import ErdosProblems.Erdos243.CubicNeighbourIdentity
import ErdosProblems.Erdos243.CumulativeLcmTransfer
import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos243.FiniteHorizonResidue
import ErdosProblems.Erdos243.IntegerRoundingBarrier
import ErdosProblems.Erdos243.LcmRecordCrossing
import ErdosProblems.Erdos243.LcmRecordDivergence
import ErdosProblems.Erdos243.LcmRecordExcess
import ErdosProblems.Erdos243.ProtectedEpochEnergy
import ErdosProblems.Erdos243.ReciprocalTailRigidity
import ErdosProblems.Erdos243.RecordIncrementBarrier
import ErdosProblems.Erdos243.SaturatedSquareTransport
import ErdosProblems.Erdos243.SlowRiseBarrier
import ErdosProblems.Erdos243.SparseResetRecovery

/-! Exact source checks for the r7 inventory.  Presence and #print output
are not a substitute for the status/statement analysis in theorem_coverage.json.
This file has not been compiled in the return environment. -/

#check ErdosProblems.Erdos243.LcmRecordCrossing.exists_crt_covering_progression
#print axioms ErdosProblems.Erdos243.LcmRecordCrossing.exists_crt_covering_progression
#check ErdosProblems.Erdos243.LcmRecordCrossing.not_summable_recordExcessWeight_of_progression
#print axioms ErdosProblems.Erdos243.LcmRecordCrossing.not_summable_recordExcessWeight_of_progression
#check ErdosProblems.Erdos243.LcmRecordExcess.rise_is_fresh
#print axioms ErdosProblems.Erdos243.LcmRecordExcess.rise_is_fresh
#check ErdosProblems.Erdos243.antitone_nat_eventually_constant
#print axioms ErdosProblems.Erdos243.antitone_nat_eventually_constant
#check ErdosProblems.Erdos243.boundedNegativePart_sylvesterNext_eventually
#print axioms ErdosProblems.Erdos243.boundedNegativePart_sylvesterNext_eventually
#check ErdosProblems.Erdos243.cancellationFree_curvature_square
#print axioms ErdosProblems.Erdos243.cancellationFree_curvature_square
#check ErdosProblems.Erdos243.centeredState_eventually_zero
#print axioms ErdosProblems.Erdos243.centeredState_eventually_zero
#check ErdosProblems.Erdos243.centeredState_zero_absorbing
#print axioms ErdosProblems.Erdos243.centeredState_zero_absorbing
#check ErdosProblems.Erdos243.centeredZero_eventually_runningMax_const
#print axioms ErdosProblems.Erdos243.centeredZero_eventually_runningMax_const
#check ErdosProblems.Erdos243.cubicProfile_square_cleared
#print axioms ErdosProblems.Erdos243.cubicProfile_square_cleared
#check ErdosProblems.Erdos243.cubic_minus_word_exact_transport_impossible
#print axioms ErdosProblems.Erdos243.cubic_minus_word_exact_transport_impossible
#check ErdosProblems.Erdos243.cubic_plus_word_exact_transport_impossible
#print axioms ErdosProblems.Erdos243.cubic_plus_word_exact_transport_impossible
#check ErdosProblems.Erdos243.eventuallyBoundedNegativePart_eventually_zero
#print axioms ErdosProblems.Erdos243.eventuallyBoundedNegativePart_eventually_zero
#check ErdosProblems.Erdos243.eventually_zero_of_summable_negativeRelativeMass_scalar
#print axioms ErdosProblems.Erdos243.eventually_zero_of_summable_negativeRelativeMass_scalar
#check ErdosProblems.Erdos243.exists_consecutiveMultiples_between
#print axioms ErdosProblems.Erdos243.exists_consecutiveMultiples_between
#check ErdosProblems.Erdos243.exists_shifted_consecutiveMultiples
#print axioms ErdosProblems.Erdos243.exists_shifted_consecutiveMultiples
#check ErdosProblems.Erdos243.forcedSurvives_iff_of_modEq_factorial
#print axioms ErdosProblems.Erdos243.forcedSurvives_iff_of_modEq_factorial
#check ErdosProblems.Erdos243.lcmLifted_step
#print axioms ErdosProblems.Erdos243.lcmLifted_step
#check ErdosProblems.Erdos243.linear_barrier_of_step_le
#print axioms ErdosProblems.Erdos243.linear_barrier_of_step_le
#check ErdosProblems.Erdos243.multiplierOverlap_persists
#print axioms ErdosProblems.Erdos243.multiplierOverlap_persists
#check ErdosProblems.Erdos243.nextTailState_eq_sub_centered
#print axioms ErdosProblems.Erdos243.nextTailState_eq_sub_centered
#check ErdosProblems.Erdos243.no_boundedRise_of_tailAvoidance
#print axioms ErdosProblems.Erdos243.no_boundedRise_of_tailAvoidance
#check ErdosProblems.Erdos243.no_constantNegative_orbit
#print axioms ErdosProblems.Erdos243.no_constantNegative_orbit
#check ErdosProblems.Erdos243.no_eventuallyConstantNegative_orbit
#print axioms ErdosProblems.Erdos243.no_eventuallyConstantNegative_orbit
#check ErdosProblems.Erdos243.no_periodicNegative_orbit
#print axioms ErdosProblems.Erdos243.no_periodicNegative_orbit
#check ErdosProblems.Erdos243.no_slowNegative_of_coprimeBlock
#print axioms ErdosProblems.Erdos243.no_slowNegative_of_coprimeBlock
#check ErdosProblems.Erdos243.no_slowRise_reducedTail
#print axioms ErdosProblems.Erdos243.no_slowRise_reducedTail
#check ErdosProblems.Erdos243.protected_epoch_energy_integer
#print axioms ErdosProblems.Erdos243.protected_epoch_energy_integer
#check ErdosProblems.Erdos243.recordAmplified_error_after_cancellation
#print axioms ErdosProblems.Erdos243.recordAmplified_error_after_cancellation
#check ErdosProblems.Erdos243.recordIncrementOne_sylvesterNext_eventually
#print axioms ErdosProblems.Erdos243.recordIncrementOne_sylvesterNext_eventually
#check ErdosProblems.Erdos243.reducedStep_coprime_currentFactor
#print axioms ErdosProblems.Erdos243.reducedStep_coprime_currentFactor
#check ErdosProblems.Erdos243.reducedStep_secondOrder
#print axioms ErdosProblems.Erdos243.reducedStep_secondOrder
#check ErdosProblems.Erdos243.reducedTail_pairwiseCoprime
#print axioms ErdosProblems.Erdos243.reducedTail_pairwiseCoprime
#check ErdosProblems.Erdos243.reducedTail_wholeModulusAvoidance
#print axioms ErdosProblems.Erdos243.reducedTail_wholeModulusAvoidance
#check ErdosProblems.Erdos243.step_rise_le_of_barrier
#print axioms ErdosProblems.Erdos243.step_rise_le_of_barrier
#check ErdosProblems.Erdos243.sylvesterDefect_mul_nextTailState
#print axioms ErdosProblems.Erdos243.sylvesterDefect_mul_nextTailState
#check ErdosProblems.Erdos243.sylvesterNext_eq_of_centered_zero
#print axioms ErdosProblems.Erdos243.sylvesterNext_eq_of_centered_zero
#check ErdosProblems.Erdos243.sylvesterNext_eventually_of_centered_zero
#print axioms ErdosProblems.Erdos243.sylvesterNext_eventually_of_centered_zero
#check ErdosProblems.Erdos243.sylvesterNext_eventually_of_summable_negativeRelativeMass_scalar
#print axioms ErdosProblems.Erdos243.sylvesterNext_eventually_of_summable_negativeRelativeMass_scalar
#check ErdosProblems.Erdos243.tailGcd_dvd_succ
#print axioms ErdosProblems.Erdos243.tailGcd_dvd_succ
#check ErdosProblems.Erdos243.tailGcd_eventuallyConstant_of_cofinally_boundedNegative
#print axioms ErdosProblems.Erdos243.tailGcd_eventuallyConstant_of_cofinally_boundedNegative
#check ErdosProblems.Erdos243.tailGcd_exists_arbitrarilyLate_constBlock_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.tailGcd_exists_arbitrarilyLate_constBlock_of_normalizedVanishes
#check ErdosProblems.Erdos243.tailGcd_strictGrowthCount_sublinear_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.tailGcd_strictGrowthCount_sublinear_of_normalizedVanishes
