import ExternalVerification243TwoModulusRecordCut.Solution

#print axioms Erdos249257.ExternalVerification243TwoModulusRecordCut.two_modulus_cut
#print axioms Erdos249257.ExternalVerification243TwoModulusRecordCut.two_modulus_record_cut
