import ErdosProblems.Erdos257.EndpointDivisorSignal
import Erdos249257.CertificateKernel

/-!
# Erdős #257: the endpoint pulse is an irrational cocycle

`EndpointDivisorSignal` identifies the two-step endpoint forcing as
`Λ_R = 2τ(2R+1) + τ(2R+2)` up to a constant and a *skipped-divisor
correction*, and records that `Λ_R` is unbounded inside one residue phase.
That unboundedness is what defeats bounded-pulse and finite-alphabet attacks —
but it is also the wrong invariant.  Sparse unbounded pulses are absorbed by a
linearly elastic state; pointwise size is not what obstructs a trapped orbit.

The right invariant is the **weighted global value** of the forcing.

## The mechanism

Divide an affine recurrence `x_{r+1} = q·x_r + a_r` by `q^{r+1}`.  It becomes a
telescoping coboundary, so for a *tempered* orbit — one with `x_r/q^r → 0`,
which any linear or polynomial trap supplies — the forcing has a forced
weighted value:

```
  ∑_{r≥0} a_r / q^{r+1} = -x_0            (affine_cocycle_tsum_eq_neg_anchor)
```

A rationally anchored tempered orbit therefore cannot integrate a forcing whose
weighted value is irrational (`no_tempered_orbit_of_irrational_forcing`).

## The value of the endpoint pulse

Even–odd decimation of the base-`2` divisor expansion is exact:

```
  Λ_R / 4^(R+1) = τ(2R+1)/2^(2R+1) + τ(2R+2)/2^(2R+2)
```

so summing gives `∑_R Λ_R/4^(R+1) = ∑_m τ(m+1)/2^(m+1)`, which
`CertificateKernel.erdosSum_full_support_eq_tsum_divisor_count` identifies with
the Erdős–Borwein constant `∑_{n≥1} 1/(2^n - 1)`.  That constant's
irrationality is **already kernel-checked in this development**
(`Erdos257PeriodNoncollapse.irrational_erdosBorwein_series`, axioms
`propext / Classical.choice / Quot.sound`), so nothing here is conditional on
an external theorem.

Conclusion: `irrational_tsum_endpointPulseTerm` — the endpoint pulse is a
single irrational base-`4` cohomology class, not a sequence of shocks.

## What this does and does not settle for the fatal branch

The live recurrence in `TwentyOneQuotientGreedy` is *not* `4x_R + c_R + Λ_R`
with `c_R` a rational-valued stream.  Its forcing is the pulse restricted to
the **selected greedy support**, i.e. `Λ_R` minus a skipped-divisor correction
generated by the orbit itself, together with an exponential `-(2^(R+1) + 1)`
term.  The exponential term is harmless — its base-`4` value is the rational
`-4/3` — but the correction is adaptive, so its weighted value is not known to
be rational.  The obstruction therefore does **not** close the branch.

What it does give is an exact necessary condition, which is the honest content
of this module: `irrational_tsum_correction_of_tempered_branch` — any tempered,
rationally anchored fatal branch forces **its own skipped-divisor correction
stream** to have an irrational base-`4` value, differing from the
Erdős–Borwein constant by a rational.  A correction stream that is eventually
periodic, or bounded-and-rationally-valued, or in any way rationally
summable, is excluded.

## Claim ceiling

**Erdős #257 remains open**, and membership of `1/21` in the achievement set is
undecided.  This module does not exclude the fatal branch; it converts the
remaining obligation from "bound the pulse" into "show the adaptive correction
cannot carry the exact irrational base-`4` value of the Erdős–Borwein
constant".
-/

namespace ErdosProblems.Erdos257

open Filter Topology

/-! ## The affine cocycle telescope -/

/-- **Finite telescope.**  Dividing an affine recurrence by `q^(r+1)` turns it
into an exact coboundary. -/
theorem affine_cocycle_telescope {q : ℝ} (hq : q ≠ 0) {x a : ℕ → ℝ}
    (hrec : ∀ r, x (r + 1) = q * x r + a r) (N : ℕ) :
    x N / q ^ N - x 0 = ∑ r ∈ Finset.range N, a r / q ^ (r + 1) := by
  induction N with
  | zero => simp
  | succ N ih =>
      rw [Finset.sum_range_succ, ← ih, hrec N]
      have hqN : q ^ N ≠ 0 := pow_ne_zero _ hq
      field_simp
      ring

/-- **The forced weighted value.**  A tempered orbit pins the weighted sum of
its own forcing to the negative of its anchor. -/
theorem affine_cocycle_tsum_eq_neg_anchor {q : ℝ} (hq : q ≠ 0) {x a : ℕ → ℝ}
    (hrec : ∀ r, x (r + 1) = q * x r + a r)
    (hsum : Summable (fun r => a r / q ^ (r + 1)))
    (htemp : Tendsto (fun r => x r / q ^ r) atTop (𝓝 0)) :
    ∑' r : ℕ, a r / q ^ (r + 1) = -x 0 := by
  have hpart : Tendsto (fun N => ∑ r ∈ Finset.range N, a r / q ^ (r + 1))
      atTop (𝓝 (∑' r : ℕ, a r / q ^ (r + 1))) := hsum.hasSum.tendsto_sum_nat
  have hpart' : Tendsto (fun N => ∑ r ∈ Finset.range N, a r / q ^ (r + 1))
      atTop (𝓝 (0 - x 0)) := by
    refine Tendsto.congr (fun N => affine_cocycle_telescope hq hrec N) ?_
    exact htemp.sub tendsto_const_nhds
  have := tendsto_nhds_unique hpart hpart'
  simpa using this

/-- **The obstruction.**  A rationally anchored tempered orbit cannot integrate
a forcing whose weighted base-`q` value is irrational. -/
theorem no_tempered_orbit_of_irrational_forcing {q : ℝ} (hq : q ≠ 0) {x a : ℕ → ℝ}
    (hrec : ∀ r, x (r + 1) = q * x r + a r)
    (hsum : Summable (fun r => a r / q ^ (r + 1)))
    (htemp : Tendsto (fun r => x r / q ^ r) atTop (𝓝 0))
    (hanchor : ¬ Irrational (x 0))
    (hforce : Irrational (∑' r : ℕ, a r / q ^ (r + 1))) : False := by
  rw [affine_cocycle_tsum_eq_neg_anchor hq hrec hsum htemp] at hforce
  exact hanchor (by simpa using hforce.neg)

/-! ## The endpoint pulse as a base-`4` class -/

open EndpointDivisorSignal in
/-- One weighted endpoint pulse term. -/
noncomputable def endpointPulseTerm (R : ℕ) : ℝ :=
  (endpointDivisorSignal R : ℝ) / 4 ^ (R + 1)

/-- One weighted divisor-count term of the base-`2` expansion. -/
noncomputable def divisorDyadicTerm (m : ℕ) : ℝ :=
  (((m + 1).divisors.card : ℝ)) / 2 ^ (m + 1)

theorem divisorDyadicTerm_nonneg (m : ℕ) : 0 ≤ divisorDyadicTerm m := by
  unfold divisorDyadicTerm; positivity

theorem summable_divisorDyadicTerm : Summable divisorDyadicTerm := by
  have h := Erdos257PeriodNoncollapse.summable_divisor_count_term 2 (by norm_num)
  refine h.congr fun m => ?_
  unfold divisorDyadicTerm
  norm_num

open EndpointDivisorSignal in
/-- **Exact even–odd decimation.**  One base-`4` pulse term is exactly two
consecutive base-`2` divisor terms. -/
theorem endpointPulseTerm_eq (R : ℕ) :
    endpointPulseTerm R = divisorDyadicTerm (2 * R) + divisorDyadicTerm (2 * R + 1) := by
  unfold endpointPulseTerm divisorDyadicTerm endpointDivisorSignal
  have h4 : (4 : ℝ) ^ (R + 1) = 2 ^ (2 * R + 2) := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, ← pow_mul]
    ring_nf
  have e1 : 2 * R + 1 = 2 * R + 1 := rfl
  rw [h4]
  have hidx1 : (2 * R + 1) = 2 * R + 1 := rfl
  have hidx2 : (2 * R + 1 + 1) = 2 * R + 2 := rfl
  rw [hidx2]
  have hp1 : (2 : ℝ) ^ (2 * R + 2) = 2 ^ (2 * R + 1) * 2 := by ring
  push_cast
  rw [hp1]
  field_simp

/-- Partial sums of the pulse are exactly even-length partial sums of the
divisor series. -/
theorem sum_range_endpointPulseTerm (N : ℕ) :
    ∑ R ∈ Finset.range N, endpointPulseTerm R =
      ∑ m ∈ Finset.range (2 * N), divisorDyadicTerm m := by
  induction N with
  | zero => simp
  | succ N ih =>
      rw [Finset.sum_range_succ, ih, endpointPulseTerm_eq,
        show 2 * (N + 1) = 2 * N + 1 + 1 by ring,
        Finset.sum_range_succ, Finset.sum_range_succ]
      ring

theorem summable_endpointPulseTerm : Summable endpointPulseTerm := by
  refine summable_of_sum_range_le (c := ∑' m, divisorDyadicTerm m) ?_ ?_
  · intro R
    rw [endpointPulseTerm_eq]
    exact add_nonneg (divisorDyadicTerm_nonneg _) (divisorDyadicTerm_nonneg _)
  · intro N
    rw [sum_range_endpointPulseTerm]
    exact Summable.sum_le_tsum _ (fun m _ => divisorDyadicTerm_nonneg m)
      summable_divisorDyadicTerm

/-- **The pulse is the Erdős–Borwein constant.**  The base-`4` endpoint pulse
series and the base-`2` divisor series are the same real number. -/
theorem tsum_endpointPulseTerm_eq_erdosBorwein :
    ∑' R : ℕ, endpointPulseTerm R = ∑' k : ℕ, (1 : ℝ) / ((2 : ℝ) ^ (k + 1) - 1) := by
  have hlam := Erdos257PeriodNoncollapse.erdosSum_full_support_eq_tsum_divisor_count 2
    (by norm_num)
  have hdiv : ∑' m : ℕ, divisorDyadicTerm m
      = ∑' m : ℕ, (((m + 1).divisors.card : ℝ)) / ((2 : ℕ) : ℝ) ^ (m + 1) := by
    refine tsum_congr fun m => ?_
    unfold divisorDyadicTerm
    norm_num
  have hA : Tendsto (fun N => ∑ R ∈ Finset.range N, endpointPulseTerm R)
      atTop (𝓝 (∑' R, endpointPulseTerm R)) :=
    summable_endpointPulseTerm.hasSum.tendsto_sum_nat
  have hB : Tendsto (fun N => ∑ m ∈ Finset.range (2 * N), divisorDyadicTerm m)
      atTop (𝓝 (∑' m, divisorDyadicTerm m)) := by
    refine summable_divisorDyadicTerm.hasSum.tendsto_sum_nat.comp ?_
    exact tendsto_atTop_atTop.mpr fun b => ⟨b, fun n hn => by omega⟩
  have hEq : ∑' R, endpointPulseTerm R = ∑' m, divisorDyadicTerm m := by
    refine tendsto_nhds_unique hA ?_
    exact Tendsto.congr (fun N => (sum_range_endpointPulseTerm N).symm) hB
  rw [hEq, hdiv, ← hlam]
  norm_num

/-- **The endpoint pulse is irrational as a base-`4` class.**  Unconditional:
the Erdős–Borwein irrationality it rests on is kernel-checked in this
development. -/
theorem irrational_tsum_endpointPulseTerm :
    Irrational (∑' R : ℕ, endpointPulseTerm R) := by
  rw [tsum_endpointPulseTerm_eq_erdosBorwein]
  exact Erdos257PeriodNoncollapse.irrational_erdosBorwein_series

/-! ## The exact surviving requirement on a fatal branch -/

/-- **The necessary condition.**  A tempered, rationally anchored orbit whose
base-`4` forcing is the endpoint pulse minus a correction stream forces that
correction to carry an irrational weighted value — namely the Erdős–Borwein
constant minus a rational.  Any rationally summable correction (in particular
any eventually periodic one) is excluded. -/
theorem irrational_tsum_correction_of_tempered_branch
    {x corr : ℕ → ℝ}
    (hrec : ∀ r, x (r + 1) = 4 * x r + ((endpointPulseTerm r * 4 ^ (r + 1)) - corr r))
    (hsum : Summable (fun r => corr r / 4 ^ (r + 1)))
    (htemp : Tendsto (fun r => x r / 4 ^ r) atTop (𝓝 0))
    (hanchor : ¬ Irrational (x 0)) :
    Irrational (∑' r : ℕ, corr r / 4 ^ (r + 1)) := by
  have h4 : (4 : ℝ) ≠ 0 := by norm_num
  have hforce : ∀ r : ℕ,
      ((endpointPulseTerm r * 4 ^ (r + 1)) - corr r) / 4 ^ (r + 1)
        = endpointPulseTerm r - corr r / 4 ^ (r + 1) := by
    intro r
    have : ((4 : ℝ)) ^ (r + 1) ≠ 0 := pow_ne_zero _ h4
    field_simp
  have hsumF : Summable
      (fun r => ((endpointPulseTerm r * 4 ^ (r + 1)) - corr r) / 4 ^ (r + 1)) := by
    refine Summable.congr (summable_endpointPulseTerm.sub hsum) fun r => ?_
    rw [hforce r]
  have hval := affine_cocycle_tsum_eq_neg_anchor h4 hrec hsumF htemp
  have hsplit : ∑' r : ℕ,
      ((endpointPulseTerm r * 4 ^ (r + 1)) - corr r) / 4 ^ (r + 1)
      = (∑' r : ℕ, endpointPulseTerm r) - ∑' r : ℕ, corr r / 4 ^ (r + 1) := by
    rw [← Summable.tsum_sub summable_endpointPulseTerm hsum]
    exact tsum_congr hforce
  rw [hsplit] at hval
  -- `∑' pulse - ∑' corr = -x 0` with `x 0` rational forces `∑' corr` irrational.
  rw [Irrational, not_not] at hanchor
  obtain ⟨q, hq⟩ := hanchor
  have hcorr : ∑' r : ℕ, corr r / 4 ^ (r + 1)
      = (∑' r : ℕ, endpointPulseTerm r) + (q : ℝ) := by
    linarith [hval]
  rw [hcorr]
  exact irrational_tsum_endpointPulseTerm.add_ratCast q

end ErdosProblems.Erdos257
