import ErdosProblems.Erdos249.PaperCompleteR20.DenominatorBounds
import Erdos249257.RepunitMobiusNumerator

#print axioms Erdos249257.RepunitMobiusNumerator.mobiusNumeratorPolynomial_eval_two
#print axioms Erdos249257.CyclotomicProjectionOfShadow.mobiusNumerator_gcd_cyclotomicValue
#print axioms Erdos249257.CyclotomicProjectionOfShadow.cyclotomicValue_dvd_baseMobiusShadow_den
#print axioms Erdos249257.MersenneShadowCyclotomicNoncollapse.upperHalfChannel_product_dvd_den_of_coprime_scale
#print axioms Erdos249257.MersenneShadowCyclotomicNoncollapse.upperHalfChannel_product_dvd_den_of_scale_primeFactors_le
#print axioms Erdos249257.MersenneShadowCyclotomicNoncollapse.lcmHeight_upperHalf_product_dvd_den
#print axioms ErdosProblems.Erdos249.PaperCompleteR20.upper_half_product_denominator_bounds
