-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
--
-- Problem-centric root for the Erdős Problems library.
--
-- `Erdos249257` holds the shared machinery: the certificate kernel, the greedy
-- achievement set, the Mersenne–Lambert ladder, and the carry systems both
-- problems are built on. This library holds the work that is stated per
-- problem and reads more naturally under the problem's own name.
--
-- Both Erdős Problem 249 (irrationality of ∑ φ(n)/2ⁿ) and Erdős Problem 257
-- (irrationality of ∑_{n∈A} 1/(2ⁿ−1) for every infinite A) are OPEN. Nothing
-- imported here decides either of them.
-- Keep the reviewed finite `t ≤ 82` certificate band inside the supported
-- root closure, so a clean root build re-elaborates its proof authority.

import ErdosProblems.AxiomAudit
import ErdosProblems.DemandLedger
import ErdosProblems.Erdos249.RankOneSharpFloor
import ErdosProblems.Erdos269.RestrictedFloorSum
import ErdosProblems.Root
import ErdosProblems.Skip.LadderT67
import ErdosProblems.Erdos68.GapScalarNormalForm
import ErdosProblems.Erdos68.PrimeThresholdParity
import ErdosProblems.Erdos68.AdjacentUnitCarryWindow
import ErdosProblems.Erdos243.RepairEntropy
import ErdosProblems.Erdos243.NewtonV8.NewtonClassificationAudit
import ErdosProblems.Erdos1049.AllRow.Audit

import ErdosProblems.Erdos1049.RationalBaseContour
import ErdosProblems.Erdos243.CubicNeighbourIdentity
import ErdosProblems.Erdos243.LcmRecordExcess
import ErdosProblems.Erdos243.PaperCompleteR11.CRTObstructionDensity
import ErdosProblems.Erdos243.PaperCompleteR11.CubicDivisorObstruction
import ErdosProblems.Erdos243.PaperCompleteR11.CubicGcdFence
import ErdosProblems.Erdos243.PaperCompleteR11.CubicIntegralNormalisation
import ErdosProblems.Erdos243.PaperCompleteR11.CubicModularDensity
import ErdosProblems.Erdos243.PaperCompleteR11.CubicPrimitiveNormalisation
import ErdosProblems.Erdos243.PaperCompleteR11.CubicWindowTransport
import ErdosProblems.Erdos243.PaperCompleteR11.CubicZeroDensityShape
import ErdosProblems.Erdos243.PaperCompleteR11.DensityTransport
import ErdosProblems.Erdos243.PaperCompleteR11.FrobeniusDescent
import ErdosProblems.Erdos243.PaperCompleteR11.ReciprocalProductAmplification
import ErdosProblems.Erdos243.PaperCompleteR11.WindowIncidence
import ErdosProblems.Erdos243.PaperCompleteR9.PolynomialCorrections
import ErdosProblems.Erdos243.SlowRiseBarrier
import ErdosProblems.Erdos249.PaperCompleteR7.KernelIntegral
import ErdosProblems.Erdos249.PaperCompleteR8.KernelRelationBasis
import ErdosProblems.Erdos249.PaperCompleteR8.UnitPivotBasis
import ErdosProblems.Erdos249.TypeBReturnV8.Audit
import ErdosProblems.Erdos249.TypeBReturnV8.CenteringCounterexample
import ErdosProblems.Erdos249.TypeBReturnV8.FiniteArithmetic
import ErdosProblems.Erdos249.TypeBReturnV8.FiniteFirstHarmonic
import ErdosProblems.Erdos249.TypeBReturnV8.PeripheralAssembly
import ErdosProblems.Erdos249.TypeBReturnV8.PeripheralFiniteBridge
import ErdosProblems.Erdos251.ActualPrimePaperR11
import ErdosProblems.Erdos251.AffineCylinderCollapse
import ErdosProblems.Erdos251.AffineShiftEscape
import ErdosProblems.Erdos251.AllResidueCarryCountermodel
import ErdosProblems.Erdos251.AllResidueLogarithmicR9
import ErdosProblems.Erdos251.BinarySourceR11
import ErdosProblems.Erdos251.BoundedPerturbationCountermodel
import ErdosProblems.Erdos251.FreePairReduction
import ErdosProblems.Erdos251.GrowingBlocksR11
import ErdosProblems.Erdos251.KernelDenominatorFloor
import ErdosProblems.Erdos251.LogarithmicCarryAsymptoticsR8
import ErdosProblems.Erdos251.LogarithmicCarryR8
import ErdosProblems.Erdos251.NonconcentrationConsequencesR11
import ErdosProblems.Erdos251.NonconcentrationCoreR11
import ErdosProblems.Erdos251.OrderLatticeDiagonal
import ErdosProblems.Erdos251.PaperBoundedCarryR7
import ErdosProblems.Erdos251.PaperCoreR7
import ErdosProblems.Erdos251.PaperFiniteCertificatesR7
import ErdosProblems.Erdos251.PaperSparseCouplingR7
import ErdosProblems.Erdos251.PaperTailBoundsR7
import ErdosProblems.Erdos251.PerturbationGrowthR11
import ErdosProblems.Erdos251.PolynomialGapSeriesValue
import ErdosProblems.Erdos251.PrimeSourceR11
import ErdosProblems.Erdos251.RealPrimeGapTail
import ErdosProblems.Erdos251.ResidueFeedbackCore
import ErdosProblems.Erdos251.ReturnedSparseWindow
import ErdosProblems.Erdos251.SparseAmbientR9
import ErdosProblems.Erdos251.SparseIntervalR8
import ErdosProblems.Erdos251.SparsePaperR11
import ErdosProblems.Erdos251.SparsePolylogR11
import ErdosProblems.Erdos251.SparseRationalisationCore
import ErdosProblems.Erdos251.SparseScheduleDensityR8
import ErdosProblems.Erdos251.SparseScheduleR8
import ErdosProblems.Erdos269.ActualSharpTailMajorantR10
import ErdosProblems.Erdos269.BlockMassEngines
import ErdosProblems.Erdos269.CertificateRangeR11
import ErdosProblems.Erdos269.CertificateSafetyR12
import ErdosProblems.Erdos269.CofinalWindowEscapeEquivalence
import ErdosProblems.Erdos269.DyadicBlockMassIdentity
import ErdosProblems.Erdos269.DyadicBlockThresholdPartition
import ErdosProblems.Erdos269.DyadicOrderedTailRecurrence
import ErdosProblems.Erdos269.DyadicRadixTailEscape
import ErdosProblems.Erdos269.DyadicShellSummability
import ErdosProblems.Erdos269.IntegralBranchExtinction
import ErdosProblems.Erdos269.IntegralBranchWidth
import ErdosProblems.Erdos269.JumpConstraintMajorant
import ErdosProblems.Erdos269.KernelCarryRank
import ErdosProblems.Erdos269.LongWindowCapR11
import ErdosProblems.Erdos269.NormalizedStateWidth
import ErdosProblems.Erdos269.PaperR12WaveAAxiomAudit
import ErdosProblems.Erdos269.PaperR7ActualOrbit
import ErdosProblems.Erdos269.PaperR7BasicAssembly
import ErdosProblems.Erdos269.PaperR7RationalBridge
import ErdosProblems.Erdos269.PaperR7SeriesIdentification
import ErdosProblems.Erdos269.PaperR7SharpShellBound
import ErdosProblems.Erdos269.PaperR7WindowResults
import ErdosProblems.Erdos269.PaperR8RankMajorant
import ErdosProblems.Erdos269.PaperR9SourceCounts
import ErdosProblems.Erdos269.PaperR9WidthData
import ErdosProblems.Erdos269.PurePowerIrrationality
import ErdosProblems.Erdos269.R12.ExactModulus
import ErdosProblems.Erdos269.R12.OcticWindowBand
import ErdosProblems.Erdos269.R12.PrefixExtension
import ErdosProblems.Erdos269.RationalLatticeReduction
import ErdosProblems.Erdos269.RationalityCarryBridge
import ErdosProblems.Erdos269.SharpWindowCapR10
import ErdosProblems.Erdos68.CanonicalFactorialTermination
import ErdosProblems.Erdos68.CarryCongruenceNormalForm
import ErdosProblems.Erdos68.CompanionConstantBridge
import ErdosProblems.Erdos68.CompanionOrbitRationality
import ErdosProblems.Erdos68.ConstantOnlyMissCertificates
import ErdosProblems.Erdos68.DivisorChannelBasis
import ErdosProblems.Erdos68.FactorialAnalyticBoundary
import ErdosProblems.Erdos68.FactorialDigitRigidity
import ErdosProblems.Erdos68.FactorialGapPlateauCore
import ErdosProblems.Erdos68.FactorialShiftFamilyOrbit
import ErdosProblems.Erdos68.FactorialZeroPlateauCertificates
import ErdosProblems.Erdos68.FactorialZeroPlateauSupplement
import ErdosProblems.Erdos68.PaperCompleteAsymptotics
import ErdosProblems.Erdos68.PaperCompleteDivisorCoordinates
import ErdosProblems.Erdos68.PaperCompleteDyadicEnclosure
import ErdosProblems.Erdos68.PaperCompleteExisting
import ErdosProblems.Erdos68.PaperCompleteFiniteLeadArithmetic
import ErdosProblems.Erdos68.PaperCompleteFiniteSizeData
import ErdosProblems.Erdos68.PaperCompleteIntegerSpan
import ErdosProblems.Erdos68.PaperCompleteKernelFloorAlgorithm
import ErdosProblems.Erdos68.PaperCompleteKernelFloorSoundness
import ErdosProblems.Erdos68.PaperCompleteLiminf
import ErdosProblems.Erdos68.PaperCompleteLowKernel
import ErdosProblems.Erdos68.PaperCompleteMomentHorizon
import ErdosProblems.Erdos68.PaperCompleteMomentIdeal
import ErdosProblems.Erdos68.PaperCompleteRadiusLimit
import ErdosProblems.Erdos68.PaperCompleteResidualIdentity
import ErdosProblems.Erdos68.PrimePoleCriterion
import ErdosProblems.Erdos68.PrimePoleDenominator
import ErdosProblems.Erdos68.SecondLayerDigit
import ErdosProblems.Erdos68.ShrinkingTargetNormalForm
import ErdosProblems.Shared.IrrationalRotationStaircase

/-!
# Problem-centric Erdős research library

This is the supported root for the problem-owned modules. The `Erdos249257`
library remains available as the reviewed #249/#257 corpus.
-/
