-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
--
-- Problem-centric root for the Erdős Problems library.
--
-- `Erdos249257` holds the shared machinery: the certificate kernel, the greedy
-- achievement set, the Mersenne–Lambert ladder, and the carry systems both
-- problems are built on. This library holds the work that is stated per
-- problem and reads more naturally under the problem's own name.
--
-- Both Erdős Problem 249 (irrationality of ∑ φ(n)/2ⁿ) and Erdős Problem 257
-- (irrationality of ∑_{n∈A} 1/(2ⁿ−1) for every infinite A) are OPEN. Nothing
-- imported here decides either of them.
-- Keep the reviewed finite `t ≤ 82` certificate band inside the supported
-- root closure, so a clean root build re-elaborates its proof authority.

import ErdosProblems.AxiomAudit
import ErdosProblems.DemandLedger
import ErdosProblems.Erdos269.RestrictedFloorSum
import ErdosProblems.Root
import ErdosProblems.Skip.LadderT67

/-!
# Problem-centric Erdős research library

This is the supported root for the problem-owned modules. The `Erdos249257`
library remains available as the reviewed #249/#257 corpus.
-/
import ErdosProblems.Erdos1041.AttachmentAwareReeb
import ErdosProblems.Erdos1041.BarycentricEnvelope
import ErdosProblems.Erdos1041.BarycentricTargetDisc
import ErdosProblems.Erdos1041.CEGMQuarticFixedPairNoGo
import ErdosProblems.Erdos1041.CassiniTreeBudget
import ErdosProblems.Erdos1041.CentroidHubBudget
import ErdosProblems.Erdos1041.ClosePairCyclicQuotientCase
import ErdosProblems.Erdos1041.CollinearRootCase
import ErdosProblems.Erdos1041.ConcyclicAlternationCounterexample
import ErdosProblems.Erdos1041.ConcyclicPotentialBound
import ErdosProblems.Erdos1041.ConcyclicSmallestGapSelectorCounterexample
import ErdosProblems.Erdos1041.ConcyclicSpokeCalculus
import ErdosProblems.Erdos1041.ConnectedClusterAreaForcing
import ErdosProblems.Erdos1041.ConnectedClusterBergman
import ErdosProblems.Erdos1041.CriticalBlaschkePairBound
import ErdosProblems.Erdos1041.CriticalEllipseMinimaxStationarity
import ErdosProblems.Erdos1041.CriticalEllipseStationaryNoGo
import ErdosProblems.Erdos1041.CriticalTwoRootProximity
import ErdosProblems.Erdos1041.CubicCriticalHub
import ErdosProblems.Erdos1041.CubicQuotientFiberCase
import ErdosProblems.Erdos1041.CyclicTetranomialCoefficientCase
import ErdosProblems.Erdos1041.CyclicTrinomialFiberCase
import ErdosProblems.Erdos1041.DegenerateHubMonodromyKernel
import ErdosProblems.Erdos1041.EvenSymmetricTrinomialCase
import ErdosProblems.Erdos1041.ExteriorBlaschkeFibreCapacityGap
import ErdosProblems.Erdos1041.FormACutFirstNonzeroMode
import ErdosProblems.Erdos1041.FormACutQuantitativeExpansion
import ErdosProblems.Erdos1041.GenericSufficiencyClosure
import ErdosProblems.Erdos1041.LevelSeparation
import ErdosProblems.Erdos1041.MergeTreeDiscriminantDichotomy
import ErdosProblems.Erdos1041.NearFeketeHubOrbit
import ErdosProblems.Erdos1041.NearFeketeTransverseClosure
import ErdosProblems.Erdos1041.NearFeketeUniqueNewtonFaceClosure
import ErdosProblems.Erdos1041.NewtonFlowRaySeparation
import ErdosProblems.Erdos1041.PrimitiveQuinticBoundaryTail
import ErdosProblems.Erdos1041.PrimitiveQuinticInteriorTail
import ErdosProblems.Erdos1041.ProperComponentCapacityGap
import ErdosProblems.Erdos1041.QuarticQuotientFiberCase
import ErdosProblems.Erdos1041.QuinticCanonicalMixedSlice
import ErdosProblems.Erdos1041.QuinticEqualityCubicExtension
import ErdosProblems.Erdos1041.QuinticEqualityTetrahedron
import ErdosProblems.Erdos1041.QuinticFinitePerturbationTransfer
import ErdosProblems.Erdos1041.QuinticMixedGlobalAtlas
import ErdosProblems.Erdos1041.QuinticMixedTransitionResolution
import ErdosProblems.Erdos1041.QuinticRadialDominantCone
import ErdosProblems.Erdos1041.QuinticSecondModeConnector
import ErdosProblems.Erdos1041.QuinticTransverseFiniteTransfer
import ErdosProblems.Erdos1041.ReciprocalNewtonExpansion
import ErdosProblems.Erdos1041.RefinedQuinticClosePair
import ErdosProblems.Erdos1041.SelfInversiveComparisonDual
import ErdosProblems.Erdos1041.SexticAnisotropicCubicCone
import ErdosProblems.Erdos1041.SexticCanonicalMixedSlice
import ErdosProblems.Erdos1041.SexticCanonicalNeighborhoodGluing
import ErdosProblems.Erdos1041.SexticChordCoveringCriterion
import ErdosProblems.Erdos1041.SexticCubicFaceConnectorNoGo
import ErdosProblems.Erdos1041.SexticCubicPairedDeficitCone
import ErdosProblems.Erdos1041.SexticCubicRadialDeficitCone
import ErdosProblems.Erdos1041.SexticCubicTransitionCone
import ErdosProblems.Erdos1041.SexticFirstModeDominantTangentCone
import ErdosProblems.Erdos1041.SexticFirstModeOverlapCone
import ErdosProblems.Erdos1041.SexticFirstModeThreeQuarterOverlap
import ErdosProblems.Erdos1041.SexticMixedCubicLiftWindow
import ErdosProblems.Erdos1041.SexticMixedFullCubicAxis
import ErdosProblems.Erdos1041.SexticMixedOriginSpokeNoGo
import ErdosProblems.Erdos1041.SexticMixedTruncatedNeighborhood
import ErdosProblems.Erdos1041.SexticNormalizedCubicCompactness
import ErdosProblems.Erdos1041.SexticNullBranch
import ErdosProblems.Erdos1041.SexticNullBranchCompanion
import ErdosProblems.Erdos1041.SexticNullBranchFiniteTransfer
import ErdosProblems.Erdos1041.SexticNullBranchGlobalBoxAtlas
import ErdosProblems.Erdos1041.SexticNullBranchSecondOrderAtlas
import ErdosProblems.Erdos1041.SexticNullBranchTransverseSelector
import ErdosProblems.Erdos1041.SexticNullBranchUniformMargin
import ErdosProblems.Erdos1041.SexticSecondModeCubicLift
import ErdosProblems.Erdos1041.SexticSecondModePhaseCircle
import ErdosProblems.Erdos1041.SexticSecondModeStrictPhaseArc
import ErdosProblems.Erdos1041.SharpCollinearAlternation
import ErdosProblems.Erdos1041.SharpCollinearChebyshev
import ErdosProblems.Erdos1041.TetranomialElementarySymmetricSelector
import ErdosProblems.Erdos1041.TetranomialL2Selector
import ErdosProblems.Erdos1041.TetranomialProductSensitiveSelector
import ErdosProblems.Erdos1041.TetranomialReciprocalMomentSelector
import ErdosProblems.Erdos1041.TetranomialTailProductSelector
import ErdosProblems.Erdos1041.TiedNewtonFaceAdjacentEllipse
import ErdosProblems.Erdos1041.TiedNewtonFaceAsymmetricDiameterTube
import ErdosProblems.Erdos1041.TiedNewtonFaceBlockL1NoGo
import ErdosProblems.Erdos1041.TiedNewtonFaceBlockL1PolyhedralCell
import ErdosProblems.Erdos1041.TiedNewtonFaceBlockL1RationalChart
import ErdosProblems.Erdos1041.TiedNewtonFaceBlockL1RationalRescue
import ErdosProblems.Erdos1041.TiedNewtonFaceComplexDiameterTransfer
import ErdosProblems.Erdos1041.TiedNewtonFaceComplexDiameterTube
import ErdosProblems.Erdos1041.TiedNewtonFaceComponentSelector
import ErdosProblems.Erdos1041.TiedNewtonFaceCriticalTrace
import ErdosProblems.Erdos1041.TiedNewtonFaceEvenSymmetricDiameter
import ErdosProblems.Erdos1041.TiedNewtonFaceFibreProduct
import ErdosProblems.Erdos1041.TiedNewtonFaceHorizontalFibreHubwiseNoGo
import ErdosProblems.Erdos1041.TiedNewtonFaceMinimumRealSelectorNoGo
import ErdosProblems.Erdos1041.TiedNewtonFaceNonAdjacentNoGo
import ErdosProblems.Erdos1041.TiedNewtonFacePairedTrace
import ErdosProblems.Erdos1041.TiedNewtonFacePointwiseL1NoGo
import ErdosProblems.Erdos1041.TiedNewtonFacePositiveFibreRationalRescue
import ErdosProblems.Erdos1041.TiedNewtonFaceRationalHubRescue
import ErdosProblems.Erdos1041.TiedNewtonFaceTwoSpokeNoGo
import ErdosProblems.Erdos1041.TrinomialInterpolationSpoke
import ErdosProblems.Erdos1041.TwoSegmentLevelIdentityRefutation
import ErdosProblems.Erdos1041.TwoSmallestRootTruncation
import ErdosProblems.Erdos1049.AdelicHeightBridge
import ErdosProblems.Erdos1049.BezoutPluckerJets
import ErdosProblems.Erdos1049.FixedDiagonalRationalClearing
import ErdosProblems.Erdos1049.QAperyTailDenominator
import ErdosProblems.Erdos1049.SoutheastBlockDeterminant
import ErdosProblems.Erdos1049.TwoSelectorRemainderEscape
import ErdosProblems.Erdos1049.ZudilinConeArithmetic
import ErdosProblems.Erdos243.CenteredEuclideanFeedback
import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos243.FiniteHorizonResidue
import ErdosProblems.Erdos243.HorizonEscapeOfMass
import ErdosProblems.Erdos243.OrientedFeedbackRoot
import ErdosProblems.Erdos243.RepairEntropy
import ErdosProblems.Erdos243.WeightedCRTRepair
import ErdosProblems.Erdos249.CyclotomicAnchoredKill
import ErdosProblems.Erdos249.FiniteEulerSieve
import ErdosProblems.Erdos249.FullDepthRayAmplifier
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos249.PrimeRayCyclotomicCurvature
import ErdosProblems.Erdos249.RankOneSharpFloor
import ErdosProblems.Erdos249.RankOneSubrankObstruction
import ErdosProblems.Erdos249.TotientAffineModeEscape
import ErdosProblems.Erdos249.TotientStrictPrimeEscape
import ErdosProblems.Erdos251.AffineCylinderCollapse
import ErdosProblems.Erdos251.AffineShiftEscape
import ErdosProblems.Erdos251.OrderLatticeDiagonal
import ErdosProblems.Erdos257.AffineCocycleObstruction
import ErdosProblems.Erdos257.CenteredCarryPullbackBalance
import ErdosProblems.Erdos257.EndpointDivisorSignal
import ErdosProblems.Erdos257.FatalBorrowCofiniteCarryTransfer
import ErdosProblems.Erdos257.FatalBorrowMiddleScaleContradiction
import ErdosProblems.Erdos257.FatalBorrowMidpointTransfer
import ErdosProblems.Erdos257.FatalBorrowPositiveResidualPacket
import ErdosProblems.Erdos257.FatalBorrowZeroFractionalSqueeze
import ErdosProblems.Erdos257.FatalCriticalDangerEndpointReduction
import ErdosProblems.Erdos257.FourNinthsCofinalRepairConsumer
import ErdosProblems.Erdos257.FourNinthsCoinCancellation
import ErdosProblems.Erdos257.FourNinthsMidpointCarryReachability
import ErdosProblems.Erdos257.FourNinthsNegativeCarryNoGo
import ErdosProblems.Erdos257.FourNinthsQuotientCompactness
import ErdosProblems.Erdos257.FourNinthsQuotientDefect
import ErdosProblems.Erdos257.FourNinthsSkippedTwoAdicAntiConcentration
import ErdosProblems.Erdos257.FourNinthsUpperSaturation
import ErdosProblems.Erdos257.HalfCounterexampleFrontier
import ErdosProblems.Erdos257.MersenneSubseriesRigidity
import ErdosProblems.Erdos257.PrimeSlackTwoValued
import ErdosProblems.Erdos257.SelectedAncestryBudget
import ErdosProblems.Erdos257.SelectedAncestryTailSurvival
import ErdosProblems.Erdos257.SelectedFirstWindowCharge
import ErdosProblems.Erdos257.SelectedFirstWindowQuotientLift
import ErdosProblems.Erdos257.SocketRunRationalCap
import ErdosProblems.Erdos257.TotientFourNinthsCylinderTransport
import ErdosProblems.Erdos269.BlockMassEngines
import ErdosProblems.Erdos269.CarryLiftExtinction
import ErdosProblems.Erdos269.DyadicBlockMassIdentity
import ErdosProblems.Erdos269.DyadicBlockThresholdPartition
import ErdosProblems.Erdos269.DyadicOrderedTailRecurrence
import ErdosProblems.Erdos269.DyadicRadixTailEscape
import ErdosProblems.Erdos269.DyadicShellSummability
import ErdosProblems.Erdos269.HalfHeightDenominatorTransport
import ErdosProblems.Erdos269.IntegralBranchExtinction
import ErdosProblems.Erdos269.KernelCarryRank
import ErdosProblems.Erdos269.PurePowerIrrationality
import ErdosProblems.Erdos269.RationalLatticeReduction
import ErdosProblems.Erdos269.ResidueEscape
import ErdosProblems.Erdos269.ThreeChannelBlockRigidity
import ErdosProblems.Erdos269.ThreePrimeRunningLcm
import ErdosProblems.Erdos269.WeightedPhaseCarry
import ErdosProblems.Erdos68.AdjacentUnitCarryWindow
import ErdosProblems.Erdos68.AffineDefectRigidity
import ErdosProblems.Erdos68.BinaryCarryNormalForm
import ErdosProblems.Erdos68.CarryCongruenceNormalForm
import ErdosProblems.Erdos68.ChannelIntegralCongruence
import ErdosProblems.Erdos68.CompanionConstantBridge
import ErdosProblems.Erdos68.ConstantOnlyMissCertificates
import ErdosProblems.Erdos68.FactorialCarry
import ErdosProblems.Erdos68.FactorialChannelCertificate
import ErdosProblems.Erdos68.FactorialDigitRigidity
import ErdosProblems.Erdos68.FactorialZeroPlateau
import ErdosProblems.Erdos68.GapScalarNormalForm
import ErdosProblems.Erdos68.HyperbolicPeeling
import ErdosProblems.Erdos68.PrimeThresholdParity
import ErdosProblems.Erdos68.PrimeZeroBranch
import ErdosProblems.Erdos68.RunCylinder
import ErdosProblems.Erdos68.SecondLayerDigit
import ErdosProblems.Erdos68.ShrinkingTargetNormalForm
import ErdosProblems.IntModEq
import ErdosProblems.Shared.IrrationalRotationStaircase
