import ErdosProblems.Erdos249.PaperCompleteR7

/-! Unrun compilation/axiom audit of returned proof endpoints. -/

#check ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.negative_separation_counterexample
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.negative_separation_counterexample
#check ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.no_zero_period_certificate
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.no_zero_period_certificate
#check ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unguarded_simultaneous_periods_impossible
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unguarded_simultaneous_periods_impossible
#check ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unrestricted_residual_determinant_counterexample
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unrestricted_residual_determinant_counterexample
#check ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unrestricted_residual_row_counterexample
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.DisplayedNoGo.unrestricted_residual_row_counterexample
#check ErdosProblems.Erdos249.PaperCompleteR7.GenericCertificates.generic_soundness
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.GenericCertificates.generic_soundness
#check ErdosProblems.Erdos249.PaperCompleteR7.GenericCertificates.generic_tail_period
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.GenericCertificates.generic_tail_period
#check ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.irrational_positiveValue_of_unit
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.irrational_positiveValue_of_unit
#check ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.rational_zmod_observable_iff
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.rational_zmod_observable_iff
#check ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.residue_series_sharp_range
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.residue_series_sharp_range
#check ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.short_note_residue_theorem
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.short_note_residue_theorem
#check ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.zmod_observable_value
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.zmod_observable_value
#check ErdosProblems.Erdos249.PaperCompleteR7.bounded_isolated_pulse
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.bounded_isolated_pulse
#check ErdosProblems.Erdos249.PaperCompleteR7.canonical_mersenne_gap_iff
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.canonical_mersenne_gap_iff
#check ErdosProblems.Erdos249.PaperCompleteR7.common_window_upto_sixteen
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.common_window_upto_sixteen
#check ErdosProblems.Erdos249.PaperCompleteR7.complete_level_zero_rank
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.complete_level_zero_rank
#check ErdosProblems.Erdos249.PaperCompleteR7.fullDepth_amplification
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.fullDepth_amplification
#check ErdosProblems.Erdos249.PaperCompleteR7.generic_absolute_adjugate_floor
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.generic_absolute_adjugate_floor
#check ErdosProblems.Erdos249.PaperCompleteR7.generic_tempered_equivalence_and_rigidity
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.generic_tempered_equivalence_and_rigidity
#check ErdosProblems.Erdos249.PaperCompleteR7.int_span_allBaseThroughLevelFamily_eq
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.int_span_allBaseThroughLevelFamily_eq
#check ErdosProblems.Erdos249.PaperCompleteR7.integralTotientKernelBasis
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.integralTotientKernelBasis
#check ErdosProblems.Erdos249.PaperCompleteR7.irrational_totient_iff_moebius_square
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.irrational_totient_iff_moebius_square
#check ErdosProblems.Erdos249.PaperCompleteR7.long_record_rankOne_additional_clauses
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.long_record_rankOne_additional_clauses
#check ErdosProblems.Erdos249.PaperCompleteR7.low_rungs_with_literal_totient_series
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.low_rungs_with_literal_totient_series
#check ErdosProblems.Erdos249.PaperCompleteR7.odd_agreement_rational_control
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.odd_agreement_rational_control
#check ErdosProblems.Erdos249.PaperCompleteR7.paper_maximal_power_reduction
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.paper_maximal_power_reduction
#check ErdosProblems.Erdos249.PaperCompleteR7.periodic_freezing
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.periodic_freezing
#check ErdosProblems.Erdos249.PaperCompleteR7.positive_rankOne_floor
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.positive_rankOne_floor
#check ErdosProblems.Erdos249.PaperCompleteR7.positive_rational_gap
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.positive_rational_gap
#check ErdosProblems.Erdos249.PaperCompleteR7.totient_absolute_adjugate_floor
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.totient_absolute_adjugate_floor
#check ErdosProblems.Erdos249.PaperCompleteR7.unique_terminal_parity_and_nonzero
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.unique_terminal_parity_and_nonzero
