import Erdos257PeriodNoncollapse.CertificateKernel
import Erdos257PeriodNoncollapse.GapFareyBound
import Erdos257PeriodNoncollapse.GcdMomentCalculus
import Erdos257PeriodNoncollapse.GenericTailOrbitRigidity
import Erdos257PeriodNoncollapse.GeometricCoprimality
import Erdos257PeriodNoncollapse.LcmConeFlatness
import Erdos257PeriodNoncollapse.LcmConeNonflat
import Erdos257PeriodNoncollapse.LcmDiagonalReduction
import Erdos257PeriodNoncollapse.SignedQMomentObstruction
import Erdos257PeriodNoncollapse.TotientActualLcmOrbitSign
import Erdos257PeriodNoncollapse.TotientActualLcmTopEdgeStaircase
import Erdos257PeriodNoncollapse.TotientCarryKernelRigidity
import Erdos257PeriodNoncollapse.TotientMahlerDefect
import Erdos257PeriodNoncollapse.TotientTailPeriodKiller
import Erdos257PeriodNoncollapse.TropicalCurvatureCarry
import ErdosProblems.Erdos249.RankOneSubrankObstruction

/-! Inherited exact endpoints selected by the coverage review.
This file has NOT been run. #check verifies a name/type, not its correspondence
to a TeX theorem. #print axioms exposes dependencies; no replay is claimed. -/

#check Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcmTailDiff_shift_pos
#print axioms Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcmTailDiff_shift_pos
#check Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_integral_forces_topEdgeResidue
#print axioms Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_integral_forces_topEdgeResidue
#check Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_trueEndpointSurvivor_neg
#print axioms Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_trueEndpointSurvivor_neg
#check Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.not_actualLcmTerminalDyadicStaircase_of_room
#print axioms Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.not_actualLcmTerminalDyadicStaircase_of_room
#check Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.puncturedDyadicStaircase_penultimate_eq_half
#print axioms Erdos257PeriodNoncollapse.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.puncturedDyadicStaircase_penultimate_eq_half
#check Erdos257PeriodNoncollapse.SignedQMomentObstruction.mobiusMersenneTheta_strict_logConcave
#print axioms Erdos257PeriodNoncollapse.SignedQMomentObstruction.mobiusMersenneTheta_strict_logConcave
#check Erdos257PeriodNoncollapse.SignedQMomentObstruction.mobiusMersenneTwoAtom_hankelGap
#print axioms Erdos257PeriodNoncollapse.SignedQMomentObstruction.mobiusMersenneTwoAtom_hankelGap
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.certifiedKill_depth_floor
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.certifiedKill_depth_floor
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.eq_prime_pow_of_not_dvd_periodLcm
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.eq_prime_pow_of_not_dvd_periodLcm
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_certifiedKill_iff_guardCylinderWitness
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_certifiedKill_iff_guardCylinderWitness
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_certifiedKill_iff_tail_diff_notMem_int
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_certifiedKill_iff_tail_diff_notMem_int
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_nonintegral_pair_of_coneNonflatCert
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.exists_nonintegral_pair_of_coneNonflatCert
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.fixedPrecisionTropicalNoGo
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.fixedPrecisionTropicalNoGo
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.irrational_totient_series_iff_certificate_supply
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.irrational_totient_series_iff_certificate_supply
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.irrational_totient_series_of_lcm_diagonal_certificate_supply
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.irrational_totient_series_of_lcm_diagonal_certificate_supply
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.tail_diff_int_of_den_dvd
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.tail_diff_int_of_den_dvd
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.tail_diff_notMem_int_of_certifiedKill
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.tail_diff_notMem_int_of_certifiedKill
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.totient_periodLcm_ray_split
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.totient_periodLcm_ray_split
#check Erdos257PeriodNoncollapse.TotientTailPeriodKiller.two_pow_mul_totient_series_eq
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.two_pow_mul_totient_series_eq
#check Erdos257PeriodNoncollapse.doublingOrbit_eq_zero_of_tempered
#print axioms Erdos257PeriodNoncollapse.doublingOrbit_eq_zero_of_tempered
#check Erdos257PeriodNoncollapse.irrational_of_den_mul_abs_sub_tendsto_zero
#print axioms Erdos257PeriodNoncollapse.irrational_of_den_mul_abs_sub_tendsto_zero
#check Erdos257PeriodNoncollapse.irrational_totient_series_of_lcm_cone_window_kill_supply
#print axioms Erdos257PeriodNoncollapse.irrational_totient_series_of_lcm_cone_window_kill_supply
#check Erdos257PeriodNoncollapse.linearIndependent_of_separatedMinorCertificate
#print axioms Erdos257PeriodNoncollapse.linearIndependent_of_separatedMinorCertificate
#check Erdos257PeriodNoncollapse.not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#print axioms Erdos257PeriodNoncollapse.not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#check Erdos257PeriodNoncollapse.rational_totient_series_forces_lcm_cone_flatness
#print axioms Erdos257PeriodNoncollapse.rational_totient_series_forces_lcm_cone_flatness
#check Erdos257PeriodNoncollapse.tsum_moebius_div_two_pow_sub_one_sq_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms Erdos257PeriodNoncollapse.tsum_moebius_div_two_pow_sub_one_sq_ne_int_div_of_den_le_39819823323350687661677887437915526
#check Erdos257PeriodNoncollapse.tsum_totient_div_pow_two_ne_ratCast_of_den_le_79639646646701375323355774875831053
#print axioms Erdos257PeriodNoncollapse.tsum_totient_div_pow_two_ne_ratCast_of_den_le_79639646646701375323355774875831053
#check ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt
#check GapFareyBound.farey_gap
#print axioms GapFareyBound.farey_gap
#check GapFareyBound.gap_check_window_1_240_first_failure
#print axioms GapFareyBound.gap_check_window_1_240_first_failure
#check GcdMomentCalculus.tsum_lambert_linear_weight_sq_pure
#print axioms GcdMomentCalculus.tsum_lambert_linear_weight_sq_pure
#check GcdMomentCalculus.tsum_pos_coprime_inv_mersenne_eq_one
#print axioms GcdMomentCalculus.tsum_pos_coprime_inv_mersenne_eq_one
#check GeometricCoprimality.card_antidiagonal_filter_pos_coprime
#print axioms GeometricCoprimality.card_antidiagonal_filter_pos_coprime
#check GeometricCoprimality.tsum_pos_coprime_lambert_eq_sq
#print axioms GeometricCoprimality.tsum_pos_coprime_lambert_eq_sq
