-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 6f9f5f13f3af5159415b66bace072f361c5de63f (Lean tree 6410fad4b9daafa52a8e10cd18787f1f3f712940). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos243.PaperCompleteR21.ExactOrbitRecordDichotomy
import ErdosProblems.Erdos243.PaperCompleteR21.MaximalGapConstant
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedDenominatorPrimePowers
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedStepLocalArithmetic
import ErdosProblems.Erdos243.PaperCompleteR21.WindowAvoidance

/-! # Erdos243: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.oddPrimePower_supply
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_avoiding_in_window
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_multiplier_ge_four
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_slow_rise_avoiding_sequence
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.maximal_gap_limsup_eq_inv_sigma
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.unit_word_saturates_old_modulus
