-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos251.PaperCompleteR20.FiniteSeparation
import ErdosProblems.Erdos251.PaperCompleteR21.JointPrimeGapCountermodel
import ErdosProblems.Erdos251.PaperCompleteR21.PerturbedPrimePositions
import ErdosProblems.Erdos251.PaperCompleteR21.TwoWindowSparsity

/-! # Erdos251: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos251.PaperCompleteR20.finite_separation_complete
derive_idle ErdosProblems.Erdos251.PaperCompleteR20.one_tail_signed_certificate
derive_idle ErdosProblems.Erdos251.PaperCompleteR21.long_joint_prime_gap_countermodel

-- Derivations the export does not decide in advance: conjuncts a proof may establish
-- without an open hypothesis, and frontiers with the consequences the graph records as
-- proved by corpus theorems discharged. A command that adds nothing warns.
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos251.PaperCompleteR21.long_joint_prime_gap_countermodel
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos251.PaperCompleteR21.nonconcentration_does_not_force_irrationality
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos251.PaperCompleteR21.prime_gap_two_window_sparse
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos251.PaperCompleteR21.short_joint_prime_gap_countermodel
