-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 6f9f5f13f3af5159415b66bace072f361c5de63f (Lean tree 6410fad4b9daafa52a8e10cd18787f1f3f712940). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos1049.PaperCompleteR21.RationalBaseThreshold

/-! # Erdos1049: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_measure_uniform
derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_threshold
derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_threshold_log
