-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos1041.PaperCompleteR21.ConstantFactorAreaCriteria
import ErdosProblems.Erdos1041.PaperCompleteR21.CriticalValueSeparationTransport
import ErdosProblems.Erdos1041.PaperCompleteR21.HyperbolicLawOfCosines
import ErdosProblems.Erdos1041.PaperCompleteR21.SeparationParent
import ErdosProblems.Erdos1041.PaperCompleteR21.SubcriticalPerimeterPath

/-! # Erdos1041: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.Hyperbolic.le_of_lam_le
derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.SeparationParent.separation_parent
derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.cfaArity_length_le
derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.discSep_cubic_six_fifths
derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.discSep_uniform_radius
derive_idle ErdosProblems.Erdos1041.PaperCompleteR21.subcritical_perimeter_path_paper
