-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 6f9f5f13f3af5159415b66bace072f361c5de63f (Lean tree 6410fad4b9daafa52a8e10cd18787f1f3f712940). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos269.PaperCompleteR21.TwoPrimeSums
import ErdosProblems.Erdos269.PaperR7BasicAssembly
import ErdosProblems.Erdos269.PaperR7WindowResults

/-! # Erdos269: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos269.PaperR7.long_no_bounded_length
derive_idle ErdosProblems.Erdos269.PaperR7.long_window_growth
derive_idle ErdosProblems.Erdos269.PaperR7.paper_uniform_rank_and_nonseparation
derive_weakening ErdosProblems.Erdos269.PaperCompleteR21.transcendental_heckeValue
derive_weakening ErdosProblems.Erdos269.PaperCompleteR21.two_prime_sums_transcendental
derive_frontier ErdosProblems.Erdos269.PaperCompleteR21.two_prime_sums_transcendental
derive_weakening ErdosProblems.Erdos269.PaperCompleteR21.two_prime_transcendence
derive_frontier ErdosProblems.Erdos269.PaperCompleteR21.two_prime_transcendence
derive_frontier ErdosProblems.Erdos269.PaperCompleteR21.two_prime_transcendence at ErdosProblems.Erdos269.PaperCompleteR21.transcendental_heckeValue
