-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revisions 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 and 4bcc5ecbf9a4720c53a1e4c22740f4f1e91041d5 combined (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos1049.PaperCompleteR21.RationalBaseThreshold

/-! # Erdos1049: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_measure_uniform
derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_threshold
derive_idle ErdosProblems.Erdos1049.PaperCompleteR21.rational_base_threshold_log
