-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos68.PaperCompletePrimePole

/-! # Erdos68: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos68.PaperComplete.maximal_prime_power_survival
