-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revisions 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 and 4bcc5ecbf9a4720c53a1e4c22740f4f1e91041d5 combined (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos243.PaperCompleteR21.AmplifiedRecordEquivalence
import ErdosProblems.Erdos243.PaperCompleteR21.ExactOrbitRecordDichotomy
import ErdosProblems.Erdos243.PaperCompleteR21.MaximalGapConstant
import ErdosProblems.Erdos243.PaperCompleteR21.RecordJumpEnergySeries
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedDenominatorPrimePowers
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedStepLocalArithmetic
import ErdosProblems.Erdos243.PaperCompleteR21.WindowAvoidance

/-! # Erdos243: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.oddPrimePower_supply
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_avoiding_in_window
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_multiplier_ge_four
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_slow_rise_avoiding_sequence
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.maximal_gap_limsup_eq_inv_sigma
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.unit_word_saturates_old_modulus

-- Derivations the export does not decide in advance: conjuncts a proof may establish
-- without an open hypothesis, and frontiers with the consequences the graph records as
-- proved by corpus theorems discharged. A command that adds nothing warns.
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.Rdelta_bddAbove_iff_amp
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.amp_bddAbove_iff_sylvester
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.coprimeMultiplier_cofinal
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.criticalRate
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.criticalRate_counterexample
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.energySqrt_summable_iff
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.energy_criterion
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.energy_summable_iff
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.exists_late_energy_window
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.largePrime_coprimeMultiplier
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.oddPrimePower_supply
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.oddPrimePower_supply_nat
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.primeBlock_supply
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.recordAmplified
set_option argumentGraph.strict false in derive_conjuncts ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.unitRecordIncrement_criterion
