-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision 5176d8878036549d6e35a4cb42d8e26fdb3e4b46 (Lean tree ca2f57c9c7e461d54d2617d2ae33016ec7481567). Do not edit by hand.

import ErdosProblems.ArgumentGraph.Derive
import ErdosProblems.Erdos243.PaperCompleteR21.ExactOrbitRecordDichotomy
import ErdosProblems.Erdos243.PaperCompleteR21.MaximalGapConstant
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedDenominatorPrimePowers
import ErdosProblems.Erdos243.PaperCompleteR21.ReducedStepLocalArithmetic
import ErdosProblems.Erdos243.PaperCompleteR21.WindowAvoidance

/-! # Erdos243: theorems derived from what the paper results' proofs use

Each command below rebuilds, as a library theorem the kernel checks, a finding of
the argument graph about a theorem the papers cite. See
`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/

set_option argumentGraph.strict true
set_option maxHeartbeats 4000000

derive_idle ErdosProblems.Erdos243.PaperCompleteR21.StandingOrbit.oddPrimePower_supply
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_avoiding_in_window
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_multiplier_ge_four
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.exists_slow_rise_avoiding_sequence
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.maximal_gap_limsup_eq_inv_sigma
derive_idle ErdosProblems.Erdos243.PaperCompleteR21.unit_word_saturates_old_modulus
