import Mathlib.GroupTheory.Perm.Cycle.Basic

/-!
# Erdős #1041: the cyclic-monodromy kernel for a degenerate hub

The analytic unique-branch repair reduces its algebraic step to this fact.  If
the monodromy of a connected finite cover is generated by one permutation,
transitivity forces that generator to move every sheet and to be one full
cycle.  Covering-space connectedness and the identification of local degrees
with cycle lengths remain analytic inputs; they are not postulated here.
-/

namespace ErdosProblems.Erdos1041

/-- A transitive action by the integer powers of one permutation has no fixed
point, provided the underlying type has at least two points. -/
theorem transitive_zpowers_move_every_point
    {α : Type*} [Nontrivial α]
    (σ : Equiv.Perm α)
    (htrans : ∀ x y, ∃ n : ℤ, (σ ^ n) x = y) :
    ∀ x, σ x ≠ x := by
  intro x hx
  obtain ⟨y, hyx⟩ := exists_ne x
  obtain ⟨n, hn⟩ := htrans x y
  have hnfix : (σ ^ n) x = x :=
    Equiv.Perm.zpow_apply_eq_self_of_apply_eq_self hx n
  exact hyx (hn.symm.trans hnfix)

/-- A cyclic monodromy generator acting transitively on a nontrivial fibre is
one cycle.  This is the finite algebraic core of the unique-branch argument. -/
theorem transitive_zpowers_isCycle
    {α : Type*} [Nontrivial α]
    (σ : Equiv.Perm α)
    (htrans : ∀ x y, ∃ n : ℤ, (σ ^ n) x = y) :
    σ.IsCycle := by
  let x : α := Classical.choice inferInstance
  refine ⟨x, transitive_zpowers_move_every_point σ htrans x, ?_⟩
  intro y _hy
  exact htrans x y

/-- On a finite fibre, transitive cyclic monodromy has full support. -/
theorem transitive_zpowers_support_eq_univ
    {α : Type*} [Fintype α] [DecidableEq α] [Nontrivial α]
    (σ : Equiv.Perm α)
    (htrans : ∀ x y, ∃ n : ℤ, (σ ^ n) x = y) :
    σ.support = Finset.univ := by
  have hmove := transitive_zpowers_move_every_point σ htrans
  ext x
  simp [hmove x]

/-- The combined certificate used by the degenerate-hub proof: a transitive
cyclic action on a finite nontrivial fibre is a full-support single cycle. -/
theorem transitive_zpowers_fullCycle
    {α : Type*} [Fintype α] [DecidableEq α] [Nontrivial α]
    (σ : Equiv.Perm α)
    (htrans : ∀ x y, ∃ n : ℤ, (σ ^ n) x = y) :
    σ.IsCycle ∧ σ.support = Finset.univ :=
  ⟨transitive_zpowers_isCycle σ htrans,
    transitive_zpowers_support_eq_univ σ htrans⟩

end ErdosProblems.Erdos1041
