-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0

-- Current-source whole-statement audit for Erdős 257.
-- 35 paper environments; 66 declaration endpoints.

import Erdos249257.AllBaseReciprocalSupportIrrationality
import Erdos249257.BooleanMobiusCarry
import Erdos249257.BooleanMobiusCriticalCapacityCofinal
import Erdos249257.BooleanMobiusGreedyReduction
import Erdos249257.CertificateKernel
import Erdos249257.GenericTailOrbitRigidity
import Erdos249257.GreedyAchievementSet
import Erdos249257.HalfCarryReachability
import Erdos249257.HalfCutLocator
import Erdos249257.HalfCylinderFatalGapRightTail
import Erdos249257.HalfCylinderFixedTailSocket
import Erdos249257.HalfCylinderHalfMembershipClassification
import Erdos249257.HalfCylinderIntegerGreedy
import Erdos249257.SuffixCylinderTerminalOnlyBridge
import Erdos249257.TropicalCurvatureCarry
import Erdos249257.TwentyOneQuotientGreedy
import ErdosProblems.Erdos257.MersenneSubseriesRigidity
import ErdosProblems.Erdos257.PaperCompleteR8.ArbitraryWeightMixedClaim
import ErdosProblems.Erdos257.PaperCompleteR8.PositiveCoverReturn
import ErdosProblems.Erdos257.PaperCompleteR8.WeightedHereditaryClaim
import ErdosProblems.Erdos257.PaperCompleteR8.WeightedReturn

#print axioms Erdos249257.IsStraddlePrefix.half_agrees_greedy
#print axioms Erdos249257.IsStraddlePrefix.half_step_forced
#print axioms Erdos249257.HalfCylinderIntegerGreedy.PerturbedFamily.AdjacentCut.nextRemainder_trichotomy
#print axioms Erdos249257.HalfCylinderIntegerGreedy.PerturbedFamily.AdjacentCut.prefixChoice_maximal
#print axioms Erdos249257.SuffixCylinderTerminalOnlyBridge.exists_infinite_positive_support_half_of_cofinalCylinderStages
#print axioms Erdos249257.affineBinaryOrbit_mod_twoPow_eq
#print axioms Erdos249257.balancedPulse_endpoint_fanout
#print axioms Erdos249257.balancedPulse_label_card_lower_bound
#print axioms Erdos249257.balancedPulse_no_autonomous_decoder
#print axioms Erdos249257.balancedPulse_weighted_pair
#print axioms Erdos249257.binaryCoeffTail_nonneg
#print axioms Erdos249257.binaryCoeffTail_supportCoeff_le_two_sqrt_add_four
#print axioms Erdos249257.coprime_base_den_finiteErdosSum
#print axioms Erdos249257.eq_halfGreedyPrefixSupport_of_critical_crossing
#print axioms Erdos249257.finite_period_noncollapse_rat_den
#print axioms Erdos249257.TotientTailPeriodKiller.fixedPrecisionTropicalNoGo
#print axioms Erdos249257.halfTwoChannelCap_lt_mersenneTail
#print axioms Erdos249257.half_lt_upper_competitor_of_eventually_right
#print axioms Erdos249257.half_mem_iff_every_actual_skip_survives
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_cofinalTerminalFalse
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_exists_unboundedSkippedRanksAlong
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_no_existsFatalHalfGap
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_no_lastHalfGreedySkip
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_not_seamGreedyEventuallyRight
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_unboundedTerminalFalse
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_unboundedUpperOrMiddle
#print axioms Erdos249257.half_mem_mersenneAchievementSet_or_exists_fatal_gap
#print axioms Erdos249257.half_ne_coe_finset_add_mersenneTail
#print axioms Erdos249257.HalfCarryReachability.integerHalfCarry_eq_scaled_residual_add_tail
#print axioms Erdos249257.irrational_coeff_series_of_weighted_coeff_block_certificates
#print axioms Erdos249257.irrational_erdosBorweinMersenneConstant
#print axioms Erdos249257.irrational_erdosSum_full_support
#print axioms Erdos249257.irrational_erdosSum_of_lcm_gap
#print axioms Erdos249257.irrational_erdosSupportSeries_eventuallyPeriodic
#print axioms Erdos249257.irrational_erdosSupportSeries_odd
#print axioms Erdos249257.irrational_erdosSupportSeries_of_summable_reciprocal
#print axioms Erdos249257.irrational_erdosSupportSeries_pairwise_coprime
#print axioms Erdos249257.irrational_erdosSupportSeries_periodic
#print axioms Erdos249257.isLastHalfGreedySkip_iff_skip_and_fatal
#print axioms Erdos249257.isStraddlePrefix_step_trichotomy
#print axioms Erdos249257.lcm_lt_den_finiteErdosSum
#print axioms Erdos249257.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms Erdos249257.mersenneTail_eq_weight_add
#print axioms Erdos249257.mersenneTail_le_two_mul_weight
#print axioms Erdos249257.mersenneTail_lt_weight
#print axioms Erdos249257.one_div_twenty_one_mem_iff_not_fatalAlignedBranch
#print axioms Erdos249257.one_div_twenty_one_mem_mersenneAchievementSet_of_cofinalGreedyDecay
#print axioms Erdos249257.positiveMersenneSupportValue_coe_finset_ne_half
#print axioms Erdos249257.prefix_add_mersenneTail_lt_half_of_eventually_right
#print axioms Erdos249257.BooleanMobiusGreedyReduction.remainder_lt_gap_iff_eq_integerGreedyBits
#print axioms Erdos249257.twentyOneCofinalEvenQuotientGreedyDecay_of_closedRows
#print axioms Erdos249257.twentyOneFatalAlignedBranch_eventually_affine_supercapacity
#print axioms Erdos249257.twentyOneFatalAlignedBranch_eventually_strict_supercapacity
#print axioms Erdos249257.two_mul_mersenneWeight_succ_lt
#print axioms Erdos249257.unboundedTerminalFalse_iff_greedyMersenneSkippedSupport_infinite
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.arbitraryWeightMixedSupport_allBase_hereditary
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.divisibilityWeightedClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.finitePrimeWeighted_fixedBase_hereditary
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.mixedSupportClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.strengthenedPositiveCoverClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.weighted_displacement_cofinal_close_return
#print axioms ErdosProblems.Erdos257.perfect_supportedMersenneAchievementSet
#print axioms ErdosProblems.Erdos257.supportedMersenneDigitValue_injective
#print axioms ErdosProblems.Erdos257.volume_supportedMersenneAchievementSet_dichotomy
#print axioms ErdosProblems.Erdos257.volume_supportedMersenneAchievementSet_eq_zero_of_compl_infinite
