import Erdos249257.CarrySurvivorExtinction
import Erdos249257.CertificateKernel
import Erdos249257.DiagonalPincerCertificatesT64
import Erdos249257.GapFareyBound
import Erdos249257.GenericTailOrbitRigidity
import Erdos249257.LcmConeFlatness
import Erdos249257.LcmDiagonalReduction
import Erdos249257.MersenneShadowDenominatorGrowth
import Erdos249257.SignedQMomentObstruction
import Erdos249257.TotientCarryKernelRigidity
import Erdos249257.TotientParityCoboundaryCountermodel
import Erdos249257.TotientTailCarryPeriod
import ErdosProblems.Erdos249.PaperCompleteR20.PeriodicIntegerAffine
import ErdosProblems.Erdos249.PaperCompleteR7.PeriodicAndPulse
import ErdosProblems.Erdos249.PaperCompleteR7.RationalObservableClassification
import ErdosProblems.Erdos249.PaperCompleteR7.ShortNoteAssemblies
import ErdosProblems.Erdos249.PaperCompleteR8.FullKernelAssemblies
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos249.RankOneSharpFloor
import ErdosProblems.Erdos249.RankOneSubrankObstruction
import ErdosProblems.Skip.LadderT67

/-!
# Additive Erdos 249 paper-correspondence audit

This source-current audit adds 22 complete paper environments and
53 declarations omitted from the previously frozen audit root.
-/

#print axioms GapFareyBound.gap_check_window_1_240_first_failure
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.lcmHeight_five_scaledMobiusShadow_den_exact
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.lcmHeight_scaledMobiusShadow_den_exact
#print axioms Erdos249257.SignedQMomentObstruction.mobiusMersenneTheta_two_eq_totient_offset
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.exists_later_arbitrarily_many_separated_parityCoboundaryWeight_carry_pairs
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.exists_totientParity_arbitrarilyManySeparatedCarry_rational_countermodel
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_le_self
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_le_six
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_mod_two_eq_totient
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.tsum_parityCoboundaryWeight_eq_three_halves
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_all_upto_sixteen
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_diagonal_all_imported_through_t64
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_diagonal_t64
#print axioms Erdos249257.TotientTailPeriodKiller.eq_prime_pow_of_not_dvd_periodLcm
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_all_tail_diffs_nonintegral
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_lcm_diagonal_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_of_lcm_cone_nonintegrality_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_of_lcm_diagonal_nonintegrality_supply
#print axioms Erdos249257.TotientTailPeriodKiller.periodLcm_diagonal_kill_iff_tail_diff_notMem_int
#print axioms Erdos249257.binaryCoeffSeries_rational_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.not_irrational_totientSeries_implies_mod_period_and_unbounded_rank
#print axioms Erdos249257.not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#print axioms Erdos249257.temperedBinaryOrbit_eq_scaledTail
#print axioms Erdos249257.tsum_totient_div_pow_two_ne_ratCast_of_den_le_79639646646701375323355774875831053
#print axioms ErdosProblems.Erdos249.PaperCompleteR20.periodic_freezing_integer_affine
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.short_note_residue_theorem
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.bounded_isolated_pulse
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.rankOne_denominator_pos
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_all_base_kernel
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_canonical_and_full_dyadic
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_full_dyadic_basis
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_101_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_121_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_125_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_127_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_128_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_67_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_81_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_97_300
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.abs_mobiusMersenneTheta_sub_prefix_le
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.mobiusMersenneTheta_ge_alpha
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.mobiusMersenneTheta_lt_one
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.positive_direct_sum_sub_theta_two_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.positive_direct_sum_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.primitive_form_abs_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_eq_one_five_iff
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_ge_one_five
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_one_five_sub_theta_two_lt_one_div_fifteen
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOne_denominator_pos
#print axioms ErdosProblems.Skip.LadderT67.exists_diagonalKill_le_82
