-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0

-- Current-source audit of recovered exact paper correspondences.
-- Axiom checks supply kernel evidence; semantic correspondence remains separately reviewed.

import Erdos249257.BooleanMobiusCarry
import Erdos249257.BooleanMobiusCriticalCapacityCofinal
import Erdos249257.BooleanMobiusCriticalCapacityGeometric
import Erdos249257.BooleanMobiusExactRowCrossing
import Erdos249257.BooleanMobiusExactRowDoubling
import Erdos249257.BooleanMobiusExactRowRankTwo
import Erdos249257.BooleanMobiusExactTransition
import Erdos249257.BooleanMobiusGlobalRepair
import Erdos249257.BooleanMobiusGreedyReduction
import Erdos249257.BooleanMobiusLocalRepair
import Erdos249257.BooleanMobiusSkipRow
import Erdos249257.BooleanMobiusSkippedCoreCriticalCapacity
import Erdos249257.CarrySurvivorExtinction
import Erdos249257.CertificateKernel
import Erdos249257.GapFareyBound
import Erdos249257.GcdMomentCalculus
import Erdos249257.GenericTailOrbitRigidity
import Erdos249257.GeometricCoprimality
import Erdos249257.HalfCylinderFinalMiddleCellEscape
import Erdos249257.HalfCylinderFiniteShadow
import Erdos249257.HalfCylinderFullShellSeamBridge
import Erdos249257.HalfCylinderSkippedEndpointClassifier
import Erdos249257.HalfDivisorUnitDrop
import Erdos249257.HalfGapMass
import Erdos249257.HalfGreedyFatalGap
import Erdos249257.HalfTrappingReturnCarry
import Erdos249257.LcmConeFlatness
import Erdos249257.MaximalOmegaLayer
import Erdos249257.MersenneLambertLadder
import Erdos249257.PivotAntiReconstruction
import Erdos249257.RationalSupportCarrySkeleton
import Erdos249257.SublogDivisorCoverage
import Erdos249257.TotientActualLcmOrbitSign
import Erdos249257.TotientTailCarryPeriod
import Erdos249257.TotientTailPeriodKiller
import ErdosProblems.Erdos249.PaperCompleteR7.ArithmeticAssemblies
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos269.PaperCompleteR20.BoundedLatticeCollision
import ErdosProblems.Erdos269.PaperCompleteR20.EightScaleRigidity
import ErdosProblems.Erdos269.PaperCompleteR20.LiteralTriangleReal
import ErdosProblems.Erdos269.PaperCompleteR20.OcticEscapeWhole
import ErdosProblems.Erdos269.PaperCompleteR20.RealBoundDenominatorReduction
import ErdosProblems.Erdos269.PaperCompleteR20.RealCutoffs
import ErdosProblems.Erdos269.PaperCompleteR20.RealTwoPrimeKernel
import ErdosProblems.Erdos269.PaperR7BasicAssembly

import ErdosProblems.Erdos251.PaperCompleteR20.SignedWindow
import ErdosProblems.Erdos251.PaperCompleteR20.RealPropagation
import ErdosProblems.Erdos243.PaperCompleteR20.RealCutoffCriterion
import ErdosProblems.Erdos1041.PaperCompleteR20.TwoNearestPolynomial

#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneHalfTarget_lower_word_eq_greedy_and_remainder_eq
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeightsFrom_gapDominates
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeights_gapDominates_even
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeights_gapDominates_odd
#print axioms Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcmTailDiff_shift_pos
#print axioms Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_integral_forces_topEdgeResidue
#print axioms Erdos249257.HalfCylinderFiniteShadow.supportCoeff_insert_divisor
#print axioms Erdos249257.HalfDivisorUnitDrop.supportCoeff_boundaryPair_unitDrop_at_double
#print axioms Erdos249257.HalfDivisorUnitDrop.supportCoeff_extend_true_eq_false_add_one_at_double
#print axioms Erdos249257.HalfGreedyFatalGap.three_le_of_fatal_of_odd
#print axioms Erdos249257.HalfGreedyFatalGap.two_le_of_fatal
#print axioms Erdos249257.HalfGreedyFatalGap.unitNumerator_skipSafe
#print axioms Erdos249257.HalfGreedyFatalGap.unitNumerator_skipSafe_actualTail
#print axioms Erdos249257.HalfGreedySkippedCriticalQuotientSupply
#print axioms Erdos249257.HalfTrappingReturnCarry.ReverseCarryWord
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingMidpointReturns_twoPow_le_realBound
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingReverseCarryWords_carryDifference_eq_twoPow_mul_odd
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingReverseCarryWords_twoPow_le_realBound
#print axioms Erdos249257.IsTemperedBinaryOrbit
#print axioms Erdos249257.MaximalOmegaLayer.mixedPrimePowerLayerTwo_supportCoeffInt
#print axioms Erdos249257.MaximalOmegaLayer.mixedPrimePowerLayerTwo_twelve_fixture
#print axioms Erdos249257.MaximalOmegaLayer.primePowerLayer_comm
#print axioms Erdos249257.TotientTailPeriodKiller.carryOrbit_eq_tail_diff
#print axioms Erdos249257.TotientTailPeriodKiller.dtwWindowSeparatedPairs_iff_irrational_totient_series
#print axioms Erdos249257.TotientTailPeriodKiller.exists_certifiedKill_iff_tail_diff_notMem_int
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_lcm_diagonal_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.tail_diff_int_of_den_dvd
#print axioms Erdos249257.TotientTailPeriodKiller.two_pow_mul_totient_series_eq
#print axioms Erdos249257.abs_localMersennePrefixValue_sub_half_le
#print axioms Erdos249257.binaryCoeffSeries
#print axioms Erdos249257.binaryCoeffTail_div_pow_tendsto_zero
#print axioms Erdos249257.binaryCoeffTail_le
#print axioms Erdos249257.card_divisors_le_divisorSubpowerConst_mul_rpow
#print axioms Erdos249257.card_divisors_pow_le_divisorSubpowerConst_pow_mul
#print axioms Erdos249257.divisorSubpowerConst
#print axioms Erdos249257.dyadic_support_fraction_reciprocalMass_diverges_or_gt_one
#print axioms Erdos249257.erdosSupportSeries_rational_iff_exists_temperedCarry
#print axioms Erdos249257.erdosSupportSeries_two_eq_binaryCoeffSeries
#print axioms Erdos249257.exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCoreSharpCapacity
#print axioms Erdos249257.exists_boolean_word_of_lt_two_pow
#print axioms Erdos249257.exists_exactRowStrictUpperExtension_two_mul_sub_one_of_exact_below
#print axioms Erdos249257.exists_exactRowStrictUpperFill_of_skippedCoreSharpCapacity
#print axioms Erdos249257.exists_first_localMersenne_crossing
#print axioms Erdos249257.exists_unbounded_shifted_odd_tail_nat_state_of_support_fraction
#print axioms Erdos249257.finalMiddleCell_neg_three_not_last
#print axioms Erdos249257.halfGreedySkippedCriticalQuotientSupply_of_precriticalSuffix
#print axioms Erdos249257.halfGreedySkippedPrecriticalSuffixSupply_iff_preTake
#print axioms Erdos249257.halfGreedy_precriticalSuffix_lt_of_future_skip_after_takenBlock
#print axioms Erdos249257.halfGreedy_precriticalSuffix_lt_of_next_skip
#print axioms Erdos249257.halfGreedy_skipped_endpoint_trichotomy
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skippedFullShellNonnegative
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skippedSeamEscape
#print axioms Erdos249257.irrational_totientSeries_iff_cofinalDirectedLcmCertificateSupply
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_one_lt_upperWindow_of_exact_below
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometric
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometricCore
#print axioms Erdos249257.localMersenneCrossingRanks
#print axioms Erdos249257.localMersenneGeometricQuotient
#print axioms Erdos249257.localMersenneQuotient_eq_geometric
#print axioms Erdos249257.localMersenneQuotient_eq_two_pow_sub_of_half_lt
#print axioms Erdos249257.localPrefixQuotient_succ
#print axioms Erdos249257.mersenneGap_le
#print axioms Erdos249257.mersenneGap_tail_le
#print axioms Erdos249257.mobiusCenteredHalfCarry_add_two
#print axioms Erdos249257.mobius_supportCoeff_boolean
#print axioms Erdos249257.mobius_supportCoeff_eq_one_iff
#print axioms Erdos249257.moebius_mul_supportCoeffAF
#print axioms Erdos249257.not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.one_add_mul_card_le_two_mul_shifted_state
#print axioms Erdos249257.one_lt_reciprocalMass_of_dyadic_support_fraction_of_two_pos_mem
#print axioms Erdos249257.precriticalCrossingTax_of_futureThreshold
#print axioms Erdos249257.shifted_state_unbounded_of_infinite_support
#print axioms Erdos249257.skippedCoreCriticalQuotientSupply_iff_halfGreedySkipped
#print axioms Erdos249257.skippedSeamAlignmentZero_iff_skippedFullShellNonnegative
#print axioms Erdos249257.sub_two_le_two_pow_sub_four
#print axioms Erdos249257.summable_mersenneGap_shift
#print axioms Erdos249257.supportCoeff_le_card_divisors
#print axioms Erdos249257.supportCoeff_le_self
#print axioms Erdos249257.tendsto_mersenneGap_tail_zero
#print axioms Erdos249257.totient_carry_residue_window_1_240_eq
#print axioms Erdos249257.totient_series_eq_half_add_moebius_mersenne_square
#print axioms Erdos249257.totient_series_eq_half_add_visible_coprime_pairs
#print axioms Erdos249257.tsum_moebius_div_two_pow_sub_one_sq_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms Erdos249257.tsum_visible_coprime_pairs_eq_totient_series
#print axioms Erdos249257.tsum_visible_coprime_pairs_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms Erdos249257.two_mem_of_exact_localMersenneQuotient
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.irrational_totient_iff_moebius_square
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.periodMultipleKillSupply_iff_irrational
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.conditional_denominator_reduction_real_bound
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.literal_triangle_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.long_all_scale_lattice_exact
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.octic_escape_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.paper_pinning_and_eight_scale_rigidity
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_eq_of_sameLogCell
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_first
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_second
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_third
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realSmoothExponentShell_bounds
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.real_two_prime_separation
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.running_lcm_real_cutoff_exact
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.threePrimeKernelQ_eq_of_sameRealLogCell
#print axioms ErdosProblems.Erdos269.PaperR7.paper_jump_count
#print axioms GapFareyBound.gap_check_window_1_240_first_failure
#print axioms GapFareyBound.gap_check_window_1_240_le_79639646646701375323355774875831053
#print axioms GcdMomentCalculus.tsum_lambert_linear_weight_sq_pure
#print axioms GcdMomentCalculus.tsum_pos_pair_both_dvd_half_eq_inv_mersenne_sq
#print axioms GeometricCoprimality.tsum_gcd_layer_pos_coprime_half_eq_one
#print axioms MersenneLambertLadder.tsum_moebius_lambert_sq
#print axioms Erdos249257.irrational_totient_series_of_lcm_cone_window_kill_supply
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.signed_two_window_iff
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.signed_two_window_consequences
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.realTailShift_integral_add
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.real_lowerDensityZero_iff_exists_admissible_real_weight
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.two_nearest_roots_of_polynomial_critical
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.exists_two_nearest_roots_of_polynomial_critical
