-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0

-- Combined current-source replay of exact paper correspondences.
-- Semantic review and independent comparison remain separate obligations.

import Erdos249257.AdelicHeightObstruction
import Erdos249257.AllBaseReciprocalSupportIrrationality
import Erdos249257.BooleanMobiusCarry
import Erdos249257.BooleanMobiusCofinalExactRows
import Erdos249257.BooleanMobiusCriticalCapacityCofinal
import Erdos249257.BooleanMobiusCriticalCapacityGeometric
import Erdos249257.BooleanMobiusExactRowCrossing
import Erdos249257.BooleanMobiusExactRowDoubling
import Erdos249257.BooleanMobiusExactRowRankTwo
import Erdos249257.BooleanMobiusExactTransition
import Erdos249257.BooleanMobiusGlobalRepair
import Erdos249257.BooleanMobiusGreedyReduction
import Erdos249257.BooleanMobiusLocalRepair
import Erdos249257.BooleanMobiusSkipRow
import Erdos249257.BooleanMobiusSkipRowCofinal
import Erdos249257.BooleanMobiusSkippedCoreCriticalCapacity
import Erdos249257.CarrySurvivorExtinction
import Erdos249257.CertificateKernel
import Erdos249257.CofinalStripReturn
import Erdos249257.DiagonalPincerCertificatesT64
import Erdos249257.DyadicPrefixCompression
import Erdos249257.GapFareyBound
import Erdos249257.GcdMomentCalculus
import Erdos249257.GenericTailOrbitRigidity
import Erdos249257.GeometricCoprimality
import Erdos249257.GreedyAchievementSet
import Erdos249257.HalfCarryReachability
import Erdos249257.HalfCutLocator
import Erdos249257.HalfCylinderFatalGapRightTail
import Erdos249257.HalfCylinderFinalMiddleCellEscape
import Erdos249257.HalfCylinderFiniteShadow
import Erdos249257.HalfCylinderFixedTailSocket
import Erdos249257.HalfCylinderFullShellSeamBridge
import Erdos249257.HalfCylinderHalfMembershipClassification
import Erdos249257.HalfCylinderIntegerGreedy
import Erdos249257.HalfCylinderLargestSkipInduction
import Erdos249257.HalfCylinderMiddleCarryLowerBound
import Erdos249257.HalfCylinderProducerLowerBound
import Erdos249257.HalfCylinderSkippedEndpointClassifier
import Erdos249257.HalfCylinderUpperResetBandCertificates
import Erdos249257.HalfDivisorUnitDrop
import Erdos249257.HalfGapMass
import Erdos249257.HalfGreedyFatalGap
import Erdos249257.HalfTrappingReturnCarry
import Erdos249257.HalfUpperResetCriticalBand
import Erdos249257.LcmConeFlatness
import Erdos249257.LcmDiagonalReduction
import Erdos249257.MaximalOmegaLayer
import Erdos249257.MersenneLambertLadder
import Erdos249257.MersenneShadowDenominatorGrowth
import Erdos249257.MobiusSignSupportNoGo
import Erdos249257.PivotAntiReconstruction
import Erdos249257.RationalDenominatorSurvival
import Erdos249257.RationalSupportCarrySkeleton
import Erdos249257.SignedQMomentObstruction
import Erdos249257.SublogDivisorCoverage
import Erdos249257.SuffixCylinderTerminalOnlyBridge
import Erdos249257.TotientActualLcmOrbitSign
import Erdos249257.TotientCarryKernelRigidity
import Erdos249257.TotientMahlerDefect
import Erdos249257.TotientParityCoboundaryCountermodel
import Erdos249257.TotientTailCarryPeriod
import Erdos249257.TotientTailPeriodKiller
import Erdos249257.TropicalCurvatureCarry
import Erdos249257.TwentyOneQuotientGreedy
import ErdosProblems.Erdos1041.Counterexample.CatalogueAdapter
import ErdosProblems.Erdos1041.CriticalTwoRootProximity
import ErdosProblems.Erdos1041.CubicQuotientFiberCase
import ErdosProblems.Erdos1041.NewtonFlowRaySeparation
import ErdosProblems.Erdos1041.PaperCompleteR20.CriticalMeanWhole
import ErdosProblems.Erdos1041.PaperCompleteR20.NewtonRealTime
import ErdosProblems.Erdos1041.PaperCompleteR20.SexticSpokeWhole
import ErdosProblems.Erdos1041.PaperCompleteR20.TwoNearestPolynomial
import ErdosProblems.Erdos1041.PaperCriticalValueMeanR10
import ErdosProblems.Erdos1041.PaperCubicCompletion
import ErdosProblems.Erdos1041.PaperCubicFibres
import ErdosProblems.Erdos1041.PaperPrimitiveCompletionR10
import ErdosProblems.Erdos1041.PaperReflectedCompletion
import ErdosProblems.Erdos1041.PaperSeparationCounterexample
import ErdosProblems.Erdos1041.PaperStraightObstructions
import ErdosProblems.Erdos1041.PaperTrinomial
import ErdosProblems.Erdos1041.PaperTrinomialWholeR21
import ErdosProblems.Erdos1041.PaperWeightedRefinementsR10
import ErdosProblems.Erdos1041.PrimitiveQuinticInteriorTail
import ErdosProblems.Erdos1041.SharpCollinearChebyshev
import ErdosProblems.Erdos1049.AdelicHeightBridge
import ErdosProblems.Erdos1049.AllRow.Producer
import ErdosProblems.Erdos1049.PaperFiniteAssembliesR7
import ErdosProblems.Erdos1049.PaperLongCapR9
import ErdosProblems.Erdos1049.PaperNoDecayR9
import ErdosProblems.Erdos1049.PaperOmegaIndicatorR7
import ErdosProblems.Erdos1049.PaperR17.SourceConsumers
import ErdosProblems.Erdos1049.PaperShortCapR9
import ErdosProblems.Erdos1049.QuantitativeSelectorEscape
import ErdosProblems.Erdos1049.RationalBaseLambert
import ErdosProblems.Erdos1049.ZudilinConeArithmetic
import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos243.FiniteHorizonResidue
import ErdosProblems.Erdos243.PaperCompleteR11.ArithmeticWeightedRecord
import ErdosProblems.Erdos243.PaperCompleteR11.CanonicalRecords
import ErdosProblems.Erdos243.PaperCompleteR11.DensityTransport
import ErdosProblems.Erdos243.PaperCompleteR11.InclusiveLimsup
import ErdosProblems.Erdos243.PaperCompleteR11.QuantitativeRecordDichotomy
import ErdosProblems.Erdos243.PaperCompleteR20.InclusiveOne
import ErdosProblems.Erdos243.PaperCompleteR20.PowerPersistence
import ErdosProblems.Erdos243.PaperCompleteR20.RealCutoffCriterion
import ErdosProblems.Erdos243.PaperCompleteR7.Arithmetic
import ErdosProblems.Erdos243.PaperCompleteR7.Frontier
import ErdosProblems.Erdos243.PaperCompleteR7.LcmDefect
import ErdosProblems.Erdos243.PaperCompleteR7.Limits
import ErdosProblems.Erdos243.PaperCompleteR7.ProductDefect
import ErdosProblems.Erdos243.PaperCompleteR7.QuantitativeTail
import ErdosProblems.Erdos243.PaperCompleteR7.Reduction
import ErdosProblems.Erdos243.ReciprocalTailRigidity
import ErdosProblems.Erdos249.PaperCompleteR20.PeriodicIntegerAffine
import ErdosProblems.Erdos249.PaperCompleteR20.SpecifiedTailPeriod
import ErdosProblems.Erdos249.PaperCompleteR7.ArithmeticAssemblies
import ErdosProblems.Erdos249.PaperCompleteR7.PeriodicAndPulse
import ErdosProblems.Erdos249.PaperCompleteR7.RationalObservableClassification
import ErdosProblems.Erdos249.PaperCompleteR7.ShortNoteAssemblies
import ErdosProblems.Erdos249.PaperCompleteR8.FullKernelAssemblies
import ErdosProblems.Erdos249.PaperCompleteR8.KernelRelationBasis
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos249.RankOneSharpFloor
import ErdosProblems.Erdos249.RankOneSubrankObstruction
import ErdosProblems.Erdos251.LogarithmicCarryAsymptoticsR8
import ErdosProblems.Erdos251.OrderLatticeDiagonal
import ErdosProblems.Erdos251.PaperBoundedCarryR7
import ErdosProblems.Erdos251.PaperCompleteR20.RealPropagation
import ErdosProblems.Erdos251.PaperCompleteR20.SignedWindow
import ErdosProblems.Erdos251.PaperCompleteR20.TrueTail
import ErdosProblems.Erdos251.PaperCoreR7
import ErdosProblems.Erdos251.PaperFiniteCertificatesR7
import ErdosProblems.Erdos251.PaperNonconcentrationR7
import ErdosProblems.Erdos251.PaperTailBoundsR7
import ErdosProblems.Erdos251.PrimeGapDyadicTail
import ErdosProblems.Erdos251.RealPrimeGapTail
import ErdosProblems.Erdos251.ShiftedGapCountingR9
import ErdosProblems.Erdos251.SparseAmbientR9
import ErdosProblems.Erdos251.SparsePaperR11
import ErdosProblems.Erdos257.MersenneSubseriesRigidity
import ErdosProblems.Erdos257.PaperCompleteR8.ArbitraryWeightMixedClaim
import ErdosProblems.Erdos257.PaperCompleteR8.PositiveCoverReturn
import ErdosProblems.Erdos257.PaperCompleteR8.WeightedHereditaryClaim
import ErdosProblems.Erdos257.PaperCompleteR8.WeightedReturn
import ErdosProblems.Erdos269.ActualSharpTailMajorantR10
import ErdosProblems.Erdos269.LongWindowCapR11
import ErdosProblems.Erdos269.PaperCompleteR20.BoundedLatticeCollision
import ErdosProblems.Erdos269.PaperCompleteR20.DyadicAlphabetWhole
import ErdosProblems.Erdos269.PaperCompleteR20.EightScaleRigidity
import ErdosProblems.Erdos269.PaperCompleteR20.FixedBaseRecoding
import ErdosProblems.Erdos269.PaperCompleteR20.LiteralTriangleReal
import ErdosProblems.Erdos269.PaperCompleteR20.OcticEscapeWhole
import ErdosProblems.Erdos269.PaperCompleteR20.PhaseStripDecomposition
import ErdosProblems.Erdos269.PaperCompleteR20.RealBaseShortInterval
import ErdosProblems.Erdos269.PaperCompleteR20.RealBoundDenominatorReduction
import ErdosProblems.Erdos269.PaperCompleteR20.RealCutoffs
import ErdosProblems.Erdos269.PaperCompleteR20.RealTwoPrimeKernel
import ErdosProblems.Erdos269.PaperCompleteR20.WeightedShiftValue
import ErdosProblems.Erdos269.PaperExactDenominatorR13
import ErdosProblems.Erdos269.PaperFixedStartResidueR14
import ErdosProblems.Erdos269.PaperR7ActualOrbit
import ErdosProblems.Erdos269.PaperR7BasicAssembly
import ErdosProblems.Erdos269.PaperR7FiniteCutRank
import ErdosProblems.Erdos269.PaperR7ModularMinors
import ErdosProblems.Erdos269.PaperR7RationalBridge
import ErdosProblems.Erdos269.PaperR7SeriesIdentification
import ErdosProblems.Erdos269.PaperR7WindowResults
import ErdosProblems.Erdos269.PaperR8RankMajorant
import ErdosProblems.Erdos269.PaperR8UniformRank
import ErdosProblems.Erdos269.ResidueEscape
import ErdosProblems.Erdos269.RestrictedFloorSum
import ErdosProblems.Erdos269.ThreePrimeRunningLcm
import ErdosProblems.Erdos68.ChannelIntegralCongruence
import ErdosProblems.Erdos68.PaperCompleteDivisorCoordinates
import ErdosProblems.Erdos68.PaperCompleteExisting
import ErdosProblems.Erdos68.PaperCompleteLiminf
import ErdosProblems.Erdos68.PaperCompleteMomentHorizon
import ErdosProblems.Erdos68.PaperCompleteMomentIdeal
import ErdosProblems.Erdos68.PaperCompletePrimePole
import ErdosProblems.Erdos68.PaperCompleteResidualIdentity
import ErdosProblems.Erdos68.PaperCompleteSupportedBands
import ErdosProblems.Skip.LadderT67

#print axioms Erdos1041.Counterexample.erdos1041_ani_degree_seven
#print axioms Erdos249257.AdelicHeightObstruction.linearDescender_eq_smul_eval
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneHalfTarget_lower_word_eq_greedy_and_remainder_eq
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeightsFrom_gapDominates
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeights_gapDominates_even
#print axioms Erdos249257.BooleanMobiusGreedyReduction.localMersenneWeights_gapDominates_odd
#print axioms Erdos249257.BooleanMobiusGreedyReduction.remainder_lt_gap_iff_eq_integerGreedyBits
#print axioms Erdos249257.CofinalExactLocalMersenneHalfRows
#print axioms Erdos249257.CofinalPositiveHalfGreedySkips
#print axioms Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcmTailDiff_shift_pos
#print axioms Erdos249257.DiagonalFreshLossBridge.PowerTwoOddWindowAffine.actualLcm_integral_forces_topEdgeResidue
#print axioms Erdos249257.HalfCarryReachability.GreedyHalfCarryCofinalStripReturn
#print axioms Erdos249257.HalfCarryReachability.finite_boolSupport_ne_half
#print axioms Erdos249257.HalfCarryReachability.greedy_half_infinite_of_cofinalStripReturn
#print axioms Erdos249257.HalfCarryReachability.greedy_half_infinite_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms Erdos249257.HalfCarryReachability.greedy_half_infinite_of_mobiusCenteredHalfCarry_upperBound
#print axioms Erdos249257.HalfCarryReachability.greedy_mobiusCenteredHalfCarry_nonneg
#print axioms Erdos249257.HalfCarryReachability.infinite_support_half_of_mobiusCenteredHalfCarry_sqrtBound
#print axioms Erdos249257.HalfCarryReachability.integerHalfCarry_eq_scaled_residual_add_tail
#print axioms Erdos249257.HalfCylinderFiniteShadow.supportCoeff_insert_divisor
#print axioms Erdos249257.HalfCylinderIntegerGreedy.PerturbedFamily.AdjacentCut.nextRemainder_trichotomy
#print axioms Erdos249257.HalfCylinderIntegerGreedy.PerturbedFamily.AdjacentCut.prefixChoice_maximal
#print axioms Erdos249257.HalfCylinderIntegerGreedy.supportCoeff_insert_eq_add_indicator
#print axioms Erdos249257.HalfDivisorUnitDrop.supportCoeff_boundaryPair_unitDrop_at_double
#print axioms Erdos249257.HalfDivisorUnitDrop.supportCoeff_extend_true_eq_false_add_one_at_double
#print axioms Erdos249257.HalfGreedyFatalGap.three_le_of_fatal_of_odd
#print axioms Erdos249257.HalfGreedyFatalGap.two_le_of_fatal
#print axioms Erdos249257.HalfGreedyFatalGap.unitNumerator_skipSafe
#print axioms Erdos249257.HalfGreedyFatalGap.unitNumerator_skipSafe_actualTail
#print axioms Erdos249257.HalfGreedySkippedCriticalQuotientSupply
#print axioms Erdos249257.HalfGreedySkippedFullShellNonnegative
#print axioms Erdos249257.HalfGreedySkippedSeamAlignmentZero
#print axioms Erdos249257.HalfTrappingReturnCarry.ReverseCarryWord
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingMidpointReturns_twoPow_le_realBound
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingReverseCarryWords_carryDifference_eq_twoPow_mul_odd
#print axioms Erdos249257.HalfTrappingReturnCarry.overlappingReverseCarryWords_twoPow_le_realBound
#print axioms Erdos249257.HalfTrappingReturnCarry.relationInvariantLinearChannels_det_eq_zero
#print axioms Erdos249257.HalfUpperResetCriticalBand.dyadicBandEscape_iff_exists_critical
#print axioms Erdos249257.HalfUpperResetCriticalBand.exists_criticalDyadicBandIndex
#print axioms Erdos249257.HalfUpperResetCriticalBand.seamUpperResetCharge_le
#print axioms Erdos249257.HalfUpperResetCriticalBand.seamUpperResetCriticalBandEscape_iff
#print axioms Erdos249257.IsStraddlePrefix.half_agrees_greedy
#print axioms Erdos249257.IsStraddlePrefix.half_step_forced
#print axioms Erdos249257.IsTemperedBinaryOrbit
#print axioms Erdos249257.MaximalOmegaLayer.mixedPrimePowerLayerTwo_supportCoeffInt
#print axioms Erdos249257.MaximalOmegaLayer.mixedPrimePowerLayerTwo_twelve_fixture
#print axioms Erdos249257.MaximalOmegaLayer.primePowerLayer_comm
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.lcmHeight_five_scaledMobiusShadow_den_exact
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.lcmHeight_scaledMobiusShadow_den_exact
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.lcmHeight_scaledMobiusShadow_den_lower_bound
#print axioms Erdos249257.MersenneShadowDenominatorGrowth.upperHalfMersenneProduct_lower_bound
#print axioms Erdos249257.MobiusSignSupportNoGo.half_lt_tsum_negativeMobius
#print axioms Erdos249257.MobiusSignSupportNoGo.tsum_negativeMobius_eq_half_add_positiveMobiusTail
#print axioms Erdos249257.ProtectedExactLocalMersenneRow
#print axioms Erdos249257.RationalDenominatorSurvival.divisor_dvd_divInt_den
#print axioms Erdos249257.RationalDenominatorSurvival.survivingDivisor_dvd_scaled_divInt_den
#print axioms Erdos249257.SeamTwoSidedDyadicCellEscape.twoSided
#print axioms Erdos249257.SignedQMomentObstruction.mobiusMersenneTheta_two_eq_totient_offset
#print axioms Erdos249257.SkippedCoreCriticalQuotientSupply
#print axioms Erdos249257.SuffixCylinderTerminalOnlyBridge.exists_infinite_positive_support_half_of_cofinalCylinderStages
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.exists_later_arbitrarily_many_separated_parityCoboundaryWeight_carry_pairs
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.exists_totientParity_arbitrarilyManySeparatedCarry_rational_countermodel
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_le_self
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_le_six
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.parityCoboundaryWeight_mod_two_eq_totient
#print axioms Erdos249257.TotientParityCoboundaryCountermodel.tsum_parityCoboundaryWeight_eq_three_halves
#print axioms Erdos249257.TotientTailPeriodKiller.carryOrbit_eq_tail_diff
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_all_upto_sixteen
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_diagonal_all_imported_through_t64
#print axioms Erdos249257.TotientTailPeriodKiller.certifiedKill_diagonal_t64
#print axioms Erdos249257.TotientTailPeriodKiller.dtwWindowSeparatedPairs_iff_irrational_totient_series
#print axioms Erdos249257.TotientTailPeriodKiller.eq_prime_pow_of_not_dvd_periodLcm
#print axioms Erdos249257.TotientTailPeriodKiller.exists_certifiedKill_iff_tail_diff_notMem_int
#print axioms Erdos249257.TotientTailPeriodKiller.fixedPrecisionTropicalNoGo
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_all_tail_diffs_nonintegral
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_iff_lcm_diagonal_certificate_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_of_lcm_cone_nonintegrality_supply
#print axioms Erdos249257.TotientTailPeriodKiller.irrational_totient_series_of_lcm_diagonal_nonintegrality_supply
#print axioms Erdos249257.TotientTailPeriodKiller.periodLcm_diagonal_kill_iff_tail_diff_notMem_int
#print axioms Erdos249257.TotientTailPeriodKiller.tail_diff_int_of_den_dvd
#print axioms Erdos249257.TotientTailPeriodKiller.two_pow_mul_totient_series_eq
#print axioms Erdos249257.abs_exactLocalMersenneRowValue_sub_half_le
#print axioms Erdos249257.abs_localMersennePrefixValue_sub_half_le
#print axioms Erdos249257.affineBinaryOrbit_mod_twoPow_eq
#print axioms Erdos249257.balancedPulse_endpoint_fanout
#print axioms Erdos249257.balancedPulse_label_card_lower_bound
#print axioms Erdos249257.balancedPulse_no_autonomous_decoder
#print axioms Erdos249257.balancedPulse_weighted_pair
#print axioms Erdos249257.binaryCoeffSeries
#print axioms Erdos249257.binaryCoeffSeries_rational_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.binaryCoeffTail_div_pow_tendsto_zero
#print axioms Erdos249257.binaryCoeffTail_le
#print axioms Erdos249257.binaryCoeffTail_nonneg
#print axioms Erdos249257.binaryCoeffTail_supportCoeff_coe_finset_le_card
#print axioms Erdos249257.binaryCoeffTail_supportCoeff_le_two_sqrt_add_four
#print axioms Erdos249257.card_divisors_le_divisorSubpowerConst_mul_rpow
#print axioms Erdos249257.card_divisors_pow_le_divisorSubpowerConst_pow_mul
#print axioms Erdos249257.cofinalExactLocalMersenneHalfRows_of_criticalQuotientSupply
#print axioms Erdos249257.cofinalExactLocalMersenneHalfRows_of_positiveHalfGreedySkips
#print axioms Erdos249257.cofinalPositiveHalfGreedySkips_iff_half_mem
#print axioms Erdos249257.coprime_base_den_finiteErdosSum
#print axioms Erdos249257.divInt_le_nextDyadic_iff_excess_nonpos
#print axioms Erdos249257.divisorSubpowerConst
#print axioms Erdos249257.dyadicResidual_denominator_sandwich
#print axioms Erdos249257.dyadic_support_fraction_reciprocalMass_diverges_or_gt_one
#print axioms Erdos249257.eq_halfGreedyPrefixSupport_of_critical_crossing
#print axioms Erdos249257.erdosSupportSeries_multiples_eq_pow_base_full_support
#print axioms Erdos249257.erdosSupportSeries_rational_iff_exists_temperedCarry
#print axioms Erdos249257.erdosSupportSeries_two_eq_binaryCoeffSeries
#print axioms Erdos249257.exactLocalMersenneHalfRow_of_positiveHalfGreedySkip
#print axioms Erdos249257.exactLocalMersenneHalfRow_two_mul_sub_two_of_skippedCoreSharpCapacity
#print axioms Erdos249257.exists_boolean_word_of_lt_two_pow
#print axioms Erdos249257.exists_exactRowStrictUpperExtension_two_mul_sub_one_of_exact_below
#print axioms Erdos249257.exists_exactRowStrictUpperFill_of_skippedCoreSharpCapacity
#print axioms Erdos249257.exists_first_localMersenne_crossing
#print axioms Erdos249257.exists_laterProtectedExactLocalMersenneRow
#print axioms Erdos249257.exists_unbounded_shifted_odd_tail_nat_state_of_support_fraction
#print axioms Erdos249257.finalMiddleCell_neg_three_not_last
#print axioms Erdos249257.finite_period_noncollapse_rat_den
#print axioms Erdos249257.greedyHalfFrozenMargin_fullShell_eq_neg_seamRemainder_of_alignment
#print axioms Erdos249257.greedyHalf_mem_nextMersenneDyadicSliver_iff_excess
#print axioms Erdos249257.greedy_survives_of_mem_mersenneAchievementSet
#print axioms Erdos249257.halfGreedySkippedCriticalQuotientSupply_of_precriticalSuffix
#print axioms Erdos249257.halfGreedySkippedPrecriticalSuffixSupply_iff_preTake
#print axioms Erdos249257.halfGreedy_precriticalSuffix_lt_iff_futureSkipCoverage
#print axioms Erdos249257.halfGreedy_precriticalSuffix_lt_of_future_skip_after_takenBlock
#print axioms Erdos249257.halfGreedy_precriticalSuffix_lt_of_next_skip
#print axioms Erdos249257.halfGreedy_skipped_endpoint_trichotomy
#print axioms Erdos249257.halfTwoChannelCap_lt_mersenneTail
#print axioms Erdos249257.half_lt_upper_competitor_of_eventually_right
#print axioms Erdos249257.half_mem_iff_every_actual_skip_survives
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_cofinalTerminalFalse
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_exists_unboundedSkippedRanksAlong
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_greedySkippedSupport_infinite
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_no_existsFatalHalfGap
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_no_lastHalfGreedySkip
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_not_seamGreedyEventuallyRight
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_unboundedTerminalFalse
#print axioms Erdos249257.half_mem_mersenneAchievementSet_iff_unboundedUpperOrMiddle
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_cofinalExactLocalRows
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_criticalQuotientSupply
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_largestSkipLateStepSocket
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_middleProducerCardEscape
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_middleProducerRowEscape
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_positiveHalfGreedySkips
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_secondChannelSeparation
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_secondChannelSeparationRat_from_seven
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skippedFullShellNonnegative
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skippedSeamEscape
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skipped_dyadicCap
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_skipped_twoChannelCap
#print axioms Erdos249257.half_mem_mersenneAchievementSet_of_upperResetDyadicBandEscape
#print axioms Erdos249257.half_mem_mersenneAchievementSet_or_exists_fatal_gap
#print axioms Erdos249257.half_ne_coe_finset_add_mersenneTail
#print axioms Erdos249257.irrational_coeff_series_of_weighted_coeff_block_certificates
#print axioms Erdos249257.irrational_erdosBorweinMersenneConstant
#print axioms Erdos249257.irrational_erdosSum_factorial_support
#print axioms Erdos249257.irrational_erdosSum_full_support
#print axioms Erdos249257.irrational_erdosSum_of_lcm_gap
#print axioms Erdos249257.irrational_erdosSum_two_pow_support
#print axioms Erdos249257.irrational_erdosSupportSeries_eventuallyPeriodic
#print axioms Erdos249257.irrational_erdosSupportSeries_multiples
#print axioms Erdos249257.irrational_erdosSupportSeries_odd
#print axioms Erdos249257.irrational_erdosSupportSeries_of_summable_reciprocal
#print axioms Erdos249257.irrational_erdosSupportSeries_of_tail
#print axioms Erdos249257.irrational_erdosSupportSeries_pairwise_coprime
#print axioms Erdos249257.irrational_erdosSupportSeries_periodic
#print axioms Erdos249257.irrational_erdosSupportSeries_residueClass
#print axioms Erdos249257.irrational_erdosSupportSeries_tail_of_irrational
#print axioms Erdos249257.irrational_intWeightedErdosSeries_periodic_of_coeff_nonneg_of_frequently_ne_zero
#print axioms Erdos249257.irrational_intWeightedErdosSeries_periodic_of_coeff_nonpos_of_frequently_ne_zero
#print axioms Erdos249257.irrational_of_den_mul_abs_sub_tendsto_zero
#print axioms Erdos249257.irrational_or_bpow_mul_eq_intCast_intWeightedErdosSeries_periodic
#print axioms Erdos249257.irrational_totientSeries_iff_cofinalDirectedLcmCertificateSupply
#print axioms Erdos249257.irrational_totient_series_of_lcm_cone_window_kill_supply
#print axioms Erdos249257.isLastHalfGreedySkip_iff_skip_and_fatal
#print axioms Erdos249257.isStraddlePrefix_step_trichotomy
#print axioms Erdos249257.largestSkipLateAt_fourteen
#print axioms Erdos249257.lcm_lt_den_finiteErdosSum
#print axioms Erdos249257.linearIndependent_of_separatedMinorCertificate
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_one_lt_upperWindow_of_exact_below
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometric
#print axioms Erdos249257.localBinarySuffix_two_mul_sub_two_lt_criticalCapacity_iff_geometricCore
#print axioms Erdos249257.localMersenneCrossingRanks
#print axioms Erdos249257.localMersenneGeometricQuotient
#print axioms Erdos249257.localMersenneQuotient_eq_geometric
#print axioms Erdos249257.localMersenneQuotient_eq_two_pow_sub_of_half_lt
#print axioms Erdos249257.localPrefixQuotient_succ
#print axioms Erdos249257.mem_mersenneAchievementSet_iff_greedy_survival
#print axioms Erdos249257.mem_mersenneAchievementSet_of_greedySkippedSupport_infinite
#print axioms Erdos249257.mem_mersenneAchievementSet_of_greedy_survival
#print axioms Erdos249257.mersenneGap_le
#print axioms Erdos249257.mersenneGap_pos
#print axioms Erdos249257.mersenneGap_tail_le
#print axioms Erdos249257.mersenneTail_eq_weight_add
#print axioms Erdos249257.mersenneTail_le_two_mul_weight
#print axioms Erdos249257.mersenneTail_lt_weight
#print axioms Erdos249257.middleProducer_allRight_forces_carry_lt_tail
#print axioms Erdos249257.middleProducer_allRight_forces_rational_skip
#print axioms Erdos249257.mobiusCenteredHalfCarry_add_two
#print axioms Erdos249257.mobiusCenteredHalfCarry_nonneg_of_supportSeries_lt_half
#print axioms Erdos249257.mobius_supportCoeff_boolean
#print axioms Erdos249257.mobius_supportCoeff_eq_one_iff
#print axioms Erdos249257.moebius_mul_supportCoeffAF
#print axioms Erdos249257.not_irrational_binaryCoeffSeries_iff_exists_temperedBinaryOrbit
#print axioms Erdos249257.not_irrational_totientSeries_implies_mod_period_and_unbounded_rank
#print axioms Erdos249257.not_irrational_totientSeries_implies_unbounded_carryRank_unconditional
#print axioms Erdos249257.one_add_mul_card_le_two_mul_shifted_state
#print axioms Erdos249257.one_div_twenty_one_mem_iff_not_fatalAlignedBranch
#print axioms Erdos249257.one_div_twenty_one_mem_mersenneAchievementSet_of_cofinalGreedyDecay
#print axioms Erdos249257.one_lt_reciprocalMass_of_dyadic_support_fraction_of_two_pos_mem
#print axioms Erdos249257.positiveMersenneSupportValue_coe_finset_ne_half
#print axioms Erdos249257.precriticalCrossingTax_of_futureThreshold
#print axioms Erdos249257.prefix_add_mersenneTail_lt_half_of_eventually_right
#print axioms Erdos249257.producerCarry_insert_seamBelowSupport_eq_middleCoordinate
#print axioms Erdos249257.seamGreedy_terminal_false_iff_upperOrMiddle
#print axioms Erdos249257.seamUpperBranch_remainder_add_resetCharge_eq
#print axioms Erdos249257.seamUpperResetDyadicBandEscape_through_thirty
#print axioms Erdos249257.shifted_state_unbounded_of_infinite_support
#print axioms Erdos249257.skippedCoreCriticalQuotientSupply_iff_halfGreedySkipped
#print axioms Erdos249257.skippedSeamAlignmentZero_iff_skippedFullShellNonnegative
#print axioms Erdos249257.skipped_fullShell_neg_iff_alignment_and_seamRemainder_pos
#print axioms Erdos249257.sub_two_le_two_pow_sub_four
#print axioms Erdos249257.summable_mersenneGap_shift
#print axioms Erdos249257.summable_mersenneGap_succ
#print axioms Erdos249257.supportCoeff_le_card_divisors
#print axioms Erdos249257.supportCoeff_le_self
#print axioms Erdos249257.temperedBinaryOrbit_eq_scaledTail
#print axioms Erdos249257.tendsto_mersenneGap_tail_zero
#print axioms Erdos249257.totient_carry_residue_window_1_240_eq
#print axioms Erdos249257.totient_series_eq_half_add_moebius_mersenne_square
#print axioms Erdos249257.totient_series_eq_half_add_visible_coprime_pairs
#print axioms Erdos249257.tsum_moebius_div_two_pow_sub_one_sq_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms Erdos249257.tsum_totient_div_pow_two_ne_ratCast_of_den_le_79639646646701375323355774875831053
#print axioms Erdos249257.tsum_visible_coprime_pairs_eq_totient_series
#print axioms Erdos249257.tsum_visible_coprime_pairs_ne_int_div_of_den_le_39819823323350687661677887437915526
#print axioms Erdos249257.twentyOneCofinalEvenQuotientGreedyDecay_of_closedRows
#print axioms Erdos249257.twentyOneFatalAlignedBranch_eventually_affine_supercapacity
#print axioms Erdos249257.twentyOneFatalAlignedBranch_eventually_strict_supercapacity
#print axioms Erdos249257.two_mem_of_exact_localMersenneQuotient
#print axioms Erdos249257.two_mul_mersenneWeight_succ_lt
#print axioms Erdos249257.unboundedTerminalFalse_iff_greedyMersenneSkippedSupport_infinite
#print axioms Erdos68.factorialGapSegment_log_sum_le_channelLCM_add_choose
#print axioms Erdos68.factorial_gap_gcd_exact
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.critical_value_three_budgets
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.critical_value_three_budgets_sharp
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.exists_two_nearest_roots_of_polynomial_critical
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.newton_real_endpoint_whole
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.newton_real_value_whole
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.sextic_spoke_counterexample_whole
#print axioms ErdosProblems.Erdos1041.PaperCompleteR20.two_nearest_roots_of_polynomial_critical
#print axioms ErdosProblems.Erdos1041.PaperCubicCompletion.cubic_paper_complete
#print axioms ErdosProblems.Erdos1041.PaperCubicFibres.complete_translated_cubic_quotient_fibres
#print axioms ErdosProblems.Erdos1041.PaperPrimitiveCompletionR10.complete_primitive_quintic
#print axioms ErdosProblems.Erdos1041.PaperReflectedCompletion.reflected_critical_value
#print axioms ErdosProblems.Erdos1041.PaperSeparationCounterexample.complete_sep_or_counterexample
#print axioms ErdosProblems.Erdos1041.PaperStraightObstructions.complete_straight_path_obstructions
#print axioms ErdosProblems.Erdos1041.PaperTrinomial.all_spokes
#print axioms ErdosProblems.Erdos1041.PaperTrinomial.complete_trinomial
#print axioms ErdosProblems.Erdos1041.PaperTrinomialWholeR21.all_degree_monic_trinomials_whole
#print axioms ErdosProblems.Erdos1041.SharpCollinearChebyshev.exists_peak_le_comparisonBound
#print axioms ErdosProblems.Erdos1041.cubic_has_safe_root_spoke
#print axioms ErdosProblems.Erdos1041.exists_two_roots_dist_sum_le_two_mul_geomMean
#print axioms ErdosProblems.Erdos1041.geometric_row_mean_closed_disc_le
#print axioms ErdosProblems.Erdos1041.paper_critical_value_mean
#print axioms ErdosProblems.Erdos1041.paper_weighted_free_point
#print axioms ErdosProblems.Erdos1041.primitiveInterior_exists_two_tailEnergy_lt_one
#print axioms ErdosProblems.Erdos1041.translated_samePositiveRay_parameterization
#print axioms ErdosProblems.Erdos1049.PaperR17.thirtyone_four_powers
#print axioms ErdosProblems.Erdos1049.PaperR7.charge_ceilings
#print axioms ErdosProblems.Erdos1049.PaperR7.endpoint_residues
#print axioms ErdosProblems.Erdos1049.PaperR7.endpoint_scalar_content_exclusion
#print axioms ErdosProblems.Erdos1049.PaperR7.forcing_term
#print axioms ErdosProblems.Erdos1049.PaperR7.fourJet_paper_statement
#print axioms ErdosProblems.Erdos1049.PaperR7.height_and_hankel_deficits
#print axioms ErdosProblems.Erdos1049.PaperR7.integer_scalar_content
#print axioms ErdosProblems.Erdos1049.PaperR7.omega_indicator
#print axioms ErdosProblems.Erdos1049.PaperR7.pade_summand_bound_and_gap
#print axioms ErdosProblems.Erdos1049.PaperR7.plucker_paper_statement
#print axioms ErdosProblems.Erdos1049.PaperR7.power_bracket
#print axioms ErdosProblems.Erdos1049.PaperR7.rank_fortyone
#print axioms ErdosProblems.Erdos1049.PaperR7.scalar_margin
#print axioms ErdosProblems.Erdos1049.PaperR9.cleared_below_square_not_tendsto_zero
#print axioms ErdosProblems.Erdos1049.PaperR9.long_record_archcap
#print axioms ErdosProblems.Erdos1049.PaperR9.short_note_archimedean_cap
#print axioms ErdosProblems.Erdos1049.bottomJet3_eq_zero_iff_dvd
#print axioms ErdosProblems.Erdos1049.coeff_zudilinNormalizedHankelDet_all_rat
#print axioms ErdosProblems.Erdos1049.commonMultiplier_not_two_not_three_of_endpoint_units
#print axioms ErdosProblems.Erdos1049.coordinatewiseCorridor_implies_pow_lt_linear
#print axioms ErdosProblems.Erdos1049.cyclotomicHomEval_isCoprime_mul
#print axioms ErdosProblems.Erdos1049.exists_ne_map_eq_map_ne_of_card_mul_lt
#print axioms ErdosProblems.Erdos1049.exists_small_real_escape_of_conditional_multiplicity
#print axioms ErdosProblems.Erdos1049.order_zudilinNormalizedHankelDet_all
#print axioms ErdosProblems.Erdos1049.rationalBaseClearedTailQ_succ
#print axioms ErdosProblems.Erdos1049.sevenHalves_archimedean_height_condition
#print axioms ErdosProblems.Erdos1049.threeHalves_no_coordinatewiseCorridor
#print axioms ErdosProblems.Erdos1049.three_mul_lt_two_pow_succ
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.arithmetic_weighted_record_dichotomy
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_inclusive_logLog_criterion
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_negativeError_limsup_gt_one
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_quantitative_record_dichotomy
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_recordTheta_eq_zero_iff
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_recordTheta_gt_one
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_recordTheta_zero_or_gt_one
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.canonical_weighted_record_excess
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.fixed_offsets_periodic_lowerDensity
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.original_coordinate_inclusive_one
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.original_coordinate_inclusive_one_pointwise
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.primePower_persists
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.real_lowerDensityZero_iff_exists_admissible_real_weight
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.absorption_and_descent
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.bounded_negative_endpoint_eventual_multiplier
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.canonical_frontier
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.canonical_tail_ratio_quantitative
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.error_identities
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.finite_negative_mass_paper
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.gcd_stabilises_and_reduces
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.natural_sylvester_of_eventual_zero
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.original_coordinate_bounded_defect
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.original_coordinate_lcm_bounded_defect
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.persistent_coprimality
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.reduced_second_order_int
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.sparse_gcd_changes
#print axioms ErdosProblems.Erdos243.PaperCompleteR7.state_scale
#print axioms ErdosProblems.Erdos243.boundedNegativePart_sylvesterNext_eventually
#print axioms ErdosProblems.Erdos243.cancellationFree_curvature_square
#print axioms ErdosProblems.Erdos243.centeredState_zero_absorbing
#print axioms ErdosProblems.Erdos243.eventuallyBoundedNegativePart_eventually_zero
#print axioms ErdosProblems.Erdos243.exists_shifted_consecutiveMultiples
#print axioms ErdosProblems.Erdos243.forcedSurvives_iff_of_modEq_factorial
#print axioms ErdosProblems.Erdos243.nextTailState_eq_sub_centered
#print axioms ErdosProblems.Erdos243.no_boundedRise_of_tailAvoidance
#print axioms ErdosProblems.Erdos243.sylvesterDefect_mul_nextTailState
#print axioms ErdosProblems.Erdos243.sylvesterNext_eq_of_centered_zero
#print axioms ErdosProblems.Erdos243.sylvesterNext_eventually_of_centered_zero
#print axioms ErdosProblems.Erdos249.PaperCompleteR20.periodic_freezing_integer_affine
#print axioms ErdosProblems.Erdos249.PaperCompleteR20.specified_euler_tail_period
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.RationalObservables.short_note_residue_theorem
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.bounded_isolated_pulse
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.fullDepth_amplification
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.irrational_totient_iff_moebius_square
#print axioms ErdosProblems.Erdos249.PaperCompleteR7.rankOne_denominator_pos
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_all_base_kernel
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_canonical_and_full_dyadic
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_full_dyadic_basis
#print axioms ErdosProblems.Erdos249.PaperCompleteR8.displayed_integral_normal_form
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_101_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_121_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_125_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_127_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_128_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_67_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_81_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.certifiedKill_97_300
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.periodMultipleKillSupply_iff_irrational
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.abs_mobiusMersenneTheta_sub_prefix_le
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.mobiusMersenneTheta_ge_alpha
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.mobiusMersenneTheta_lt_one
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.positive_direct_sum_sub_theta_two_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.positive_direct_sum_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.primitive_form_abs_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_eq_one_five_iff
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_ge_one_five
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_one_five_sub_theta_two_lt_one_div_fifteen
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOne_denominator_pos
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.realTailShift_integral_add
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.real_dyadic_orbit_eq_true_tail_iff
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.signed_two_window_consequences
#print axioms ErdosProblems.Erdos251.PaperCompleteR20.signed_two_window_iff
#print axioms ErdosProblems.Erdos251.PaperR11.SparsePaper.polylogarithmic_word_interval_uniform
#print axioms ErdosProblems.Erdos251.PaperR7.actual_free_pair_criterion
#print axioms ErdosProblems.Erdos251.PaperR7.affine_circularity_bundle
#print axioms ErdosProblems.Erdos251.PaperR7.bounded_recurring_values_countermodel
#print axioms ErdosProblems.Erdos251.PaperR7.cofinal_escape_of_finite_truncation
#print axioms ErdosProblems.Erdos251.PaperR7.denominator_floor_both
#print axioms ErdosProblems.Erdos251.PaperR7.denominator_floor_decimal
#print axioms ErdosProblems.Erdos251.PaperR7.explicit_remainder_certificate
#print axioms ErdosProblems.Erdos251.PaperR7.finite_perturbation_stability
#print axioms ErdosProblems.Erdos251.PaperR7.finite_small_pair
#print axioms ErdosProblems.Erdos251.PaperR7.infinite_prime_gap_identity
#print axioms ErdosProblems.Erdos251.PaperR7.irrational_prime_series_of_finite_truncation
#print axioms ErdosProblems.Erdos251.PaperR7.irrationality_reformulation
#print axioms ErdosProblems.Erdos251.PaperR7.polynomial_countermodel
#print axioms ErdosProblems.Erdos251.PaperR7.prime_gaps_not_eventually_periodic
#print axioms ErdosProblems.Erdos251.PaperR7.rational_bounded_perturbation
#print axioms ErdosProblems.Erdos251.PaperR7.rational_small_pair_bundle
#print axioms ErdosProblems.Erdos251.PaperR7.rationality_classification
#print axioms ErdosProblems.Erdos251.PaperR7.real_block_identity
#print axioms ErdosProblems.Erdos251.PaperR7.real_signed_two_window
#print axioms ErdosProblems.Erdos251.PaperR7.real_small_pair_prime_endpoint
#print axioms ErdosProblems.Erdos251.PaperR8.LogCarry.exists_logarithmic_recurring_values_countermodel
#print axioms ErdosProblems.Erdos251.PaperR9.ShiftCounting.shifted_count_bound
#print axioms ErdosProblems.Erdos251.PaperR9.SparseAmbient.arbitrary_word_sparse_rationalisation_uniform
#print axioms ErdosProblems.Erdos251.carryPartialSum_eq
#print axioms ErdosProblems.Erdos251.dyadicPartialSumQ_eq_start_add_differences
#print axioms ErdosProblems.Erdos251.irrational_initial_iff_all_lcmDiagonal_nonintegral
#print axioms ErdosProblems.Erdos251.irrational_realPrimeGapTail_zero_iff
#print axioms ErdosProblems.Erdos251.irrational_tsum_primeDyadicTerm_iff_primeGap
#print axioms ErdosProblems.Erdos251.prime0_dyadic_summation_by_parts
#print axioms ErdosProblems.Erdos251.realPrimeGapTail_eq_tsum_shifted_gaps
#print axioms ErdosProblems.Erdos251.realPrimeGapTail_recurrence
#print axioms ErdosProblems.Erdos251.realPrimeGapTail_zero
#print axioms ErdosProblems.Erdos251.tailShift_integral_totient_of_odd_den
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.arbitraryWeightMixedSupport_allBase_hereditary
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.divisibilityWeightedClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.finitePrimeWeighted_fixedBase_hereditary
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.mixedSupportClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.strengthenedPositiveCoverClaim
#print axioms ErdosProblems.Erdos257.PaperCompleteR8.weighted_displacement_cofinal_close_return
#print axioms ErdosProblems.Erdos257.perfect_supportedMersenneAchievementSet
#print axioms ErdosProblems.Erdos257.supportedMersenneDigitValue_injective
#print axioms ErdosProblems.Erdos257.volume_supportedMersenneAchievementSet_dichotomy
#print axioms ErdosProblems.Erdos257.volume_supportedMersenneAchievementSet_eq_zero_of_compl_infinite
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.actual_cubic_no_crossing_strips
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.actual_weighted_strip_decomposition
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.conditional_denominator_reduction_real_bound
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.dyadic_alphabet_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.exponent_unique_real_base_short_interval
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.fixed_base_recoding_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.literal_triangle_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.long_all_scale_lattice_exact
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.octic_escape_whole
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.paper_pinning_and_eight_scale_rigidity
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_eq_of_sameLogCell
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_first
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_second
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realPrefixLcm_jump_third
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.realSmoothExponentShell_bounds
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.real_two_prime_separation
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.running_lcm_real_cutoff_exact
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.threePrimeKernelQ_eq_of_sameRealLogCell
#print axioms ErdosProblems.Erdos269.PaperCompleteR20.weighted_shift_whole
#print axioms ErdosProblems.Erdos269.PaperR10.actual_sharp_tail_bound
#print axioms ErdosProblems.Erdos269.PaperR11.longPaperCap_le_three_squareR11
#print axioms ErdosProblems.Erdos269.PaperR11.long_fixed_split_bridgeR11
#print axioms ErdosProblems.Erdos269.PaperR13.clearingCondition_iff_max
#print axioms ErdosProblems.Erdos269.PaperR13.exact_denominators_and_minimal_clearing
#print axioms ErdosProblems.Erdos269.PaperR13.firstClearingIndex_le_sufficient
#print axioms ErdosProblems.Erdos269.PaperR13.firstClearingIndex_minimal
#print axioms ErdosProblems.Erdos269.PaperR13.firstClearingIndex_spec
#print axioms ErdosProblems.Erdos269.PaperR13.scaled_state_is_integer_iff_firstClearingIndex_le
#print axioms ErdosProblems.Erdos269.PaperR14.eventually_fixedStartResidue_eq_tail_of_integral
#print axioms ErdosProblems.Erdos269.PaperR14.eventually_fixedStartResidue_formula
#print axioms ErdosProblems.Erdos269.PaperR14.fixedStartResidue_ratio_tendsto
#print axioms ErdosProblems.Erdos269.PaperR7.admissible_modular_minors
#print axioms ErdosProblems.Erdos269.PaperR7.allReducedTailsNonintegral_iff
#print axioms ErdosProblems.Erdos269.PaperR7.long_actual_orbit
#print axioms ErdosProblems.Erdos269.PaperR7.long_no_bounded_length
#print axioms ErdosProblems.Erdos269.PaperR7.long_window_growth
#print axioms ErdosProblems.Erdos269.PaperR7.paper_finite_endpoint_obstruction
#print axioms ErdosProblems.Erdos269.PaperR7.paper_jump_count
#print axioms ErdosProblems.Erdos269.PaperR7.paper_two_by_two_fixture
#print axioms ErdosProblems.Erdos269.PaperR7.paper_uniform_rank_and_nonseparation
#print axioms ErdosProblems.Erdos269.PaperR7.radix_eq_height_ratio
#print axioms ErdosProblems.Erdos269.PaperR7.rank_cutMatrix
#print axioms ErdosProblems.Erdos269.PaperR7.scaled_integer_or_cofinal_separation
#print axioms ErdosProblems.Erdos269.PaperR7.short_actual_orbit
#print axioms ErdosProblems.Erdos269.PaperR7.short_fixed_split_bridge
#print axioms ErdosProblems.Erdos269.PaperR7.short_window_equivalence
#print axioms ErdosProblems.Erdos269.PaperR8.actual_tail_rank_bound
#print axioms ErdosProblems.Erdos269.PaperR8.uniform_rank_complete
#print axioms ErdosProblems.Erdos269.dyadicBlockBase235
#print axioms ErdosProblems.Erdos269.dyadicBlockBase235_cases
#print axioms ErdosProblems.Erdos269.dyadicBlockBase235_mem_interval
#print axioms ErdosProblems.Erdos269.dyadicInternalPower_exponent_unique
#print axioms ErdosProblems.Erdos269.exists_dyadicInternalPower_iff_log_succ
#print axioms ErdosProblems.Erdos269.finiteSmoothKernelSum_groupedByHeight
#print axioms ErdosProblems.Erdos269.log_dyadic_succ_eq_of_no_internalPower
#print axioms ErdosProblems.Erdos269.no_bounded_positive_int_state_of_leastPositiveResidue
#print axioms ErdosProblems.Erdos269.no_positive_reducedCarry_of_cofinalLocalWindowEscape
#print axioms ErdosProblems.Erdos269.threePrimeHeight_dyadicBlock_succ
#print axioms ErdosProblems.Erdos68.PaperComplete.asymptotic_radius_constant_liminf
#print axioms ErdosProblems.Erdos68.PaperComplete.carry_characterisation
#print axioms ErdosProblems.Erdos68.PaperComplete.cofinal_first_prime_occurrences
#print axioms ErdosProblems.Erdos68.PaperComplete.common_denominator_growth_liminf
#print axioms ErdosProblems.Erdos68.PaperComplete.companion_orbit
#print axioms ErdosProblems.Erdos68.PaperComplete.companion_orbit_boundary
#print axioms ErdosProblems.Erdos68.PaperComplete.divisor_channel_coordinates
#print axioms ErdosProblems.Erdos68.PaperComplete.equal_moment_residual_integer_difference
#print axioms ErdosProblems.Erdos68.PaperComplete.exact_moment_ideal_with_primitive_attainment
#print axioms ErdosProblems.Erdos68.PaperComplete.finite_channel_moment_certificate
#print axioms ErdosProblems.Erdos68.PaperComplete.finite_channel_moment_certificate_eq
#print axioms ErdosProblems.Erdos68.PaperComplete.global_complementary_criterion_nat
#print axioms ErdosProblems.Erdos68.PaperComplete.global_complementary_criterion_prime
#print axioms ErdosProblems.Erdos68.PaperComplete.lower_interval_criterion
#print axioms ErdosProblems.Erdos68.PaperComplete.maximal_prime_power_survival
#print axioms ErdosProblems.Erdos68.PaperComplete.minimumMoment_independent_prime
#print axioms ErdosProblems.Erdos68.PaperComplete.prime_channel_corrector
#print axioms ErdosProblems.Erdos68.PaperComplete.product_lcm_pairwise_gcd
#print axioms ErdosProblems.Erdos68.PaperComplete.radius_no_eventual_ratio_upper
#print axioms ErdosProblems.Erdos68.PaperComplete.radius_not_littleO
#print axioms ErdosProblems.Erdos68.PaperComplete.residual_transparency
#print axioms ErdosProblems.Erdos68.PaperComplete.square_subsequence_radius
#print axioms ErdosProblems.Erdos68.PaperComplete.strict_successor_characterisation
#print axioms ErdosProblems.Erdos68.PaperComplete.summable_fullResidual
#print axioms ErdosProblems.Erdos68.PaperComplete.supported_breakpoint_escape
#print axioms ErdosProblems.Erdos68.PaperComplete.supported_first_band_cancellation
#print axioms ErdosProblems.Erdos68.PaperComplete.supported_integral_normal_form
#print axioms ErdosProblems.Erdos68.PaperComplete.supported_quotient_band
#print axioms ErdosProblems.Erdos68.PaperComplete.uniform_family_boundary
#print axioms ErdosProblems.Erdos68.PaperComplete.uniform_family_members
#print axioms ErdosProblems.Erdos68.PaperComplete.zero_moment_residual_integral
#print axioms ErdosProblems.Skip.LadderT67.exists_diagonalKill_le_82
#print axioms GapFareyBound.farey_gap
#print axioms GapFareyBound.gap_check_window_1_240_first_failure
#print axioms GapFareyBound.gap_check_window_1_240_le_79639646646701375323355774875831053
#print axioms GcdMomentCalculus.cylinderMass_children_le
#print axioms GcdMomentCalculus.sternBrocotDepthMass_error
#print axioms GcdMomentCalculus.tendsto_sternBrocotDepthMass
#print axioms GcdMomentCalculus.tsum_lambert_linear_weight_sq_pure
#print axioms GcdMomentCalculus.tsum_pos_coprime_inv_mersenne_eq_one
#print axioms GcdMomentCalculus.tsum_pos_pair_both_dvd_half_eq_inv_mersenne_sq
#print axioms GeometricCoprimality.tsum_gcd_layer_pos_coprime_half_eq_one
#print axioms MersenneLambertLadder.tsum_moebius_div_two_pow_sub_one_eq_half
#print axioms MersenneLambertLadder.tsum_moebius_lambert_sq
