/-
Copyright (c) 2026 Will Cook. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Will Cook
-/
-- Generated by scripts/build_comparator_replay_portfolio.py; do not edit.
-- Aggregate Challenge for a Comparator replay candidate. This is not a replay receipt.
import ExternalVerification1041CentralFreePoint.Challenge
import ExternalVerification1041CubicPath.Challenge
import ExternalVerification1041CubicRootCount.Challenge
import ExternalVerification1041SolvedFamilies.Challenge
import ExternalVerification1049ArchimedeanCap.Challenge
import ExternalVerification243WeightedRecordExcess.Challenge
import ExternalVerification249TotientKernelBasis.Challenge
import ExternalVerification68FiniteDenominator.Challenge
import ExternalVerification68MomentIdealResidual.Challenge
