/-
Copyright (c) 2026 Will Cook. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Will Cook
-/
-- Generated by scripts/build_comparator_replay_portfolio.py; do not edit.
-- Aggregate Solution for a Comparator replay candidate. This is not a replay receipt.
import Solutions.ExternalVerification1041CentralFreePoint
import Solutions.ExternalVerification1041CubicPath
import Solutions.ExternalVerification1041CubicRootCount
import ExternalVerification1041SolvedFamilies.Solution
import Solutions.ExternalVerification1049ArchimedeanCap
import Solutions.ExternalVerification243WeightedRecordExcess
import Solutions.ExternalVerification249TotientKernelBasis
import Solutions.ExternalVerification68FiniteDenominator
import Solutions.ExternalVerification68MomentIdealResidual
