import ExternalVerification257FourNinthsTetraprime.Solution

#print axioms Erdos249257.ExternalVerification257FourNinthsTetraprime.fourNinthsTetraprime_baseKernel
#print axioms Erdos249257.ExternalVerification257FourNinthsTetraprime.fourNinthsTetraprimePrimeRepair_defect_le_thirty_five
#print axioms Erdos249257.ExternalVerification257FourNinthsTetraprime.fourNinthsTetraprime_completeCounterexample
