import ErdosProblems.Erdos257.PaperCompleteR7.All

/-! Uncompiled audit commands. Output must be obtained in the pinned workspace. -/

#check ErdosProblems.Erdos257.PaperCompleteR7.short_finite_period
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.short_finite_period
#check ErdosProblems.Erdos257.PaperCompleteR7.short_general_repair
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.short_general_repair
#check ErdosProblems.Erdos257.PaperCompleteR7.long_general_repair
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_general_repair
#check ErdosProblems.Erdos257.PaperCompleteR7.long_scaled_greedy_trap
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_scaled_greedy_trap
#check ErdosProblems.Erdos257.PaperCompleteR7.long_rational_membership
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_rational_membership
#check ErdosProblems.Erdos257.PaperCompleteR7.long_achievement_geometry
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_achievement_geometry
#check ErdosProblems.Erdos257.PaperCompleteR7.long_supported_dichotomy
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_supported_dichotomy
#check ErdosProblems.Erdos257.PaperCompleteR7.long_tempered_orbit_rigidity
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_tempered_orbit_rigidity
#check ErdosProblems.Erdos257.PaperCompleteR7.irrational_support_of_eventual_agreement
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.irrational_support_of_eventual_agreement
#check ErdosProblems.Erdos257.PaperCompleteR7.long_finite_symmetric_difference
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_finite_symmetric_difference
#check ErdosProblems.Erdos257.PaperCompleteR7.signed_period_with_bound
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.signed_period_with_bound
#check ErdosProblems.Erdos257.PaperCompleteR7.long_boolean_mobius_correspondence
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_boolean_mobius_correspondence
#check ErdosProblems.Erdos257.PaperCompleteR7.long_greedy_survival_and_fatal_dichotomy
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_greedy_survival_and_fatal_dichotomy
#check ErdosProblems.Erdos257.PaperCompleteR7.long_half_one_sided
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_half_one_sided
#check ErdosProblems.Erdos257.PaperCompleteR7.half_membership_requires_infinite_support
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.half_membership_requires_infinite_support
#check ErdosProblems.Erdos257.PaperCompleteR7.long_fatal_absorption
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_fatal_absorption
#check ErdosProblems.Erdos257.PaperCompleteR7.long_two_channel_and_dyadic_caps
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_two_channel_and_dyadic_caps
#check ErdosProblems.Erdos257.PaperCompleteR7.long_second_channel_consumers
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_second_channel_consumers
#check ErdosProblems.Erdos257.PaperCompleteR7.long_factorial_and_geometric
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_factorial_and_geometric
#check ErdosProblems.Erdos257.PaperCompleteR7.long_multiples
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_multiples
#check ErdosProblems.Erdos257.PaperCompleteR7.long_residue_and_odd
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_residue_and_odd
#check ErdosProblems.Erdos257.PaperCompleteR7.long_signed_periodic
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_signed_periodic
#check ErdosProblems.Erdos257.PaperCompleteR7.long_half_regressions
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_half_regressions
#check ErdosProblems.Erdos257.PaperCompleteR7.long_mersenne_tail_package
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_mersenne_tail_package
#check ErdosProblems.Erdos257.PaperCompleteR7.long_half_endpoint_exclusions
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_half_endpoint_exclusions
#check ErdosProblems.Erdos257.PaperCompleteR7.critical_band_range_counterexample
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.critical_band_range_counterexample
#check ErdosProblems.Erdos257.PaperCompleteR7.critical_band_equivalence_requires_range
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.critical_band_equivalence_requires_range
#check ErdosProblems.Erdos257.PaperCompleteR7.displacementAtom_nonneg
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacementAtom_nonneg
#check ErdosProblems.Erdos257.PaperCompleteR7.summable_displacementAtom
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.summable_displacementAtom
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_eq_tsum
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_eq_tsum
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_nonneg
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_nonneg
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_pos
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_pos
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_mono
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_mono
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_partition
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_partition
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_union_le
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_union_le
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_finset_eq_zero
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_finset_eq_zero
#check ErdosProblems.Erdos257.PaperCompleteR7.displacementAtom_le_amplified
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacementAtom_le_amplified
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_le_amplified_mass
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_le_amplified_mass
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_future_eq
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_future_eq
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_residual_budget
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_residual_budget
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_le_two_mul_binary
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_le_two_mul_binary
#check ErdosProblems.Erdos257.PaperCompleteR7.irrational_of_displacement_returns
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.irrational_of_displacement_returns
#check ErdosProblems.Erdos257.PaperCompleteR7.all_base_hereditary_of_binary_returns
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.all_base_hereditary_of_binary_returns
#check ErdosProblems.Erdos257.PaperCompleteR7.low_row_certificates
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.low_row_certificates
#check ErdosProblems.Erdos257.PaperCompleteR7.row_thirty_one_remainder
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.row_thirty_one_remainder
#check ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_factor
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_factor
#check ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_rank_le_one
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_rank_le_one
#check ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_all_minors_zero
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.relationInvariantChannels_all_minors_zero
#check ErdosProblems.Erdos257.PaperCompleteR7.long_linear_channel_no_go
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.long_linear_channel_no_go
#check ErdosProblems.Erdos257.PaperCompleteR7.skip_card_le_row
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.skip_card_le_row
#check ErdosProblems.Erdos257.PaperCompleteR7.skip_card_lt_quadratic_eighth
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.skip_card_lt_quadratic_eighth
#check ErdosProblems.Erdos257.PaperCompleteR7.no_eventual_quadratic_skip_size
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.no_eventual_quadratic_skip_size
#check ErdosProblems.Erdos257.PaperCompleteR7.denominator_zero_counterexample
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.denominator_zero_counterexample
#check ErdosProblems.Erdos257.PaperCompleteR7.denominator_survival_requires_nonzero
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.denominator_survival_requires_nonzero
#check ErdosProblems.Erdos257.PaperCompleteR7.divisor_power_zero_counterexample
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.divisor_power_zero_counterexample
#check ErdosProblems.Erdos257.PaperCompleteR7.divisor_power_bound_requires_domain
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.divisor_power_bound_requires_domain
#check ErdosProblems.Erdos257.PaperCompleteR7.three_cell_complement
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.three_cell_complement
#check ErdosProblems.Erdos257.PaperCompleteR7.supportSeries_le_mersenneTail
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.supportSeries_le_mersenneTail
#check ErdosProblems.Erdos257.PaperCompleteR7.mersenneTail_le_dyadic_budget
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.mersenneTail_le_dyadic_budget
#check ErdosProblems.Erdos257.PaperCompleteR7.displacement_future_budget
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.displacement_future_budget
#check ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_mono
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_mono
#check ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_hereditary_irrational
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_hereditary_irrational
#check ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_of_samples
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.returnAdmissible_of_samples
#check ErdosProblems.Erdos257.PaperCompleteR7.delayed_countable_gluing
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.delayed_countable_gluing
#check ErdosProblems.Erdos257.PaperCompleteR7.next_multiple_in_window
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.next_multiple_in_window
#check ErdosProblems.Erdos257.PaperCompleteR7.incidence_zero_window_lt_selected
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.incidence_zero_window_lt_selected
#check ErdosProblems.Erdos257.PaperCompleteR7.incidence_zero_window_eps_logb
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.incidence_zero_window_eps_logb
#check ErdosProblems.Erdos257.PaperCompleteR7.exists_uniform_incidence_zero_window_bound
#print axioms ErdosProblems.Erdos257.PaperCompleteR7.exists_uniform_incidence_zero_window_bound
