import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos1041.CubicCriticalHub
import ErdosProblems.Erdos1049.QAperyTailDenominator
import ErdosProblems.Root
import Erdos249257.AffineDiagonalKill

/-!
# Assumption audit for the problem-owned assimilation root

This file is intentionally executable documentation.  The release gate builds
it and records the assumptions of the main results brought in by the first
problem-centric wave.
-/

#print axioms ErdosProblems.Erdos269.threePrimeHeight_le_cube
#print axioms ErdosProblems.Erdos269.smoothPrefixLcm_eq_threePrimeHeight
#print axioms ErdosProblems.Erdos269.smoothPrefixLcm_eq_of_sameLogCell
#print axioms ErdosProblems.Erdos269.finiteSmoothKernelSum_groupedByHeight
#print axioms ErdosProblems.Erdos269.smoothPrefixLcm_firstLogStep
#print axioms ErdosProblems.Erdos269.threePrimePositiveJumpSet_card
#print axioms ErdosProblems.Erdos269.threePrimeJumpSetWithOrigin_card
#print axioms ErdosProblems.Erdos269.kernel_235_not_rankOne
#print axioms ErdosProblems.Erdos269.smoothExponentShell_card_quadratic
#print axioms ErdosProblems.Erdos269.dyadicInternalPower_exponent_unique
#print axioms ErdosProblems.Erdos269.dyadicBlockBase235_cases
#print axioms ErdosProblems.Erdos269.dyadicBlockBase235_mem_interval
#print axioms ErdosProblems.Erdos269.no_bounded_positive_state_of_residue_escape
#print axioms ErdosProblems.Erdos1049.threeHalves_no_coordinatewiseCorridor
#print axioms ErdosProblems.Erdos1049.rationalBaseClearedTailQ_succ
#print axioms ErdosProblems.Erdos1049.twoPow_le_rationalBaseForcingNat
#print axioms ErdosProblems.Erdos1049.sevenHalves_power_certificate
#print axioms ErdosProblems.Erdos1049.sevenHalves_rational_margin
#print axioms ErdosProblems.Erdos1049.rationalPadePSummandDenExpTwice_le
#print axioms ErdosProblems.Erdos1049.rationalPadeQMaxDenExpTwice_le
#print axioms ErdosProblems.Erdos1049.rationalPadeExteriorDet_cast_eq
#print axioms ErdosProblems.Erdos1049.rationalPadeError_mul
#print axioms ErdosProblems.Erdos1049.rationalPadeExteriorDet_mul_contents
#print axioms ErdosProblems.Erdos1049.natAbs_rationalPadeExteriorDet_mul_contents
#print axioms ErdosProblems.Erdos1049.contentProduct_dvd_rationalPadeExteriorDet
#print axioms ErdosProblems.Erdos1049.commonU_dvd_rationalPadeExteriorDet
#print axioms ErdosProblems.Erdos1049.commonV_dvd_rationalPadeExteriorDet
#print axioms ErdosProblems.Erdos1049.rationalPadeExteriorDet_ne_zero_of_left_neg_right_pos
#print axioms ErdosProblems.Erdos1049.rationalPadeExteriorDet_ne_zero_of_left_pos_right_neg
#print axioms ErdosProblems.Erdos1049.fourJetSignature_card
#print axioms ErdosProblems.Erdos1049.exists_distinct_binary_selectors_same_fourJet_of_rank
#print axioms ErdosProblems.Erdos1049.commonMultiplier_not_two_not_three_of_endpoint_units
#print axioms ErdosProblems.Erdos1049.cyclotomicHomEval_isCoprime_mul
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.image_pivotSupplierPrimes_eq_pivotFiber
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.supplierPrime_not_globally_isolated_counterexample
#print axioms ErdosProblems.Erdos251.carryPartialSum_eq
#print axioms ErdosProblems.Erdos251.carryPartialSum_natCast_eq
#print axioms ErdosProblems.Erdos251.carryCoeff_natCast_not_eventually_periodic
#print axioms ErdosProblems.Erdos251.prime0_dyadic_summation_by_parts
#print axioms ErdosProblems.Erdos251.prime0DisplayedPartialSumQ_eq_two_mul
#print axioms ErdosProblems.Erdos251.exists_primeGap0_gt
#print axioms ErdosProblems.Erdos251.tailShift_not_both_integral_of_small_pair_of_digit_ne
#print axioms ErdosProblems.Erdos251.not_eventuallyIntegralTailShift_of_cofinal_small_mismatch
#print axioms ErdosProblems.Erdos251.primeGap0_not_eventually_periodic
#print axioms ErdosProblems.Erdos251.primeGapTailShift_not_eventuallyIntegral_of_cofinal_small_mismatch
#print axioms ErdosProblems.Erdos251.tailShift_integral_add
#print axioms ErdosProblems.Erdos251.tailShift_integral_iff_scaledTail
#print axioms ErdosProblems.Erdos251.tailShift_integral_totient_of_odd_den
#print axioms ErdosProblems.Erdos251.natCarryCoeff_cast
#print axioms ErdosProblems.Erdos243.sylvesterDefect_mul_nextTailState
#print axioms ErdosProblems.Erdos243.no_normalizedConstantNegative_orbit
#print axioms ErdosProblems.Erdos243.no_scalePrimitiveConstantNegative_orbit
#print axioms ErdosProblems.Erdos243.no_constantNegative_orbit
#print axioms ErdosProblems.Erdos243.no_eventuallyConstantNegative_orbit
#print axioms ErdosProblems.Erdos243.repeatedDivisor_forces_periodicCommonScale
#print axioms ErdosProblems.Erdos243.no_phasePrimitivePeriodicNegative_orbit
#print axioms ErdosProblems.Erdos243.no_periodicNegative_orbit
#print axioms ErdosProblems.Erdos243.no_eventuallyPeriodicNegative_orbit
#print axioms ErdosProblems.Erdos243.exists_shifted_consecutiveMultiples
#print axioms ErdosProblems.Erdos243.no_boundedRise_of_tailAvoidance
#print axioms ErdosProblems.Erdos243.reducedStep_coprime_currentFactor
#print axioms ErdosProblems.Erdos243.reducedTail_pairwiseCoprime
#print axioms ErdosProblems.Erdos243.reducedTail_wholeModulusAvoidance
#print axioms ErdosProblems.Erdos243.no_boundedRise_reducedTail
#print axioms ErdosProblems.Erdos243.no_eventuallyBoundedRise_reducedTail
#print axioms ErdosProblems.Erdos243.cancellationFactor_sandwich
#print axioms ErdosProblems.Erdos243.cancellationFactor_eq_one_iff
#print axioms ErdosProblems.Erdos243.pow_strictGrowthCount_mul_le
#print axioms ErdosProblems.Erdos243.pow_strictGrowthCountFrom_mul_le
#print axioms ErdosProblems.Erdos243.strictGrowthCount_sublinear_of_subexponential
#print axioms ErdosProblems.Erdos243.strictGrowthCount_add
#print axioms ErdosProblems.Erdos243.strictGrowthCount_pos_of_event
#print axioms ErdosProblems.Erdos243.exists_aligned_noStrictGrowthBlock_of_count_bound
#print axioms ErdosProblems.Erdos243.exists_arbitrarilyLate_noStrictGrowthBlock_of_sublinear
#print axioms ErdosProblems.Erdos243.exists_arbitrarilyLate_constBlock_of_sublinear
#print axioms ErdosProblems.Erdos243.tailGcd_dvd_succ
#print axioms ErdosProblems.Erdos243.tailGcd_strictGrowthCount_sublinear_of_tailSubexponential
#print axioms ErdosProblems.Erdos243.dynamicReducedTail_step
#print axioms ErdosProblems.Erdos243.tailGcdGrowthFactor_sandwich
#print axioms ErdosProblems.Erdos243.tailGcdGrowthFactor_eq_one_iff
#print axioms ErdosProblems.Erdos243.tailGcd_eq_gcd_negativeMagnitude
#print axioms ErdosProblems.Erdos243.dvdChain_eventuallyConstant_of_cofinally_bounded
#print axioms ErdosProblems.Erdos243.tailGcd_eventuallyConstant_of_cofinally_boundedNegative
#print axioms ErdosProblems.Erdos243.no_cofinallyBoundedNegative_of_tailTendsto
#print axioms ErdosProblems.Erdos243.tailState_tendsto_atTop_of_nonzero_normalizedVanishes
#print axioms ErdosProblems.Erdos243.no_cofinallyBoundedNegative_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.sylvesterNext_eq_of_centered_zero
#print axioms ErdosProblems.Erdos243.sylvesterNext_eventually_of_centered_zero
#print axioms ErdosProblems.Erdos243.antitone_nat_eventually_constant
#print axioms ErdosProblems.Erdos243.centeredState_eventually_zero
#print axioms ErdosProblems.Erdos243.tailState_localNearUnitGrowth
#print axioms ErdosProblems.Erdos243.tailState_eventually_localNearUnitGrowth_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.exists_nearUnitPower_rate
#print axioms ErdosProblems.Erdos243.eventually_const_mul_pow_lt_const_mul_pow
#print axioms ErdosProblems.Erdos243.subexponential_of_eventually_nearUnitGrowth
#print axioms ErdosProblems.Erdos243.tailState_subexponential_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.tailGcd_strictGrowthCount_sublinear_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.tailGcd_exists_arbitrarilyLate_constBlock_of_normalizedVanishes
#print axioms ErdosProblems.Erdos243.centeredState_zero_absorbing
#print axioms ErdosProblems.Erdos243.boundedNegativePart_eventually_zero
#print axioms ErdosProblems.Erdos243.eventuallyBoundedNegativePart_eventually_zero
#print axioms ErdosProblems.Erdos243.forcedSurvives_iff_of_modEq_factorial
#print axioms ErdosProblems.Erdos243.rawNext_coprime_currentNumerator
#print axioms ErdosProblems.Erdos243.rawNext_gcd_eq_gcd_sq
#print axioms ErdosProblems.Erdos243.rawNext_gcd_exact_overlap
#print axioms ErdosProblems.Erdos243.gcd_scaled_square_eq
#print axioms ErdosProblems.Erdos243.cancellationOverlap_normalForm_explicit
#print axioms ErdosProblems.Erdos243.cancellation_denominator_transport_explicit
#print axioms ErdosProblems.Erdos243.deletedFactor_eq_oldDenominator_div_gcd
#print axioms ErdosProblems.Erdos243.lcm_eq_overlap_mul_nextDenominator
#print axioms ErdosProblems.Erdos243.reducedStep_consecutiveNumerator_coprime
#print axioms ErdosProblems.Erdos243.reducedStep_cancellationFactor_eq_square
#print axioms ErdosProblems.Erdos243.reducedStep_secondOrder
#print axioms ErdosProblems.Erdos243.cancellationFree_dualRemainder
#print axioms ErdosProblems.Erdos243.cancellationFree_curvature_square
#print axioms ErdosProblems.Erdos243.excursionMatrix_det_square
#print axioms ErdosProblems.Erdos243.primitiveMatrix_gcd_eq_det_gcd
#print axioms ErdosProblems.Erdos243.blockCancellationPayment_explicit
#print axioms ErdosProblems.Erdos243.excursionCancellationPayment
#print axioms ErdosProblems.Erdos243.blockScale_product_telescopes
#print axioms ErdosProblems.Erdos243.blockScale_product_subexponential
#print axioms ErdosProblems.Erdos243.scaledRecord_forces_payment
#print axioms ErdosProblems.Erdos243.squareResiduePayment_of_scaledRecord

/-! ## Second wave: shrinking-target, repair-entropy, carry-rank, adelic-height

Added by the Comparator-widening pass.  Every declaration below is expected to
depend on exactly `propext`, `Classical.choice`, `Quot.sound`. -/

#print axioms ErdosProblems.Shared.exists_pos_nat_fract_mem_Ioo
#print axioms ErdosProblems.Shared.det_carryStaircase
#print axioms ErdosProblems.Shared.exists_staircase_indices
#print axioms ErdosProblems.Erdos269.log_mul_eq_add_log_add_logCarry
#print axioms ErdosProblems.Erdos269.logCarry_pow_eq_floor_fract
#print axioms ErdosProblems.Erdos269.noIntegerOrbit_logb_of_prime
#print axioms ErdosProblems.Erdos269.threePrimeHeight_factorisation
#print axioms ErdosProblems.Erdos269.twoPrimeKernelQ_eq_outer_product
#print axioms ErdosProblems.Erdos269.exists_uniform_nonsingular_threePrimeKernel_minor
#print axioms ErdosProblems.Erdos269.exists_uniform_nonsingular_threePrimeKernel_minor_of_prime
#print axioms ErdosProblems.Erdos269.not_finite_separable_threePrimeKernel
#print axioms ErdosProblems.Erdos269.finite_realisedSpan_of_functionFaithfulObserver
#print axioms Erdos68.sharp_radius_satisfies_square_log_constraint
#print axioms ErdosProblems.Erdos269.kernel_235_minor_eq_neg_one_fifteen
#print axioms ErdosProblems.Erdos269.kernel_235_minor3_eq_one_over_81000
#print axioms ErdosProblems.Erdos269.kernel_235_row_three_eq_smul_row_zero
#print axioms ErdosProblems.Erdos269.kernel_235_row_three_ne_smul_row_zero_at_four
#print axioms ErdosProblems.Erdos68.factorialGap_lower_endpoint_escape_iff_nonunit_or_maximal_digit
#print axioms ErdosProblems.Erdos68.irrational_factorialGapSeries_iff_cofinal_lower_endpoint_escape
#print axioms ErdosProblems.Erdos68.irrational_factorialGapSeries_of_cofinal_predecessorGap_outside_window
#print axioms ErdosProblems.Erdos68.lower_endpoint_target_radius_lt_two_div_sq
#print axioms ErdosProblems.Erdos243.repairedFamily_recovery_energy_divisionFree
#print axioms ErdosProblems.Erdos243.repaired_card_bound_of_independent
#print axioms ErdosProblems.Erdos243.eventually_recoveryPayment_eq_one_of_fixedLength
#print axioms ErdosProblems.Erdos243.survivor_overlap_dvd_centeredError
#print axioms ErdosProblems.Erdos243.repairedFamily_log_energy
#print axioms ErdosProblems.Erdos1049.threeHalves_bv_height_gap_gt_threeThirteenths
#print axioms ErdosProblems.Erdos1049.threeHalves_rectangular_hp_gap_gt_threeThirteenths
#print axioms ErdosProblems.Erdos1049.threeHalves_hankelChargeThreshold_lt_eightFortyOne
#print axioms ErdosProblems.Erdos1049.three_two_scalar_margin_lt_explicit
#print axioms ErdosProblems.Erdos1049.exists_distinct_binary_selectors_same_fourJet_of_rank_41
#print axioms ErdosProblems.Erdos1049.fourJet_card_gt_two_pow_of_rank_41
#print axioms ErdosProblems.Erdos1049.exists_ne_map_eq_map_ne_of_card_mul_lt
#print axioms ErdosProblems.Erdos251.tailShift_integral_iff_orderOf_dvd
#print axioms ErdosProblems.Erdos251.irrational_initial_iff_nonintegral_on_schedule
#print axioms ErdosProblems.Erdos251.irrational_initial_iff_all_factorialDiagonal_nonintegral
#print axioms ErdosProblems.Erdos1041.equal_norm_add_imp_mem_realAffineLine
#print axioms ErdosProblems.Erdos1041.exists_small_translation_separating_arguments_and_norms

/-! ## Third wave: sharp floor of the positive rank-one Schur cone

Replaces the live `1/480` uniform gap with the exact minimiser `(e,Y)=(1,5)`
and the uniform gap `21/320`.  `1/16` is the optimal uniform unit fraction;
`1/15` fails at the minimiser. -/

#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_one_five
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_eq_one_five_iff
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.rankOneSubrankQuotient_sub_theta_two_gt_one_div_sixteen
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.not_forall_rankOneSubrankQuotient_sub_theta_two_gt_one_div_fifteen
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.positive_direct_sum_sub_theta_two_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.RankOneSubrankObstruction.primitive_form_abs_gt_twentyOne_div_threeTwenty
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.exists_pointwiseTotientValued_permanent_endpointTrap
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.exists_actualTotientLetter_ne_two
#print axioms ErdosProblems.Erdos249.PeriodMultipleEscape.actualTotientWord_ne_const_two

/-! ## Fourth wave: successor objects

The eight successor Type B lanes.  Headline: the #249 full-depth ray amplifier,
which upgrades `ApFullDepthEscape` from sufficient to *equivalent* and so
deletes the depth quantifier from the exact kill supply.  Every declaration
below is expected to depend on exactly `propext`, `Classical.choice`,
`Quot.sound`. -/

#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.abs_pow_mul_shift_sub_windowDiscrepancy_le
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.one_le_pow_mul_abs_shift_sub_int
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.certifiedKill_of_forall_dist
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.exists_int_shift_concat
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.forall_dist_adjacent_of_seed
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.exists_adjacent_fullDepthKill_of_seed
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.exists_fullDepthKill_on_ray_of_seed
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.exists_fullDepthKill_on_ray_iff_shift_notMem_int
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.apFullDepthEscape_iff_irrational
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_periodMultipleKillSupply
#print axioms ErdosProblems.Erdos249.FullDepthRayAmplifier.cofinalFullDepthKillSupply_iff_irrational
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.bezoutPluckerEquiv_anchor
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.exists_scalar_eq_of_det_eq_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.anchor_det_zero_forces_all_det_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.adjacent_det_zero_forces_all_det_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.zmod_tail_pair_det_zero_of_adjacent_det_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.zmod_binary_tail_collision_of_adjacent_det_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.zmod_binary_tail_collision_of_two_three_depth
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.exists_binary_collision_of_card_lt
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.binary_row_collision_of_anchor_det_zero
#print axioms ErdosProblems.Erdos1049.BezoutPluckerJets.zmod_binary_row_collision_of_anchor_det_zero
#print axioms ErdosProblems.Erdos243.centered_rawNext_gcd
#print axioms ErdosProblems.Erdos243.orientedSquareRoot_iff_feedback
#print axioms ErdosProblems.Erdos243.feedbackTransport_existsUnique_iff
#print axioms ErdosProblems.Erdos243.canonicalRoot_feedback_iff_existsUnique
#print axioms ErdosProblems.Erdos243.rawNext_gcd_eq_gcd_denominator_sq
#print axioms ErdosProblems.Erdos243.fifteen_fake_root_four
#print axioms ErdosProblems.Erdos243.orientation_determines_root
#print axioms ErdosProblems.Erdos243.forcedClock_forcedState_succ
#print axioms ErdosProblems.Erdos243.dvd_forcedClock_of_forcedSurvives
#print axioms ErdosProblems.Erdos243.not_forcedSurvives_of_two_le
#print axioms ErdosProblems.Erdos243.forcedSurvives_one
#print axioms ErdosProblems.Erdos243.factorialGhost_survives
#print axioms ErdosProblems.Erdos243.survivor_window
#print axioms ErdosProblems.Erdos251.digit_eq_two_or_neg_two_of_small_pair
#print axioms ErdosProblems.Erdos251.shift_gt_half_of_digit_eq_two
#print axioms ErdosProblems.Erdos251.shift_lt_neg_half_of_digit_eq_neg_two
#print axioms ErdosProblems.Erdos251.evenIntegral_succ
#print axioms ErdosProblems.Erdos251.affinePowTwo_of_evenIntegral
#print axioms ErdosProblems.Erdos251.not_eventuallyIntegralTailShift_of_cofinal_affinePowTwo_escape
#print axioms ErdosProblems.Erdos257.EndpointDivisorSignal.card_divisors_Icc_odd
#print axioms ErdosProblems.Erdos257.EndpointDivisorSignal.card_divisors_Icc_even
#print axioms ErdosProblems.Erdos257.EndpointDivisorSignal.endpointPulse_eq_divisorSignal
#print axioms ErdosProblems.Erdos257.EndpointDivisorSignal.endpointDivisorSignal_unbounded_on_factorial_ray
#print axioms ErdosProblems.Erdos269.HalfHeightDenominatorTransport.dvd_carry_iff_dvd_height
#print axioms ErdosProblems.Erdos269.HalfHeightDenominatorTransport.exists_reducedCarry_isCoprime
#print axioms ErdosProblems.Erdos269.HalfHeightDenominatorTransport.no_reduced_state_of_large_or_nonunit_residue
#print axioms ErdosProblems.Erdos269.HalfHeightDenominatorTransport.reducedCarry_projective_shadow
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.four_mul_sqrt_sub_lt_two_mul
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.cassini_nine_tenths_slack
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.cassini_nine_tenths_forces_attachment_overhead
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.cassini_nine_tenths_falsifies_tree_budget
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.cassini_falsifies_tree_budget
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.newtonFlow_real_value_hasDerivAt
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.newtonFlow_real_scaledValue_eq
#print axioms ErdosProblems.Erdos1041.CassiniTreeBudget.newtonFlow_real_samePositiveRay
#print axioms ErdosProblems.Erdos68.BinaryCarryNormalForm.residualCentre_two_ne_canonicalRemainder
#print axioms ErdosProblems.Erdos68.BinaryCarryNormalForm.fract_eq_tail_sub_gap_add_binary_wrap
#print axioms ErdosProblems.Erdos68.BinaryCarryNormalForm.binary_coboundary_of_bridge
#print axioms ErdosProblems.Erdos68.BinaryCarryNormalForm.digitSum_mem_four_symbol_alphabet
#print axioms ErdosProblems.Erdos68.BinaryCarryNormalForm.binary_coboundary_telescope

/-! ## Residual wave (2026-08-19): collapse, peeling, cocycle, feedback -/

#print axioms ErdosProblems.Erdos251.evenIntegral_of_affinePowTwo
#print axioms ErdosProblems.Erdos251.ratAffinePowTwo_iff_evenIntegral
#print axioms ErdosProblems.Erdos251.ratAffinePowTwo_depth_independent
#print axioms ErdosProblems.Erdos251.affinePowTwo_succ_iff_orderOf_dvd
#print axioms ErdosProblems.Erdos251.cofinal_affinePowTwo_escape_iff_not_eventuallyIntegral
#print axioms ErdosProblems.Erdos251.not_eventuallyIntegral_of_cofinal_blockResidue_escape
#print axioms ErdosProblems.Erdos68.factorial_pow_dvd_factorial_of_mul_le
#print axioms ErdosProblems.Erdos68.factorial_mul_series_eq_peeledHead_add_centre_add_scaledTail
#print axioms ErdosProblems.Erdos68.signedCentreTailError_eq_zero_iff_exists_int
#print axioms ErdosProblems.Erdos68.not_irrational_iff_exists_signedCentreTailError_eq_zero
#print axioms ErdosProblems.Erdos68.signedCentreTailError_recurrence
#print axioms ErdosProblems.Erdos68.not_irrational_iff_eventually_centreDefectCode_eq_one
#print axioms ErdosProblems.Erdos68.one_div_succ_lt_factorialGapScaledTail
#print axioms ErdosProblems.Erdos257.affine_cocycle_tsum_eq_neg_anchor
#print axioms ErdosProblems.Erdos257.no_tempered_orbit_of_irrational_forcing
#print axioms ErdosProblems.Erdos257.tsum_endpointPulseTerm_eq_erdosBorwein
#print axioms ErdosProblems.Erdos257.irrational_tsum_endpointPulseTerm
#print axioms ErdosProblems.Erdos257.irrational_tsum_correction_of_tempered_branch
#print axioms ErdosProblems.Erdos243.negativeFeedback_squareDivision
#print axioms ErdosProblems.Erdos243.negativeFeedback_centeredQuotient
#print axioms ErdosProblems.Erdos243.centeredQuotient_window
#print axioms ErdosProblems.Erdos243.negativeFeedback_normalizedDescent_counterexample
#print axioms ErdosProblems.Erdos243.exists_divisor_between
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.affineDiagonalKillSupply_iff_irrational
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.progressionDiagonalKillSupply_iff_irrational
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.factorialDiagonalKillSupply_iff_irrational
#print axioms Erdos257PeriodNoncollapse.TotientTailPeriodKiller.no_certifiedKill_of_large_prime_annihilator
#print axioms ErdosProblems.Erdos1041.two_add_le_two_of_bernoulli
#print axioms ErdosProblems.Erdos1041.exists_two_roots_dist_sum_le_two_mul_geomMean
#print axioms ErdosProblems.Erdos1041.spoke_escapes_lemniscate_exact
#print axioms ErdosProblems.Erdos1041.normalizedCubic_spoke_identity
#print axioms ErdosProblems.Erdos1041.cubicSpoke_envelope_le_one
#print axioms ErdosProblems.Erdos1041.normalizedCubic_spoke_norm_le_one
#print axioms ErdosProblems.Erdos1041.two_small_normalized_roots_give_short_hub
#print axioms ErdosProblems.Erdos1041.normalizedCubic_two_small_roots_fan_in
#print axioms ErdosProblems.Erdos1049.det_southeastBlock_dvd
#print axioms ErdosProblems.Erdos1049.det_diagonal_mul_mul_diagonal
#print axioms ErdosProblems.Erdos1049.fixedDiagonalRationalClearingExponent_pos
#print axioms ErdosProblems.Erdos1049.fixedDiagonalSourceBalance_pos
#print axioms ErdosProblems.Erdos1049.movingDiagonalRationalClearingMainTerm_pos
#print axioms ErdosProblems.Erdos1049.movingDiagonalRatioExponent_pos
#print axioms ErdosProblems.Erdos1049.commonDivisor_dvd_adjacentSecondKindNumerator
#print axioms ErdosProblems.Erdos1049.not_tendsto_zero_of_eventually_one_le_abs
#print axioms ErdosProblems.Erdos1049.zmod_binary_collision_of_zero_denominator_coordinates
#print axioms ErdosProblems.Erdos1049.integerLinearFormNumerator_ne_zero_of_prime_support
#print axioms ErdosProblems.Erdos1049.rational_integerLinearForm_ne_zero_of_prime_support
#print axioms ErdosProblems.Erdos1049.rational_integerLinearForm_gap_of_prime_support
#print axioms ErdosProblems.Erdos1049.twoSelector_one_numerator_not_dvd_of_prime_tail_support
#print axioms ErdosProblems.Erdos1049.rational_twoSelector_gap_of_prime_tail_support
#print axioms ErdosProblems.Erdos269.List.prod_eq_one_add_suffixCorrection
#print axioms ErdosProblems.Erdos269.tailCap_bellman
#print axioms ErdosProblems.Erdos269.tailCap_step_of_shellMass
#print axioms ErdosProblems.Erdos269.tailCap_step_compose
