import ErdosProblems.Erdos249.FiniteEulerSieve
import ErdosProblems.Erdos249.PrimeRayCyclotomicCurvature
import ErdosProblems.Erdos249.CyclotomicAnchoredKill
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos249.RankOneSubrankObstruction
import ErdosProblems.Erdos249.TotientStrictPrimeEscape
import ErdosProblems.Erdos257.HalfCounterexampleFrontier
import ErdosProblems.Erdos257.MersenneSubseriesRigidity
import ErdosProblems.Erdos257.SquarefreeSupportIncidence
import ErdosProblems.Erdos243.ReciprocalTailRigidity
import ErdosProblems.Erdos243.FiniteHorizonResidue
import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos243.SparseResetRecovery
import ErdosProblems.Erdos251.PrimeGapDyadicTail
import ErdosProblems.Erdos269.ThreePrimeRunningLcm
import ErdosProblems.Erdos269.ResidueEscape
import ErdosProblems.Erdos269.RestrictedFloorSum
import ErdosProblems.Erdos1049.RationalBaseLambert
import ErdosProblems.Erdos1049.RationalPadeArithmetic
import ErdosProblems.Erdos1049.ZudilinConeArithmetic

/-!
# Problem-centric Erdős formalization root

This root is intentionally separate from the historical `Erdos249257`
namespace. New research is grouped by the actual problem and mathematical
object without forcing a repository-wide rename.
-/
