import ErdosProblems.Erdos243.ReciprocalTailRigidity
import ErdosProblems.Erdos243.FiniteHorizonResidue
import ErdosProblems.Erdos243.DynamicCancellation
import ErdosProblems.Erdos243.WeightedCRTRepair
import ErdosProblems.Erdos243.SparseResetRecovery
import ErdosProblems.Erdos243.CleanRecoveryLengthCounterexample
import ErdosProblems.Erdos243.LcmCriticalBoundary
import ErdosProblems.Erdos243.PrimitivePrefixRigidity
import ErdosProblems.Erdos243.FeedbackRealizability
import ErdosProblems.Erdos243.GlobalLcmHeight
import ErdosProblems.Erdos68.FactorialChannelCertificate
import ErdosProblems.Erdos68.ChannelIntegralCongruence
import ErdosProblems.Erdos68.PrimeUnitTranslator
import ErdosProblems.Erdos68.EndpointWeightedPrivateSupport
import ErdosProblems.Erdos68.FactorialZeroPlateau
import ErdosProblems.Erdos68.GapScalarNormalForm
import ErdosProblems.Erdos68.CarryCongruenceNormalForm
import ErdosProblems.Erdos68.CompanionConstantBridge
import ErdosProblems.Erdos68.ConstantOnlyMissCertificates
import ErdosProblems.Erdos68.DivisorFactorialCentre
import ErdosProblems.Erdos68.FactorialDigitRigidity
import ErdosProblems.Erdos249.TotientStrictPrimeEscape
import ErdosProblems.Erdos249.FiniteEulerSieve
import ErdosProblems.Erdos249.PrimeRayCyclotomicCurvature
import ErdosProblems.Erdos249.CyclotomicAnchoredKill
import ErdosProblems.Erdos249.RankOneSubrankObstruction
import ErdosProblems.Erdos249.RankOneSharpFloor
import ErdosProblems.Erdos249.PeriodMultipleEscape
import ErdosProblems.Erdos251.PrimeGapDyadicTail
import ErdosProblems.Erdos257.MersenneSubseriesRigidity
import ErdosProblems.Erdos257.HalfCounterexampleFrontier
import ErdosProblems.Erdos257.BatchReturnSynthesis
import ErdosProblems.Erdos269.ThreePrimeRunningLcm
import ErdosProblems.Erdos269.ResidueEscape
import ErdosProblems.Erdos269.BoundedRadixTailEscape
import ErdosProblems.Erdos269.DyadicRadixTailEscape
import ErdosProblems.Erdos269.WeightedPhaseCarry
import ErdosProblems.Erdos269.CarryLiftExtinction
import ErdosProblems.Erdos1049.RationalBaseLambert
import ErdosProblems.Erdos1049.RationalPadeArithmetic
import ErdosProblems.Erdos1049.ZudilinHeightRegion
import ErdosProblems.Erdos1049.HermitePadeNoGo
import ErdosProblems.Erdos1049.ZudilinConeArithmetic
import ErdosProblems.Erdos1041.NewtonFlowRaySeparation
import ErdosProblems.Shared.IrrationalRotationStaircase
import ErdosProblems.Erdos269.KernelCarryRank
import ErdosProblems.Erdos68.ShrinkingTargetNormalForm
import ErdosProblems.Erdos243.RepairEntropy
import ErdosProblems.Erdos1049.AdelicHeightBridge
import ErdosProblems.Erdos251.OrderLatticeDiagonal
import ErdosProblems.Erdos1041.LevelSeparation
import ErdosProblems.Erdos249.FullDepthRayAmplifier
import ErdosProblems.Erdos1049.BezoutPluckerJets
import ErdosProblems.Erdos1049.TwoSelectorRemainderEscape
import ErdosProblems.Erdos1049.QAperyTailDenominator
import ErdosProblems.Erdos243.OrientedFeedbackRoot
import ErdosProblems.Erdos243.HorizonEscapeOfMass
import ErdosProblems.Erdos251.AffineShiftEscape
import ErdosProblems.Erdos257.EndpointDivisorSignal
import ErdosProblems.Erdos269.HalfHeightDenominatorTransport
import ErdosProblems.Erdos1041.CassiniTreeBudget
import ErdosProblems.Erdos1041.CubicCriticalHub
import ErdosProblems.Erdos1041.NearFeketeHubOrbit
import ErdosProblems.Erdos68.BinaryCarryNormalForm
import ErdosProblems.Erdos251.AffineCylinderCollapse
import ErdosProblems.Erdos68.HyperbolicPeeling
import ErdosProblems.Erdos68.SecondLayerDigit
import ErdosProblems.Erdos68.PrimePoleCriterion
import ErdosProblems.Erdos68.PrimeThresholdParity
import ErdosProblems.Erdos68.RunCylinder
import ErdosProblems.Erdos68.AffineDefectRigidity
import ErdosProblems.Erdos257.AffineCocycleObstruction
import ErdosProblems.Erdos243.CenteredEuclideanFeedback
import ErdosProblems.Erdos1041.CriticalTwoRootProximity
import ErdosProblems.Erdos1041.BarycentricEnvelope
import ErdosProblems.Erdos1041.BarycentricTargetDisc
import ErdosProblems.Erdos1041.ConnectedClusterAreaForcing
import ErdosProblems.Erdos1041.CriticalEllipseMinimaxStationarity
import ErdosProblems.Erdos1041.GenericSufficiencyClosure
import ErdosProblems.Erdos1049.SoutheastBlockDeterminant
import ErdosProblems.Erdos1049.FixedDiagonalRationalClearing
import ErdosProblems.Erdos269.BlockMassEngines
import ErdosProblems.Erdos269.DyadicOrderedTailRecurrence
import ErdosProblems.Erdos269.DyadicShellSummability

/-!
# Problem-centric Erdős formalization root

This root is intentionally separate from the legacy
`Erdos257PeriodNoncollapse` namespace.  New research is grouped by the actual
problem and mathematical object; compatibility imports can be added later
without forcing a repository-wide rename.
-/
