#!/usr/bin/env python3
"""Write the argument frontier: the graph's findings about paper results, as Lean.

Reads the argument graph (``docs/argument_continuations_graph.json.gz``, built by
``scripts/build_argument_continuations.py``) and the paper-to-Lean ledger
(``docs/paper_lean_coverage.json``), and writes, for each problem, a Lean module
``lean/ErdosProblems/ArgumentGraph/Derived/<Problem>.lean`` whose commands
rebuild, for every theorem a paper cites:

* ``derive_idle T`` when the export's kernel check found hypotheses its proof
  never uses (``T.idle``);
* ``derive_weakening T`` and ``derive_frontier T`` when the proof uses a
  hypothesis only through consequences (``T.weakened_i``, ``T.frontier_i``),
  with ``derive_frontier T at L`` for each theorem ``L`` on the chain at which
  every branch of the chain can stop on one statement.

The commands are defined in ``lean/ErdosProblems/ArgumentGraph/Derive.lean``;
each theorem they add is checked by the kernel when the module is compiled, and
the generated modules set ``argumentGraph.strict`` so a derivation the export
reported but the library cannot rebuild fails the build. The module list is
also written to ``docs/argument_frontier.json`` with, per derived theorem, the
paper rows of its source theorem and the statements the graph recorded for it.

Usage:
    python3 scripts/build_argument_frontier.py [--graph PATH] [--root PATH] [--check]

``--check`` compares the files on disk with what would be written and exits 1
when they differ.
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DERIVED = Path("lean/ErdosProblems/ArgumentGraph/Derived")
DERIVE_MODULE = "ErdosProblems.ArgumentGraph.Derive"
PROBLEM_NAMES = {"68": "Erdos68", "243": "Erdos243", "249": "Erdos249", "251": "Erdos251",
                 "257": "Erdos257", "269": "Erdos269", "1041": "Erdos1041", "1049": "Erdos1049"}
HEADER = """-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision {revision} (Lean tree {tree}). Do not edit by hand.
"""


def load_graph(path: Path) -> dict[str, Any]:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def paper_rows(root: Path) -> dict[str, list[dict[str, Any]]]:
    ledger = json.loads((root / "docs" / "paper_lean_coverage.json").read_text(encoding="utf-8"))
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in ledger.get("rows", []):
        for declaration in (row.get("lean") or {}).get("declarations", []) or []:
            if declaration.get("name"):
                out[declaration["name"]].append({
                    "row": row.get("id"), "label": row.get("label"), "paper": row.get("paper_id"),
                    "side": row.get("side"), "lean_status": (row.get("lean") or {}).get("status"),
                    "source": row.get("source")})
    return out


def lean_ident(name: str) -> str:
    """A declaration name as Lean source: components that are not plain
    identifiers are escaped with guillemets."""
    parts = []
    for part in name.split("."):
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_'!?₀-₉]*", part):
            parts.append(part)
        else:
            parts.append(f"«{part}»")
    return ".".join(parts)


def weakening_index(graph: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    """The graph's weakenings by theorem. The builder keeps only the rows the
    export marked kernel-checked, so every row here is one; a row that still
    carries ``kernel_checked: false`` (an older payload) is skipped."""
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in graph.get("weakenings", []) or []:
        if row.get("kernel_checked", True) and row.get("theorem"):
            out[row["theorem"]].append(row)
    return out


def chain_cuts(theorem: str, weakenings: dict[str, list[dict[str, Any]]]) -> list[str]:
    """Theorems on the weakening chain below ``theorem`` at which every branch
    stops on one statement: the candidates for ``derive_frontier … at L``.
    Planned over the graph's rows; the Lean command is the authority on what
    the cut proves."""
    def heads(name: str) -> list[list[str]]:
        rows = weakenings.get(name, [])
        if len(rows) != 1:
            return []
        return [[v for v in (c.get("via") or []) if v in weakenings] for c in rows[0].get("consequences", [])]

    def leaves(name: str, stop: str, depth: int = 0) -> set[str] | None:
        if depth > 24:
            return None
        out: set[str] = set()
        for vias in heads(name):
            if len(vias) != 1:
                out.add(f"{name}:site")
                continue
            head = vias[0]
            if head == stop:
                out.add(head)
            else:
                deeper = leaves(head, stop, depth + 1)
                if deeper is None:
                    return None
                out |= deeper or {head}
        return out

    seen: list[str] = []
    frontier = [theorem]
    while frontier:
        nxt = []
        for name in frontier:
            for vias in heads(name):
                for v in vias:
                    if v not in seen and v != theorem:
                        seen.append(v)
                        nxt.append(v)
        frontier = nxt
    return [head for head in seen if leaves(theorem, head) == {head}]


def plan(graph: dict[str, Any], papers: dict[str, list[dict[str, Any]]]) -> dict[str, Any]:
    theorems = {t["name"]: t for t in graph.get("theorems", [])}
    statements = {s["key"]: s for s in graph.get("statements", [])}
    weakenings = weakening_index(graph)
    per_problem: dict[str, dict[str, Any]] = defaultdict(
        lambda: {"imports": set(), "commands": [], "supplied_commands": [], "rows": []})
    for row in graph.get("idle", []) or []:
        name = row["theorem"]
        if name not in papers or name not in theorems:
            continue
        theorem = theorems[name]
        problem = PROBLEM_NAMES.get(str(theorem.get("problem")))
        if not problem:
            continue
        slot = per_problem[problem]
        slot["imports"].add(theorem["module"])
        slot["commands"].append(f"derive_idle {lean_ident(name)}")
        slot["rows"].append({"operation": "idle", "theorem": name, "derived": [f"{name}.idle"],
                             "dropped": [d.get("type") for d in row.get("dropped", [])],
                             "statement": row.get("type"), "papers": papers[name],
                             "source": theorem.get("source")})
    for name, rows in sorted(weakenings.items()):
        if name not in papers or name not in theorems:
            continue
        theorem = theorems[name]
        problem = PROBLEM_NAMES.get(str(theorem.get("problem")))
        if not problem:
            continue
        slot = per_problem[problem]
        slot["imports"].add(theorem["module"])
        for via_row in rows:
            for c in via_row.get("consequences", []):
                for v in c.get("via") or []:
                    if v in theorems:
                        slot["imports"].add(theorems[v]["module"])
        slot["commands"].append(f"derive_weakening {lean_ident(name)}")
        slot["commands"].append(f"derive_frontier {lean_ident(name)}")
        cuts = chain_cuts(name, weakenings)
        for cut in cuts:
            slot["commands"].append(f"derive_frontier {lean_ident(name)} at {lean_ident(cut)}")
        suppliers = chain_suppliers(name, weakenings, statements, theorems)
        if suppliers:
            for s in suppliers:
                slot["imports"].add(theorems[s]["module"])
            using = " ".join(lean_ident(s) for s in suppliers)
            # A supplied consequence the graph records need not sit where the Lean
            # chain stops, so these commands only warn when they discharge nothing.
            slot["supplied_commands"].append(f"derive_frontier {lean_ident(name)} using {using}")
            for cut in cuts:
                slot["supplied_commands"].append(
                    f"derive_frontier {lean_ident(name)} at {lean_ident(cut)} using {using}")
        slot["rows"].append({
            "operation": "weakening", "theorem": name, "papers": papers[name], "source": theorem.get("source"),
            "hypotheses": [{"i": r.get("i"), "hypothesis": r.get("hypothesis_type") or r.get("hypothesis"),
                            "consequences": [{"type": c.get("type"), "via": c.get("via")}
                                             for c in r.get("consequences", [])]} for r in rows],
            "frontier_cuts": cuts, "suppliers": suppliers})
    return per_problem


def chain_suppliers(theorem: str, weakenings: dict[str, list[dict[str, Any]]],
                    statements: dict[str, dict[str, Any]], theorems: dict[str, dict[str, Any]]) -> list[str]:
    """Corpus theorems the graph records as witnesses of a consequence anywhere on
    the weakening chain below ``theorem``: the candidates for
    ``derive_frontier … using``. Battery witnesses (tactics) are not constants and
    are left out."""
    out: list[str] = []
    seen: set[str] = set()
    frontier = [theorem]
    while frontier:
        nxt: list[str] = []
        for name in frontier:
            if name in seen:
                continue
            seen.add(name)
            for row in weakenings.get(name, []):
                for c in row.get("consequences", []):
                    statement = statements.get(c.get("key") or "") or {}
                    witness = statement.get("witness")
                    if statement.get("status") == "supplied" and isinstance(witness, str) \
                            and witness in theorems and witness not in out:
                        out.append(witness)
                    nxt += [v for v in c.get("via") or [] if v in weakenings]
        frontier = nxt
    return out


def named_inputs(graph: dict[str, Any], papers: dict[str, list[dict[str, Any]]],
                 weakenings: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """Every open closed hypothesis of a theorem a paper cites, with what each
    proof consumes of it. A consumer's ``levels`` list the use-site
    consequences of the hypothesis, then the consequences of the theorems
    those sites apply it to, and so on (a site continues the chain when the
    theorem it applies has a weakening of the same hypothesis). Each
    consequence carries the graph's status for it, so an open input whose
    deeper level is supplied is visible at a glance."""
    statements = {s["key"]: s for s in graph.get("statements", [])}
    theorems = {t["name"]: t for t in graph.get("theorems", [])}

    def rows_for(theorem: str, hypothesis: str) -> list[dict[str, Any]]:
        return [r for r in weakenings.get(theorem, []) if r.get("hypothesis") == hypothesis]

    def levels(theorem: str, hypothesis: str) -> list[list[dict[str, Any]]]:
        out: list[list[dict[str, Any]]] = []
        seen: set[str] = set()
        frontier = [theorem]
        visited: set[str] = set()
        while frontier and len(out) < 24:
            level: list[dict[str, Any]] = []
            nxt: list[str] = []
            for name in frontier:
                if name in visited:
                    continue
                visited.add(name)
                for row in rows_for(name, hypothesis):
                    for c in row.get("consequences", []):
                        key = c.get("key")
                        if key and key not in seen:
                            seen.add(key)
                            level.append({"type": c.get("type"), "key": key, "via": c.get("via", []),
                                          "status": (statements.get(key) or {}).get("status")})
                        for v in c.get("via") or []:
                            if rows_for(v, hypothesis):
                                nxt.append(v)
            if level:
                out.append(level)
            frontier = nxt
        return out

    by_input: dict[str, dict[str, Any]] = {}
    for name in sorted(papers):
        theorem = theorems.get(name)
        if not theorem:
            continue
        for key in theorem.get("hypotheses", []) or []:
            statement = statements.get(key)
            if not statement or statement.get("status") != "open":
                continue
            entry = by_input.setdefault(key, {"key": key, "statement": statement.get("type"), "consumers": []})
            entry["consumers"].append({
                "theorem": name, "problem": theorem.get("problem"),
                "papers": [{"row": p["row"], "label": p["label"], "lean_status": p["lean_status"]}
                           for p in papers[name]],
                "levels": levels(name, key)})
    return sorted(by_input.values(), key=lambda e: (-len(e["consumers"]), e["statement"] or ""))


def clip(text: str | None, limit: int = 220) -> str:
    flat = " ".join((text or "").split())
    return flat if len(flat) <= limit else flat[: limit - 1] + "…"


def render_markdown(manifest: dict[str, Any]) -> str:
    """The frontier for readers: per problem, the named inputs its paper
    results assume with what their proofs use of them, and the theorems the
    library derives. Statements are clipped; the JSON has them whole."""
    source = manifest["source"]
    out = ["# The argument frontier", "",
           f"Generated by `scripts/build_argument_frontier.py` from the argument graph of source revision "
           f"`{(source.get('source_revision') or '?')[:12]}`. The Lean modules it names are compiled with "
           "`argumentGraph.strict`, so every derived theorem listed here is checked by the kernel when they "
           "compile. `docs/argument_frontier.json` holds the same rows in full.", ""]
    inputs_by_problem: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in manifest.get("named_inputs", []):
        for problem in sorted({str(c.get("problem")) for c in entry["consumers"]}):
            inputs_by_problem[problem].append(entry)
    problems = sorted(set(PROBLEM_NAMES) & (set(inputs_by_problem) | {k.removeprefix("Erdos") for k in manifest["rows"]}),
                      key=int)
    for problem in problems:
        out += [f"## Erdős #{problem}", ""]
        entries = inputs_by_problem.get(problem, [])
        if entries:
            out += ["### Named inputs the paper results assume", ""]
            for entry in entries:
                consumers = [c for c in entry["consumers"] if str(c.get("problem")) == problem]
                labels = sorted({p["label"] for c in consumers for p in c["papers"] if p.get("label")})
                out.append(f"- `{clip(entry['statement'], 160)}`: assumed by {len(consumers)} cited "
                           f"theorem(s) ({', '.join(labels[:6])}{', …' if len(labels) > 6 else ''}).")
                for consumer in consumers:
                    for depth, level in enumerate(consumer.get("levels", []), start=1):
                        statuses = ", ".join(f"`{clip(c['type'], 140)}` ({c.get('status')})" for c in level[:3])
                        more = f" and {len(level) - 3} more" if len(level) > 3 else ""
                        out.append(f"  - `{consumer['theorem'].rsplit('.', 1)[-1]}`, level {depth}: "
                                   f"uses it only through {statuses}{more}")
            out.append("")
        rows = manifest["rows"].get(PROBLEM_NAMES[problem], [])
        idle = [r for r in rows if r["operation"] == "idle"]
        weak = [r for r in rows if r["operation"] == "weakening"]
        if idle or weak:
            out += [f"### Derived theorems (`{manifest['modules'][PROBLEM_NAMES[problem]]}`)", ""]
            for r in idle:
                labels = ", ".join(sorted({p["label"] for p in r["papers"] if p.get("label")}))
                out.append(f"- `{r['theorem'].rsplit('.', 1)[-1]}.idle` ({labels}): the statement without "
                           f"{'; '.join('`' + clip(d, 100) + '`' for d in r['dropped'])}, which the proof "
                           "never uses.")
            for r in weak:
                labels = ", ".join(sorted({p["label"] for p in r["papers"] if p.get("label")}))
                cuts = ", ".join(f"`{c.rsplit('.', 1)[-1]}`" for c in r.get("frontier_cuts", []))
                out.append(f"- `{r['theorem'].rsplit('.', 1)[-1]}` ({labels}): `weakened_i` and `frontier_i`"
                           + (f", and frontiers cut at {cuts}" if cuts else "") + ".")
            out.append("")
    return "\n".join(out)


def render_module(problem: str, slot: dict[str, Any], source: dict[str, Any]) -> str:
    lines = [HEADER.format(revision=source.get("source_revision", "?"), tree=source.get("lean_tree", "?"))]
    lines.append(f"import {DERIVE_MODULE}")
    lines += [f"import {m}" for m in sorted(slot["imports"])]
    lines.append("")
    lines.append(f"/-! # {problem}: theorems derived from what the paper results' proofs use")
    lines.append("")
    lines.append("Each command below rebuilds, as a library theorem the kernel checks, a finding of")
    lines.append("the argument graph about a theorem the papers cite. See")
    lines.append("`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/")
    lines.append("")
    lines.append("set_option argumentGraph.strict true")
    lines.append("set_option maxHeartbeats 4000000")
    lines.append("")
    lines += slot["commands"]
    if slot.get("supplied_commands"):
        lines.append("")
        lines.append("-- Frontiers with the consequences the graph records as proved by corpus theorems")
        lines.append("-- discharged. Where the Lean chain stops elsewhere, a command adds nothing and warns.")
        lines += [f"set_option argumentGraph.strict false in {c}" for c in slot["supplied_commands"]]
    lines.append("")
    return "\n".join(lines)


WORKFLOW = Path(".github/workflows/lean-coverage-build.yml")
STEP_ID = "id: coverage-build"


def with_workflow_modules(text: str, modules: list[str]) -> str:
    """The coverage workflow with the argument-frontier modules in the
    coverage-build step replaced by ``modules``. The step lists one target per
    line after its ``--lake-staleness`` line; the frontier modules come last,
    and every other target is kept as it is."""
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == STEP_ID)
        flag = next(i for i in range(start, len(lines)) if "--lake-staleness" in lines[i])
    except StopIteration:
        raise SystemExit(f"{WORKFLOW}: no step with {STEP_ID} and a --lake-staleness line") from None
    end = flag + 1
    while end < len(lines) and re.match(r"^\s+(ErdosProblems|Erdos249257)\.", lines[end]):
        end += 1
    indent = re.match(r"^(\s*)", lines[flag]).group(1)
    kept = [l for l in lines[flag + 1:end] if ".ArgumentGraph." not in l]
    return "\n".join(lines[: flag + 1] + kept + [indent + m for m in modules] + lines[end:]) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--graph", type=Path, default=ROOT / "docs" / "argument_continuations_graph.json.gz")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    graph = load_graph(args.graph)
    papers = paper_rows(args.root)
    per_problem = plan(graph, papers)
    source = graph.get("source", {})
    files: dict[Path, str] = {}
    for problem, slot in sorted(per_problem.items()):
        files[args.root / DERIVED / f"{problem}.lean"] = render_module(problem, slot, source)
    manifest = {
        "schema": "plectis-argument-frontier/1",
        "source": {k: source.get(k) for k in ("source_revision", "lean_tree", "export_digest")},
        "rule": ("every row names a theorem a paper cites and a derivation the export's kernel check "
                 "reported; the generated module rebuilds it and the kernel checks it when the module "
                 "compiles (argumentGraph.strict makes a failed rebuild a build error)"),
        "modules": {problem: str(DERIVED / f"{problem}.lean") for problem in sorted(per_problem)},
        "rows": {problem: slot["rows"] for problem, slot in sorted(per_problem.items())},
        "named_inputs_rule": ("an open closed hypothesis of a theorem a paper cites; levels are what the "
                              "proofs consume of it, from the kernel-checked weakenings"),
        "named_inputs": named_inputs(graph, papers, weakening_index(graph)),
    }
    files[args.root / "docs" / "argument_frontier.json"] = json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"
    files[args.root / "docs" / "ARGUMENT_FRONTIER.md"] = render_markdown(manifest) + "\n"
    workflow = args.root / WORKFLOW
    if workflow.exists():
        modules = sorted(f"ErdosProblems.ArgumentGraph.Derived.{p}" for p in per_problem)
        files[workflow] = with_workflow_modules(workflow.read_text(encoding="utf-8"), modules)
    if args.check:
        stale = [str(p) for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print("stale:\n  " + "\n  ".join(stale))
            return 1
        print(f"ok: argument frontier current ({sum(1 for p in files if p.suffix == '.lean')} modules)")
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    counts = {p: {"commands": len(s["commands"]), "rows": len(s["rows"])} for p, s in sorted(per_problem.items())}
    print(json.dumps(counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
