#!/usr/bin/env python3
"""Write the argument frontier: the graph's findings about paper results, as Lean.

Reads the argument graph (``docs/argument_continuations_graph.json.gz``, built by
``scripts/build_argument_continuations.py``) and the paper-to-Lean ledger
(``docs/paper_lean_coverage.json``), and writes, for each problem, a Lean module
``lean/ErdosProblems/ArgumentGraph/Derived/<Problem>.lean`` whose commands
rebuild, for every theorem a paper cites:

* ``derive_idle T`` when the export's kernel check found hypotheses its proof
  never uses (``T.idle``);
* ``derive_weakening T`` and ``derive_frontier T`` when the proof uses a
  hypothesis only through consequences (``T.weakened_i``, ``T.frontier_i``),
  with ``derive_frontier T at L`` for each theorem ``L`` on the chain at which
  every branch of the chain can stop on one statement.

The commands are defined in ``lean/ErdosProblems/ArgumentGraph/Derive.lean``;
each theorem they add is checked by the kernel when the module is compiled, and
the generated modules set ``argumentGraph.strict`` so a derivation the export
reported but the library cannot rebuild fails the build. The module list is
also written to ``docs/argument_frontier.json`` with, per derived theorem, the
paper rows of its source theorem and the statements the graph recorded for it.

Usage:
    python3 scripts/build_argument_frontier.py [--graph PATH] [--root PATH] [--check]

``--check`` compares the files on disk with what would be written and exits 1
when they differ.
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DERIVED = Path("lean/ErdosProblems/ArgumentGraph/Derived")
DERIVE_MODULE = "ErdosProblems.ArgumentGraph.Derive"
PROBLEM_NAMES = {"68": "Erdos68", "243": "Erdos243", "249": "Erdos249", "251": "Erdos251",
                 "257": "Erdos257", "269": "Erdos269", "1041": "Erdos1041", "1049": "Erdos1049"}
HEADER = """-- SPDX-FileCopyrightText: 2026 Will Cook
-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/build_argument_frontier.py from the argument graph of
-- source revision {revision} (Lean tree {tree}). Do not edit by hand.
"""


def load_graph(path: Path) -> dict[str, Any]:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def paper_rows(root: Path) -> dict[str, list[dict[str, Any]]]:
    ledger = json.loads((root / "docs" / "paper_lean_coverage.json").read_text(encoding="utf-8"))
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in ledger.get("rows", []):
        for declaration in (row.get("lean") or {}).get("declarations", []) or []:
            if declaration.get("name"):
                out[declaration["name"]].append({
                    "row": row.get("id"), "label": row.get("label"), "paper": row.get("paper_id"),
                    "side": row.get("side"), "lean_status": (row.get("lean") or {}).get("status"),
                    "source": row.get("source")})
    return out


def lean_ident(name: str) -> str:
    """A declaration name as Lean source: components that are not plain
    identifiers are escaped with guillemets."""
    parts = []
    for part in name.split("."):
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_'!?₀-₉]*", part):
            parts.append(part)
        else:
            parts.append(f"«{part}»")
    return ".".join(parts)


def weakening_index(graph: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in graph.get("weakenings", []) or []:
        if row.get("kernel_checked"):
            out[row["theorem"]].append(row)
    return out


def chain_cuts(theorem: str, weakenings: dict[str, list[dict[str, Any]]]) -> list[str]:
    """Theorems on the weakening chain below ``theorem`` at which every branch
    stops on one statement: the candidates for ``derive_frontier … at L``.
    Planned over the graph's rows; the Lean command is the authority on what
    the cut proves."""
    def heads(name: str) -> list[list[str]]:
        rows = weakenings.get(name, [])
        if len(rows) != 1:
            return []
        return [[v for v in (c.get("via") or []) if v in weakenings] for c in rows[0].get("consequences", [])]

    def leaves(name: str, stop: str, depth: int = 0) -> set[str] | None:
        if depth > 24:
            return None
        out: set[str] = set()
        for vias in heads(name):
            if len(vias) != 1:
                out.add(f"{name}:site")
                continue
            head = vias[0]
            if head == stop:
                out.add(head)
            else:
                deeper = leaves(head, stop, depth + 1)
                if deeper is None:
                    return None
                out |= deeper or {head}
        return out

    seen: list[str] = []
    frontier = [theorem]
    while frontier:
        nxt = []
        for name in frontier:
            for vias in heads(name):
                for v in vias:
                    if v not in seen and v != theorem:
                        seen.append(v)
                        nxt.append(v)
        frontier = nxt
    return [head for head in seen if leaves(theorem, head) == {head}]


def plan(graph: dict[str, Any], papers: dict[str, list[dict[str, Any]]]) -> dict[str, Any]:
    theorems = {t["name"]: t for t in graph.get("theorems", [])}
    weakenings = weakening_index(graph)
    per_problem: dict[str, dict[str, Any]] = defaultdict(lambda: {"imports": set(), "commands": [], "rows": []})
    for row in graph.get("idle", []) or []:
        name = row["theorem"]
        if name not in papers or name not in theorems:
            continue
        theorem = theorems[name]
        problem = PROBLEM_NAMES.get(str(theorem.get("problem")))
        if not problem:
            continue
        slot = per_problem[problem]
        slot["imports"].add(theorem["module"])
        slot["commands"].append(f"derive_idle {lean_ident(name)}")
        slot["rows"].append({"operation": "idle", "theorem": name, "derived": [f"{name}.idle"],
                             "dropped": [d.get("type") for d in row.get("dropped", [])],
                             "statement": row.get("type"), "papers": papers[name],
                             "source": theorem.get("source")})
    for name, rows in sorted(weakenings.items()):
        if name not in papers or name not in theorems:
            continue
        theorem = theorems[name]
        problem = PROBLEM_NAMES.get(str(theorem.get("problem")))
        if not problem:
            continue
        slot = per_problem[problem]
        slot["imports"].add(theorem["module"])
        for via_row in rows:
            for c in via_row.get("consequences", []):
                for v in c.get("via") or []:
                    if v in theorems:
                        slot["imports"].add(theorems[v]["module"])
        slot["commands"].append(f"derive_weakening {lean_ident(name)}")
        slot["commands"].append(f"derive_frontier {lean_ident(name)}")
        cuts = chain_cuts(name, weakenings)
        for cut in cuts:
            slot["commands"].append(f"derive_frontier {lean_ident(name)} at {lean_ident(cut)}")
        slot["rows"].append({
            "operation": "weakening", "theorem": name, "papers": papers[name], "source": theorem.get("source"),
            "hypotheses": [{"i": r.get("i"), "hypothesis": r.get("hypothesis_type") or r.get("hypothesis"),
                            "consequences": [{"type": c.get("type"), "via": c.get("via")}
                                             for c in r.get("consequences", [])]} for r in rows],
            "frontier_cuts": cuts})
    return per_problem


def render_module(problem: str, slot: dict[str, Any], source: dict[str, Any]) -> str:
    lines = [HEADER.format(revision=source.get("source_revision", "?"), tree=source.get("lean_tree", "?"))]
    lines.append(f"import {DERIVE_MODULE}")
    lines += [f"import {m}" for m in sorted(slot["imports"])]
    lines.append("")
    lines.append(f"/-! # {problem}: theorems derived from what the paper results' proofs use")
    lines.append("")
    lines.append("Each command below rebuilds, as a library theorem the kernel checks, a finding of")
    lines.append("the argument graph about a theorem the papers cite. See")
    lines.append("`ErdosProblems.ArgumentGraph.Derive` for what each command adds. -/")
    lines.append("")
    lines.append("set_option argumentGraph.strict true")
    lines.append("set_option maxHeartbeats 4000000")
    lines.append("")
    lines += slot["commands"]
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--graph", type=Path, default=ROOT / "docs" / "argument_continuations_graph.json.gz")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    graph = load_graph(args.graph)
    papers = paper_rows(args.root)
    per_problem = plan(graph, papers)
    source = graph.get("source", {})
    files: dict[Path, str] = {}
    for problem, slot in sorted(per_problem.items()):
        files[args.root / DERIVED / f"{problem}.lean"] = render_module(problem, slot, source)
    manifest = {
        "schema": "plectis-argument-frontier/1",
        "source": {k: source.get(k) for k in ("source_revision", "lean_tree", "export_digest")},
        "rule": ("every row names a theorem a paper cites and a derivation the export's kernel check "
                 "reported; the generated module rebuilds it and the kernel checks it when the module "
                 "compiles (argumentGraph.strict makes a failed rebuild a build error)"),
        "modules": {problem: str(DERIVED / f"{problem}.lean") for problem in sorted(per_problem)},
        "rows": {problem: slot["rows"] for problem, slot in sorted(per_problem.items())},
    }
    files[args.root / "docs" / "argument_frontier.json"] = json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"
    if args.check:
        stale = [str(p) for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print("stale:\n  " + "\n  ".join(stale))
            return 1
        print(f"ok: argument frontier current ({len(files) - 1} modules)")
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    counts = {p: {"commands": len(s["commands"]), "rows": len(s["rows"])} for p, s in sorted(per_problem.items())}
    print(json.dumps(counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
