#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Render a checked short-paper-audit/1 report and systems-paper count macros."""
from __future__ import annotations
import argparse
from collections import Counter
import json
from pathlib import Path
from short_paper_writer import digest, Refusal


def render(report: dict) -> tuple[str,str]:
    if report.get('schema')!='short-paper-audit/1':raise Refusal('schema','expected short-paper-audit/1')
    papers=report['papers'];counts=Counter(f['severity'] for p in papers for f in p['findings'])
    summary=dict(papers=len(papers),assertions=sum(len(p['assertions']) for p in papers),findings=dict(sorted(counts.items())))
    if report['summary']!=summary:raise Refusal('summary','does not equal the reported inventory')
    values={'PThreePapers':len(papers),'PThreeAssertions':summary['assertions'],
            'PThreeHardFindings':counts['error'],'PThreeReviewFindings':counts['review'],
            'PThreeUnassessed':counts['unassessed']}
    tex='% Generated by scripts/build_short_paper_report.py; counts are structural, never reader scores.\n'
    tex+=''.join('\\newcommand{\\'+key+'}{'+str(value)+'}\n' for key,value in values.items())
    lines=['# Replayed short-paper audit','',f"Systems selection: `{report['system_paper_id']}`.",'',
           '| Paper | Assertion environments/spans | Hard findings | Review flags | Narrative status |',
           '|---|---:|---:|---:|---|']
    for p in papers:
        c=Counter(f['severity'] for f in p['findings'])
        lines.append(f"| {p['paper_id']} | {len(p['assertions'])} | {c['error']} | {c['review']} | Unassessed |")
    lines+=['','An assertion count is the native statement inventory, not a count of all factual prose claims. '
            'The audit checks source consistency and visible recorded marks; it reruns no mathematical proof. '
            'Style review flags are candidates, not correctness defects.','', '## Located findings','']
    for p in papers:
        lines += ['### '+p['paper_id'],'']
        for f in p['findings']:
            lines.append(f"- **{f['rule']} / {f['severity']}**, `{f['path']}:{f['line']}`: {f['message']}")
        lines.append('')
    return '\n'.join(lines)+'\n',tex


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--report',type=Path,required=True);p.add_argument('--out-dir',type=Path,required=True)
    a=p.parse_args();data=json.loads(a.report.read_text());md,tex=render(data);a.out_dir.mkdir(parents=True,exist_ok=True)
    (a.out_dir/'lint.md').write_text(md);(a.out_dir/'counts.tex').write_text(tex)
    print(json.dumps({'status':'rendered','report_sha256':digest(a.report.read_bytes())}))
if __name__=='__main__':main()
