#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Will Cook
# SPDX-License-Identifier: Apache-2.0
"""Build the no-clone reading edition from the sources the papers come from.

Inputs (all tracked, none hand-copied into the outputs):

  docs/papers/corpus.json               paper inventory and publication classes
  docs/papers/full-text/*.md            generated text of each manuscript
  docs/reading-edition/INTRODUCTION.md  authored introduction
  skills/explore-the-corpus/SKILL.md    the shared research instruction region
  research/experiments/choices_contraction/README.md   worked example, embedded whole

Outputs under docs/reading-edition/:

  plectis-reading-edition.md   starter: introduction, research instruction, the
                               cross-problem paper in full, and for each problem the
                               abstract and opening sections of its short paper
                               with its references, then the worked example in
                               full
  plectis-short-papers.md      the cross-problem paper and the eight short papers in
                               full, one file
  README.md                    index of every active mathematical paper with
                               sizes, raw links, and the command that writes
                               the complete mathematical collection on demand

The builder assembles and links.  It never rewrites a mathematical sentence,
never assigns a status, and never decides that a conjecture is a theorem.

    python3 scripts/build_reading_edition.py            # write
    python3 scripts/build_reading_edition.py --check    # fail when stale
    python3 scripts/build_reading_edition.py --complete out.md
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote, unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reading-edition"
CORPUS = ROOT / "docs" / "papers" / "corpus.json"
INTRODUCTION = OUT / "INTRODUCTION.md"
SKILL = ROOT / "skills" / "explore-the-corpus" / "SKILL.md"
RAW = "https://raw.githubusercontent.com/wcook04/plectis-erdos/main/"
BLOB = "https://github.com/wcook04/plectis-erdos/blob/main/"
BEGIN = "<!-- BEGIN shared_research_instruction -->"
END = "<!-- END shared_research_instruction -->"
SYNTHESIS_PAPER_ID = "optimal-sparse-perturbations"
PROBLEM_RE = re.compile(r"#(\d+)")
GENERATED = (
    "<!-- Generated by scripts/build_reading_edition.py from docs/papers/corpus.json,\n"
    "     docs/papers/full-text/, docs/reading-edition/INTRODUCTION.md and the shared\n"
    "     instruction in skills/explore-the-corpus/SKILL.md. Do not edit by hand. -->\n"
)


class ReadingEditionError(RuntimeError):
    pass


def shared_instruction() -> str:
    text = SKILL.read_text(encoding="utf-8")
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ReadingEditionError("the skill must carry exactly one shared instruction region")
    body = text.split(BEGIN, 1)[1].split(END, 1)[0].strip()
    if "python3 " in body or "scripts/" in body:
        raise ReadingEditionError(
            "the shared research instruction must not tell a reader without a clone to run repository commands"
        )
    return body


def mathematical_papers() -> list[dict]:
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    rows = []
    for paper in corpus["papers"]:
        if paper.get("publication_state") != "active" or paper.get("subject_kind") != "problem":
            continue
        numbers = PROBLEM_RE.findall(paper.get("subject", ""))
        if len(numbers) != 1:
            raise ReadingEditionError(f"cannot read one problem number from {paper['paper_id']}")
        path = ROOT / paper["local_full_text"]
        if not path.is_file():
            raise ReadingEditionError(f"missing full text for {paper['paper_id']}")
        rows.append({**paper, "problem": int(numbers[0]), "text_path": path})
    short = [r for r in rows if r["publication_class"] == "problem_paper"]
    long_ = [r for r in rows if r["publication_class"] == "reasoning_surface"]
    problems = sorted({r["problem"] for r in rows})
    if sorted(r["problem"] for r in short) != problems or sorted(r["problem"] for r in long_) != problems:
        raise ReadingEditionError("every problem needs exactly one short paper and one longer record")
    return sorted(rows, key=lambda r: (r["problem"], r["publication_class"]))


def synthesis_papers() -> list[dict]:
    """One paper contains the cross-problem results and their research record."""
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    rows = [paper for paper in corpus["papers"]
            if paper.get("subject_kind") == "synthesis"
            and paper.get("publication_state") in ("active", "pending_source_publication")]
    if len(rows) != 1 or rows[0].get("paper_id") != SYNTHESIS_PAPER_ID:
        raise ReadingEditionError("exactly one canonical cross-problem paper is required")
    paper = rows[0]
    if paper.get("publication_class") != "synthesis_paper":
        raise ReadingEditionError("the cross-problem paper must retain its synthesis class")
    path = ROOT / paper["local_full_text"]
    if not path.is_file():
        raise ReadingEditionError(f"missing full text for {paper['paper_id']}")
    return [{**paper, "text_path": path}]


def fingerprint(papers: list[dict], instruction: str) -> str:
    digest = hashlib.sha256()
    for row in papers:
        digest.update(row["paper_id"].encode())
        digest.update(row["text_path"].read_bytes())
    digest.update(INTRODUCTION.read_bytes())
    digest.update(instruction.encode())
    for rel in WORKED_EXAMPLES:
        digest.update((ROOT / rel).read_bytes())
    return digest.hexdigest()[:16]


def demote(markdown: str, levels: int) -> str:
    """Shift ATX headings down so each paper nests under its edition heading."""
    out, fenced = [], False
    for line in markdown.splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            line = "#" * min(6, hashes + levels) + line[hashes:]
        out.append(line)
    return "\n".join(out)


OPENING_TARGET_BYTES = 16_000
BIBLIOGRAPHY_RE = re.compile(r'<div class="thebibliography">.*?</div>', re.DOTALL)
ANCHOR_ID_RE = re.compile(r'\b(id|data-reference)="([^"]+)"')
ANCHOR_HREF_RE = re.compile(r'href="#([^"]+)"')
MD_ANCHOR_RE = re.compile(r'\]\(#([^)]+)\)')
WORKED_EXAMPLES = ("research/experiments/choices_contraction/README.md",)


def top_level_cuts(markdown: str) -> list[int]:
    """Line indices of top-level headings outside fenced blocks."""
    cuts, fenced = [], False
    for index, line in enumerate(markdown.splitlines()):
        if line.lstrip().startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("# "):
            cuts.append(index)
    return cuts


def opening(markdown: str) -> tuple[str, bool]:
    """Title, abstract and whole opening sections, cut only at a section boundary.

    The first cut stopped at the third top-level heading. A reader given only
    the starter file showed that this ended four papers before the result
    their abstract announces. Sections are now added whole until the entry
    reaches OPENING_TARGET_BYTES. The second value says whether anything of
    the paper body was left out.
    """
    lines = markdown.splitlines()
    cuts = top_level_cuts(markdown)
    body_end = len(lines)
    match = BIBLIOGRAPHY_RE.search(markdown)
    if match:
        body_end = markdown[: match.start()].count("\n")
    for cut in cuts[2:]:
        if cut >= body_end:
            break
        if len("\n".join(lines[:cut]).encode()) >= OPENING_TARGET_BYTES:
            return "\n".join(lines[:cut]).rstrip(), True
    return "\n".join(lines[:body_end]).rstrip(), False


def bibliography(markdown: str) -> str:
    match = BIBLIOGRAPHY_RE.search(markdown)
    return match.group(0) if match else ""


def scope_anchors(markdown: str, paper_id: str) -> str:
    """Prefix in-paper anchors so eight papers can share one file.

    Every short paper uses ids such as sec:problem, so a plain concatenation
    sends each internal link to the first paper that defined the id.
    """
    markdown = ANCHOR_ID_RE.sub(lambda m: f'{m.group(1)}="{paper_id}--{m.group(2)}"', markdown)
    markdown = ANCHOR_HREF_RE.sub(lambda m: f'href="#{paper_id}--{m.group(1)}"', markdown)
    return MD_ANCHOR_RE.sub(lambda m: f"](#{paper_id}--{m.group(1)})", markdown)


def tex_title(title: str) -> str:
    """Render a TeX fragment inside a paper title as mathematics."""
    return re.sub(r"(\\[A-Za-z]+.*)$", lambda m: "$`" + m.group(1) + "`$", title)


def public_links(markdown: str, source: str | Path) -> str:
    """Keep source-relative links usable after moving text into an edition."""
    base = (ROOT / source).parent

    def absolute(match: re.Match) -> str:
        target = match.group("target")
        if target is None:
            return match.group(0)
        parts = urlsplit(target)
        if parts.scheme or parts.netloc or not parts.path:
            return match.group(0)
        try:
            resolved = (base / unquote(parts.path)).resolve().relative_to(ROOT.resolve())
        except ValueError as error:
            raise ReadingEditionError(f"link outside the repository in {source}: {target}") from error
        url = BLOB + quote(resolved.as_posix(), safe="/")
        if parts.query:
            url += "?" + parts.query
        if parts.fragment:
            url += "#" + parts.fragment
        return f"]({url})"

    # Coefficient notation such as [z^k](z;q) is not a Markdown link inside
    # mathematics. Preserve code spans, fenced blocks and math delimiters
    # before considering the link-target alternative.
    return re.sub(
        r"(?P<ticks>`+).*?(?P=ticks)|(?P<tildes>~{3,}).*?(?P=tildes)"
        r"|(?P<dollars>\${1,2}).*?(?P=dollars)|\]\((?P<target>[^)\s]+)\)",
        absolute, markdown, flags=re.DOTALL,
    )


def paper_text(row: dict) -> str:
    return public_links(row["text_path"].read_text(encoding="utf-8"), row["text_path"])


def worked_examples() -> str:
    parts = []
    for rel in WORKED_EXAMPLES:
        text = (ROOT / rel).read_text(encoding="utf-8")
        text = re.sub(r"^<!--.*?-->\n", "", text, flags=re.MULTILINE).strip()
        text = public_links(text, rel)
        parts.append(scope_anchors(demote(text, 2), Path(rel).parent.name))
    return "\n\n".join(parts)


def size(path: Path) -> str:
    return f"{path.stat().st_size / 1024:,.0f} KB"


def header(title: str, edition: str) -> str:
    return (
        f"{GENERATED}\n# {title}\n\n"
        f"Edition fingerprint `{edition}`. Papers CC-BY-4.0, Will Cook, 2026. "
        f"Source: <https://github.com/wcook04/plectis-erdos>. "
        f"Website: <https://wcook04.github.io/plectis/maths/>.\n"
    )


def paper_heading(row: dict) -> str:
    rel = row["local_full_text"]
    return (
        f"## Erdős #{row['problem']}: {tex_title(row['title'])}\n\n"
        f"*{row['question_this_paper_answers']}* "
        f"[Full text]({BLOB}{rel}) · [PDF]({BLOB}{row['local_pdf']})\n"
    )


def synthesis_heading(row: dict) -> str:
    """A synthesis paper has no single problem number."""
    rel = row["local_full_text"]
    return (
        f"## Reading the eight together: {tex_title(row['title'])}\n\n"
        f"*{row['question_this_paper_answers']}* "
        f"[Full text]({BLOB}{rel}) · [PDF]({BLOB}{row['local_pdf']})\n"
    )


def synthesis_entry(rows: list[dict]) -> str:
    """The complete cross-problem paper, including its proofs and research record."""
    if len(rows) != 1 or rows[0]["paper_id"] != SYNTHESIS_PAPER_ID:
        raise ReadingEditionError("exactly one canonical cross-problem paper is required")
    paper = rows[0]
    return synthesis_heading(paper) + "\n" + scope_anchors(
        demote(paper_text(paper), 2), paper["paper_id"]
    )


def build() -> dict[Path, str]:
    papers = mathematical_papers()
    synthesis = synthesis_papers()
    instruction = shared_instruction()
    edition = fingerprint(synthesis + papers, instruction)
    short = [r for r in papers if r["publication_class"] == "problem_paper"]
    long_ = {r["problem"]: r for r in papers if r["publication_class"] == "reasoning_surface"}
    intro = INTRODUCTION.read_text(encoding="utf-8").split("-->", 2)[-1].strip()

    front = [
        header("Plectis reading edition: eight Erdős problems", edition),
        intro,
        "## The research instruction\n\n" + instruction,
    ]

    starter = list(front)
    starter.append(synthesis_entry(synthesis))
    starter.append(
        "## The mathematics, problem by problem\n\n"
        "Each entry gives the abstract and the opening sections of the short paper, cut at a "
        "section boundary, followed by that paper's references. Each entry says where it stops. "
        "The longer research record keeps the computations, the routes that stopped and the reasons."
    )
    for row in short:
        record = long_[row["problem"]]
        text = paper_text(row)
        body, truncated = opening(text)
        note = (
            f"*This entry ends here, at a section boundary. Later sections of the paper, and "
            f"anything the text above says is given below, are in "
            f"[the full short paper]({BLOB}{row['local_full_text']}) "
            f"({size(row['text_path'])} as text) and in `plectis-short-papers.md`.*"
            if truncated else "*This entry is the complete short paper.*"
        )
        references = bibliography(text)
        starter.append(
            paper_heading(row)
            + f"\nLonger record: [{record['title']}]({BLOB}{record['local_full_text']}) "
            f"({size(record['text_path'])} as text).\n\n"
            + scope_anchors(demote(body, 2), row["paper_id"])
            + "\n\n" + note
            + ("\n\n#### References cited in this paper\n\n" + references if references else "")
        )
    starter.append("## Worked example in full\n\n" + worked_examples())

    full_short = list(front)
    full_short.append(synthesis_entry(synthesis))
    for row in short:
        full_short.append(
            paper_heading(row) + "\n"
            + scope_anchors(demote(paper_text(row), 2), row["paper_id"])
        )

    starter_text = "\n\n".join(starter).rstrip() + "\n"
    short_text = "\n\n".join(full_short).rstrip() + "\n"

    total = sum(r["text_path"].stat().st_size for r in synthesis + papers)
    index = [
        header("Reading edition", edition),
        "Read the mathematics with your own AI model, or without one, and without a clone. "
        "All three files come from one builder and one set of sources, so they agree with the "
        "papers and with each other.\n",
        "| File | Contents | Size |\n|---|---|---:|",
        f"| [plectis-reading-edition.md](plectis-reading-edition.md) | Start here. Introduction, "
        f"research instruction, the cross-problem paper in full, the opening sections and references of each short paper, and one worked example in full. "
        f"[Raw]({RAW}docs/reading-edition/plectis-reading-edition.md) | {len(starter_text.encode()) / 1024:,.0f} KB |",
        f"| [plectis-short-papers.md](plectis-short-papers.md) | The same front matter with the "
        f"cross-problem paper and all eight short papers in full. [Raw]({RAW}docs/reading-edition/plectis-short-papers.md) "
        f"| {len(short_text.encode()) / 1024:,.0f} KB |",
        f"| Complete edition | All {len(synthesis) + len(papers)} papers below. Written on demand, because it repeats "
        f"`docs/papers/full-text/`. | {total / 1024:,.0f} KB |",
        "\n```sh\npython3 scripts/build_reading_edition.py --complete plectis-complete-edition.md\n```\n",
        "A model with a small context window should take the starter file first and then single "
        "papers. The sizes are printed so that nobody has to discover them by failing.\n",
        "## Every paper as text\n",
        "| Problem | Paper | Kind | Size | Raw text |\n|---|---|---|---:|---|",
    ]
    kinds = {
        "problem_paper": "short paper",
        "synthesis_paper": "cross-problem paper",
        "reasoning_surface": "longer record",
    }
    for row in synthesis + papers:
        kind = kinds[row["publication_class"]]
        label = f"#{row['problem']}" if "problem" in row else "Eight together"
        rel = row["local_full_text"]
        index.append(
            f"| {label} | [{row['title']}](../../{rel}) | {kind} | "
            f"{size(row['text_path'])} | [raw]({RAW}{rel}) |"
        )
    index.append(
        "\nThe introduction is authored in [INTRODUCTION.md](INTRODUCTION.md). The research "
        "instruction is the marked region of "
        "[skills/explore-the-corpus/SKILL.md](../../skills/explore-the-corpus/SKILL.md); a clone "
        "and this edition therefore give the same instruction. Rebuild with "
        "`python3 scripts/build_reading_edition.py`; `--check` fails when any output is stale."
    )
    return {
        OUT / "plectis-reading-edition.md": starter_text,
        OUT / "plectis-short-papers.md": short_text,
        OUT / "README.md": "\n".join(index).rstrip() + "\n",
    }


def complete(target: Path) -> None:
    papers = synthesis_papers() + mathematical_papers()
    instruction = shared_instruction()
    edition = fingerprint(papers, instruction)
    intro = INTRODUCTION.read_text(encoding="utf-8").split("-->", 2)[-1].strip()

    def entry(row: dict) -> str:
        if "problem" in row:
            return f"- Erdős #{row['problem']}: {row['title']}"
        return f"- Reading the eight together: {row['title']}"

    parts = [
        header(f"Plectis complete reading edition: {len(papers)} papers on eight Erdős problems", edition),
        intro,
        "## The research instruction\n\n" + instruction,
        "## Contents\n\n" + "\n".join(entry(r) for r in papers),
    ]
    for row in papers:
        heading = paper_heading(row) if "problem" in row else synthesis_heading(row)
        parts.append(heading + "\n" + scope_anchors(demote(paper_text(row), 2), row["paper_id"]))
    target.write_text("\n\n".join(parts).rstrip() + "\n", encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build or check the no-clone reading edition.")
    ap.add_argument("--check", action="store_true", help="fail when a tracked output is stale")
    ap.add_argument("--complete", type=Path, help="write the complete mathematical paper collection here")
    args = ap.parse_args(argv)
    try:
        if args.complete:
            complete(args.complete)
            print(f"reading edition: wrote {args.complete} ({size(args.complete)})")
            return 0
        outputs = build()
        stale = [
            path for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if args.check:
            if stale:
                for path in stale:
                    print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
                print("run: python3 scripts/build_reading_edition.py", file=sys.stderr)
                return 1
            print(f"reading edition: current ({len(outputs)} files)")
            return 0
        for path, text in outputs.items():
            path.write_text(text, encoding="utf-8")
        print(f"reading edition: wrote {len(outputs)} files, {len(stale)} changed")
        return 0
    except ReadingEditionError as error:
        print(f"reading edition: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
