#!/usr/bin/env python3
"""Exact two-window projective-coherence witness for Erdős #269.

For reduced denominator B=11, two actual dyadic windows have canonical endpoint
carries that separately satisfy the proved size and coprimality constraints.
The carries nevertheless violate the Lean-checked projective congruence linking
any two endpoints of one rational candidate.  This shows that paired-window
coherence is strictly stronger than either local residue test on its own.
"""

from __future__ import annotations

import argparse
import json
import sys
from math import gcd
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from formal_math.erdos257_period_noncollapse.scripts.check_erdos269_dyadic_windows import (  # noqa: E402
    build_dyadic_blocks,
    certificate,
)
from system.lib.formal_math_experiment_contract import (  # noqa: E402
    build_experiment_contract,
    source_record,
    validate_experiment_contract,
)


SOURCE_REF = (
    "formal_math/erdos257_period_noncollapse/scripts/"
    "check_erdos269_projective_window_pair.py"
)
WINDOW_ENGINE_REF = (
    "formal_math/erdos257_period_noncollapse/scripts/"
    "check_erdos269_dyadic_windows.py"
)
ANALYSIS_REF = (
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos269/"
    "DyadicWindowComputationalLab.md"
)
CONSUMER_REF = (
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos269/"
    "HalfHeightDenominatorTransport.lean"
)
DEFAULT_OUTPUT = REPO_ROOT / (
    "state/formal_math/erdos257_period_noncollapse/"
    "erdos269_projective_window_pair_receipt.json"
)


def three_prime_height_at_dyadic_scale(scale: int) -> int:
    cutoff = 1 << scale
    height = 1
    for prime in (2, 3, 5):
        power = 1
        while power * prime <= cutoff:
            power *= prime
        height *= power
    return height


def endpoint_certificate(
    blocks: list[tuple[int, int, int]],
    *,
    denominator: int,
    start: int,
    length: int,
) -> dict[str, Any]:
    result = certificate(blocks, denominator, start, length)
    endpoint_scale = start + length
    residue = int(result["least_positive_residue"])
    assert result["base_clears_bound"]
    assert not result["consumer_fires"]
    assert residue <= result["short_bound"]
    assert gcd(residue, denominator) == 1
    return {
        **result,
        "endpoint_dyadic_scale": endpoint_scale,
        "endpoint_height": three_prime_height_at_dyadic_scale(endpoint_scale),
        "endpoint_height_mod_denominator": (
            three_prime_height_at_dyadic_scale(endpoint_scale) % denominator
        ),
        "residue_is_locally_size_admissible": True,
        "residue_is_coprime_to_denominator": True,
    }


def build_witness() -> dict[str, Any]:
    denominator = 11
    blocks = build_dyadic_blocks(8)
    first = endpoint_certificate(blocks, denominator=denominator, start=1, length=3)
    second = endpoint_certificate(blocks, denominator=denominator, start=4, length=3)

    assert first["least_positive_residue"] == 61
    assert first["short_bound"] == 150
    assert first["window_base"] == 360
    assert first["window_forcing"] == 289
    assert first["endpoint_height_mod_denominator"] == 5
    assert second["least_positive_residue"] == 259
    assert second["short_bound"] == 398
    assert second["window_base"] == 1800
    assert second["window_forcing"] == 4231
    assert second["endpoint_height_mod_denominator"] == 2

    defect = (
        first["least_positive_residue"] * second["endpoint_height"]
        - second["least_positive_residue"] * first["endpoint_height"]
    ) % denominator
    assert defect == 4
    return {
        "reduced_denominator": denominator,
        "first_endpoint": first,
        "second_endpoint": second,
        "projective_congruence_required": (
            "d_first * height_second == d_second * height_first (mod B)"
        ),
        "projective_defect_mod_denominator": defect,
        "projective_congruence_holds": False,
        "both_one_window_size_consumers_fire": False,
        "both_nonunit_residue_consumers_fire": False,
        "paired_projective_consumer_fires": True,
    }


def build_receipt() -> dict[str, Any]:
    witness = build_witness()
    contract = build_experiment_contract(
        problem_id="erdos_269",
        target_statement=(
            "Prove irrationality for the running-LCM series generated by the "
            "prime support {2,3,5}."
        ),
        claim_ceiling=(
            "One exact reduced-denominator mechanism witness; no universal "
            "denominator exclusion, cofinal window supply, or irrationality proof."
        ),
        hypothesis_id="local_window_admissibility_implies_pairwise_compatibility",
        hypothesis_statement=(
            "Canonical carries that are individually below their short bounds "
            "and coprime to the reduced denominator can arise together from one "
            "rational candidate."
        ),
        probe_id="exact_two_window_projective_shadow",
        probe_question=(
            "Can two individually admissible exact endpoint residues violate the "
            "projective congruence forced by a common rational numerator?"
        ),
        computation=(
            "Construct the actual {2,3,5} block windows ending at dyadic scales "
            "4 and 7 for B=11, recover each canonical endpoint carry under the "
            "proved size window, compute the exact running heights, and evaluate "
            "the cross-product defect modulo B."
        ),
        falsifier=(
            "A nonzero projective defect for two residues that separately pass "
            "the local size and coprimality consumers."
        ),
        stop_condition=(
            "Stop at the first exact pair demonstrating strict separation between "
            "local admissibility and global projective coherence; do not enlarge "
            "the denominator rectangle merely to accumulate kills."
        ),
        survival_consequence=(
            "If every locally admissible pair were projectively coherent, the "
            "two-window consumer would add no exclusion power beyond local tests."
        ),
        falsification_consequence=(
            "A violating pair opens projective cross-window coherence as an "
            "independent denominator-elimination mechanism and redirects the "
            "producer toward cofinal pairs rather than only large residues."
        ),
        consumer_ref=CONSUMER_REF,
        analysis_refs=[ANALYSIS_REF, CONSUMER_REF],
        source_refs=[SOURCE_REF, WINDOW_ENGINE_REF],
        result_status="exact_one_way_result",
        result_summary=(
            "For B=11 the exact endpoint residues 61 and 259 are separately "
            "within bounds 150 and 398 and coprime to 11, so neither local "
            "consumer fires.  Their endpoint heights are 5 and 2 modulo 11, "
            "but 61*2-259*5 is 4 modulo 11.  The Lean-checked projective shadow "
            "therefore excludes the pair."
        ),
    )
    validate_experiment_contract(contract, repo_root=REPO_ROOT)
    return {
        "schema": "erdos269-projective-window-pair/1",
        "status": "verified_exact_projective_pair_mechanism_opening",
        "experiment_contract": contract,
        "witness": witness,
        "consequence_decisions": [
            {
                "mechanism": "one_window_size_or_nonunit_residue_only",
                "decision": "strictly_incomplete",
                "reason": "both endpoint residues pass both local tests",
            },
            {
                "mechanism": "two_window_projective_coherence",
                "decision": "opened_with_exact_consumer_firing_witness",
                "reason": "the height-weighted cross-product defect is 4 modulo 11",
            },
            {
                "mechanism": "universal_denominator_exclusion_or_irrationality",
                "decision": "not_claimed",
                "reason": "one reduced denominator and one finite pair are certified",
            },
        ],
        "source_records": [
            source_record(REPO_ROOT, SOURCE_REF),
            source_record(REPO_ROOT, WINDOW_ENGINE_REF),
            source_record(REPO_ROOT, ANALYSIS_REF),
            source_record(REPO_ROOT, CONSUMER_REF),
        ],
    }


def emit(payload: dict[str, Any], output: Path, check: bool) -> int:
    rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            print(f"stale receipt: {output}", file=sys.stderr)
            return 1
        print(json.dumps({"status": "current", "output": str(output)}))
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(json.dumps({"status": "written", "output": str(output)}))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return emit(build_receipt(), args.output, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
