#!/usr/bin/env python3
"""Check an exact Erdős #243 clean-negative-prefix/tiny-reset falsifier.

The canonical seed is generated by the same finite ``E=-1`` construction as
``verify_erdos243_cancellation_free_blocks.py``.  Instead of stopping at the
declared block boundary, this checker follows the actual reduced rational
orbit until its first nontrivial cancellation.  The resulting exact witness
tests whether the length of the immediately preceding negative, cancellation-
free prefix can by itself force a large reset payment.

This is a finite counterexample to a local payment inequality.  It is not an
infinite orbit and does not settle Erdős #243.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from functools import reduce
from operator import mul
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from system.lib.formal_math_experiment_contract import (  # noqa: E402
    build_experiment_contract,
    source_record,
    validate_experiment_contract,
)


SCRIPT_REF = (
    "formal_math/erdos257_period_noncollapse/scripts/"
    "check_erdos243_clean_prefix_tiny_reset.py"
)
NOTE_REF = (
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos243/"
    "CleanPrefixTinyResetComputationalLab.md"
)
PACKET_REF = (
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos243/"
    "research_packet.json"
)
LEAN_REFS = [
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos243/"
    "DynamicCancellation.lean",
    "formal_math/erdos257_period_noncollapse/ErdosProblems/Erdos243/"
    "SparseResetRecovery.lean",
]


def _digest(value: int) -> str:
    return hashlib.sha256(str(value).encode("ascii")).hexdigest()


def _integer_record(value: int) -> dict[str, Any]:
    absolute = abs(value)
    return {
        "sign": (value > 0) - (value < 0),
        "decimal_digits": 1 if absolute == 0 else len(str(absolute)),
        "bit_length": absolute.bit_length(),
        "sha256_decimal": _digest(value),
    }


def reduced_step(u: int, v: int) -> dict[str, int]:
    """Apply one exact centred, dynamically reduced rational-tail step."""

    if not (0 < u <= v) or math.gcd(u, v) != 1:
        raise ValueError("require a positive reduced rational u/v")
    nearest = (2 * v + u) // (2 * u)
    a = nearest + 1
    e = v - nearest * u
    raw_u = a * u - v
    raw_v = a * v
    h = math.gcd(raw_u, raw_v)

    assert raw_u == u - e
    assert h == math.gcd(a * a, raw_u)
    assert raw_u % h == 0 and raw_v % h == 0
    u_next = raw_u // h
    v_next = raw_v // h
    assert math.gcd(u_next, v_next) == 1
    assert 2 * abs(e) < u
    return {
        "a": a,
        "e": e,
        "h": h,
        "u_next": u_next,
        "v_next": v_next,
    }


def canonical_seed(
    *, tail_start: int = 16, guaranteed_height: int = 5, scale: int = 1
) -> tuple[int, int, dict[str, int]]:
    if tail_start < 2 or guaranteed_height < 1 or scale < 1:
        raise ValueError("require tail_start >= 2, guaranteed_height >= 1, scale >= 1")
    k = scale * reduce(
        mul, (tail_start + j for j in range(2, guaranteed_height + 2)), 1
    )
    a = 1 + (tail_start + 1) * k
    v = (a - 1) * tail_start - 1
    return tail_start, v, {
        "tail_start": tail_start,
        "guaranteed_height": guaranteed_height,
        "scale": scale,
        "k": k,
        "a": a,
    }


def check_witness(max_steps: int = 16) -> dict[str, Any]:
    u, v, seed = canonical_seed()
    rows: list[dict[str, Any]] = []
    first_reset: dict[str, Any] | None = None

    for index in range(max_steps):
        step = reduced_step(u, v)
        row = {
            "index": index,
            "u": _integer_record(u),
            "v": _integer_record(v),
            "a": _integer_record(step["a"]),
            "centered_error": step["e"],
            "payment": step["h"],
            "u_next": _integer_record(step["u_next"]),
        }
        rows.append(row)
        if step["h"] > 1:
            first_reset = row
            break
        if step["e"] >= 0:
            raise AssertionError("canonical trace left the negative branch before a reset")
        u, v = step["u_next"], step["v_next"]

    if first_reset is None:
        raise AssertionError(f"no reset found within {max_steps} exact steps")

    prefix = rows[:-1]
    prefix_length = len(prefix)
    assert prefix_length == 8
    assert all(row["centered_error"] < 0 and row["payment"] == 1 for row in prefix)
    assert [row["centered_error"] for row in prefix] == [-1] * 7 + [-4]
    assert first_reset["centered_error"] == -7
    assert first_reset["payment"] == 2
    proposed_lower_bound = 2**prefix_length
    assert first_reset["payment"] < proposed_lower_bound

    return {
        "seed": {
            key: (_integer_record(value) if key in {"k", "a"} else value)
            for key, value in seed.items()
        },
        "trace": rows,
        "first_reset": {
            "index": first_reset["index"],
            "preceding_negative_cancellation_free_length": prefix_length,
            "preceding_centered_errors": [row["centered_error"] for row in prefix],
            "centered_error_at_reset": first_reset["centered_error"],
            "payment": first_reset["payment"],
            "two_to_prefix_length": proposed_lower_bound,
            "strict_falsification": first_reset["payment"] < proposed_lower_bound,
        },
        "verified_invariants": [
            "every stored state is a positive primitive rational pair",
            "2*abs(e)<u at every step",
            "h=gcd(a^2,u-e) at every step",
            "the eight steps before the first reset have e<0 and h=1",
            "the first reset has exact payment 2<2^8",
        ],
    }


def build_receipt() -> dict[str, Any]:
    witness = check_witness()
    contract = build_experiment_contract(
        problem_id="erdos_243",
        target_statement=(
            "Under a_(n+1)/a_n^2 -> 1 and rational reciprocal sum, force "
            "eventual Sylvester recurrence."
        ),
        claim_ceiling=(
            "Finite exact counterexample to a block-length-only single-reset payment "
            "bound; not an infinite orbit and not a solution of Erdős #243."
        ),
        hypothesis_id="clean_prefix_forces_exponential_single_reset_payment",
        hypothesis_statement=(
            "Whenever L consecutive negative centred steps have h=1 and are followed "
            "by a reset, the reset payment is at least 2^L."
        ),
        probe_id="canonical_e_minus_one_prefix_continued_to_first_reset",
        probe_question=(
            "Does the exact canonical finite E=-1 construction admit a long negative "
            "h=1 prefix whose first subsequent reset has tiny payment?"
        ),
        computation=(
            "Construct the canonical seed (tail_start,height,scale)=(16,5,1), continue "
            "the primitive rational cocycle exactly, and stop at its first h>1 step."
        ),
        falsifier=(
            "An exact trace with L negative h=1 steps immediately before a reset whose "
            "payment is less than 2^L."
        ),
        stop_condition="Stop at the first h>1 step or fail after 16 exact transitions.",
        survival_consequence=(
            "Survival would leave a block-length-only exponential payment lemma as a "
            "possible input to the global telescoping budget."
        ),
        falsification_consequence=(
            "A viable repair lower bound must charge global prefix/residue coherence or "
            "a product across complete recoveries; clean-prefix length alone cannot be "
            "converted into the required payment mass at the next reset."
        ),
        consumer_ref=PACKET_REF,
        analysis_refs=[NOTE_REF, *LEAN_REFS],
        source_refs=[SCRIPT_REF],
        result_status="exact_one_way_result",
        result_summary=(
            "The exact orbit has eight consecutive negative h=1 steps with errors "
            "[-1,-1,-1,-1,-1,-1,-1,-4], followed by e=-7 and reset payment h=2; "
            "therefore h>=2^L is false at L=8."
        ),
    )
    validate_experiment_contract(contract, repo_root=REPO_ROOT)
    return {
        "schema": "erdos243-clean-prefix-tiny-reset-receipt/1",
        "status": "verified_exact_counterexample",
        "experiment_contract": contract,
        "witness": witness,
        "source_records": [source_record(REPO_ROOT, ref) for ref in [SCRIPT_REF, NOTE_REF]],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    payload = json.dumps(build_receipt(), indent=2, sort_keys=True) + "\n"
    if args.output is None:
        print(payload, end="")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(payload, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
