import ExternalVerification1041SignedMomentTetranomial.Solution

#print axioms Erdos249257.ExternalVerification1041SignedMomentTetranomial.sum_normSq_const_add_mul
#print axioms Erdos249257.ExternalVerification1041SignedMomentTetranomial.exists_two_tails_norm_lt_one_of_exact_L2_budget
#print axioms Erdos249257.ExternalVerification1041SignedMomentTetranomial.exists_two_tetranomialRoot_safeSpokes_of_moment_coeff_budget
