import ErdosProblems.Erdos243.PaperCompleteR20.ScaleTwelve
import ErdosProblems.Erdos243.PaperCompleteR20.CubicModularSquareSpecialisation
import ErdosProblems.Erdos243.PaperCompleteR20.CubicSquareSpecializationAssembly
import ErdosProblems.Erdos243.PaperCompleteR20.TwoForbiddenWords

#print axioms ErdosProblems.Erdos243.PaperCompleteR20.scale_twelve
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.scale_twelve_of_square_in_rootField
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.zero_lower_density_forces_modular_root_square
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.natural_zero_lower_density_forces_modular_root_square
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.primitive_cubic_zero_density_impossible_of_square_specialisation
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.plus_one_forbidden_word
#print axioms ErdosProblems.Erdos243.PaperCompleteR20.minus_one_forbidden_word
#print axioms ErdosProblems.Erdos243.PaperCompleteR11.primitive_zero_density_paper_multiplier_lemma
