import ExternalVerification1041CyclicTetranomialCoefficient.Solution

#print axioms Erdos249257.ExternalVerification1041CyclicTetranomialCoefficient.tetranomialRoot_spoke_factorization
#print axioms Erdos249257.ExternalVerification1041CyclicTetranomialCoefficient.tetranomialRoot_spoke_norm_lt_one_of_rootBudget
#print axioms Erdos249257.ExternalVerification1041CyclicTetranomialCoefficient.tetranomialRoot_spoke_norm_lt_one_of_lowCoeffBudget
