#!/usr/bin/env python3
"""Erdos 251: generate the kernel-decidable denominator-floor certificate.

The Lean module ErdosProblems/Erdos251/KernelDenominatorFloor.lean proves, for
S = sum_{i>=0} p_i / 2^{i+1} (zero-based primes, p_0 = 2):

  * lo / 2^c <= S <= (2 lo + 5000 (c+1)^4) / 2^{c+1}, where c = pi(X) and
    lo = sum_{i<c} p_i 2^{c-1-i} is computed inside the kernel by trial
    division (primeSumLoop), with the tail bounded through the Lean-checked
    p_i <= 1250 (i+1)^4 and (c+1+j)^4 2^j <= (c+1)^4 3^j;
  * if u/v < lo/2^c and (2 lo + 5000 (c+1)^4)/2^{c+1} < u'/v' with
    u' v - u v' = 1, then every rational a/b equal to S has b >= v + v'
    (Farey neighbours);
  * the four inequalities are decided by `decide +kernel` on the literals
    emitted here.

This script computes c, lo, the tail bound, and picks u/v, u'/v' as two
consecutive convergents of lo/2^c that strictly bracket the whole interval.
It prints the literals, the resulting floor in bits and decimal digits, and
writes a JSON receipt.  All arithmetic is exact.
"""
from __future__ import annotations

import argparse
import json
import sys
from fractions import Fraction
from pathlib import Path

sys.set_int_max_str_digits(0)


def primes_below(limit: int) -> list[int]:
    sieve = bytearray([1]) * limit
    sieve[0] = sieve[1] = 0
    for i in range(2, int(limit ** 0.5) + 1):
        if sieve[i]:
            sieve[i * i::i] = bytearray(len(sieve[i * i::i]))
    return [i for i, v in enumerate(sieve) if v]


def convergents(x: Fraction):
    """Yield (p, q) convergents of x with the standard recurrence."""
    p0, q0, p1, q1 = 0, 1, 1, 0
    num, den = x.numerator, x.denominator
    while den:
        a, r = divmod(num, den)
        p0, p1 = p1, a * p1 + p0
        q0, q1 = q1, a * q1 + q0
        yield p1, q1
        num, den = den, r


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--X", type=int, default=10000, help="sieve limit; c = pi(X)")
    ap.add_argument("--lean-out", type=str, default="", help="write a Lean instance snippet here")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    X = args.X
    primes = primes_below(X)
    c = len(primes)
    assert c >= 9
    lo = sum(p * 2 ** (c - 1 - i) for i, p in enumerate(primes))
    lo_frac = Fraction(lo, 2 ** c)
    hi_num = 2 * lo + 5000 * (c + 1) ** 4
    hi_frac = Fraction(hi_num, 2 ** (c + 1))
    assert lo_frac < hi_frac

    # independent check of the bracket against a longer prefix
    more = primes_below(4 * X)
    S_more = sum(Fraction(p, 2 ** (i + 1)) for i, p in enumerate(more))
    assert lo_frac <= S_more <= hi_frac, "bracket does not contain a longer exact prefix"

    conv = list(convergents(lo_frac))
    # consecutive convergents (p_n/q_n, p_{n+1}/q_{n+1}) bracket lo_frac; find the last pair
    # that strictly brackets [lo_frac, hi_frac]
    chosen = None
    for n in range(len(conv) - 2, -1, -1):
        (pa, qa), (pb, qb) = conv[n], conv[n + 1]
        fa, fb = Fraction(pa, qa), Fraction(pb, qb)
        u, v, up, vp = (pa, qa, pb, qb) if fa < fb else (pb, qb, pa, qa)
        if Fraction(u, v) < lo_frac and hi_frac < Fraction(up, vp) and up * v - u * vp == 1:
            chosen = (n, u, v, up, vp)
            break
    assert chosen is not None
    n, u, v, up, vp = chosen
    floor_den = v + vp
    # kernel-side check replay (the exact Bool the Lean certCheck evaluates)
    assert u * 2 ** c < lo * v
    assert hi_num * vp < up * 2 ** (c + 1)
    assert up * v == u * vp + 1
    assert v > 0 and vp > 0
    bits = floor_den.bit_length() - 1
    digits = len(str(floor_den)) - 1
    ten_pow = 10 ** digits
    assert ten_pow <= floor_den

    receipt = {
        "probe_id": "erdos251_kernel_denominator_certificate",
        "X": X,
        "c_primes_below_X": c,
        "largest_prime": primes[-1],
        "lo_bits": lo.bit_length(),
        "tail_bound_bits_exponent": -(c + 1 - (5000 * (c + 1) ** 4).bit_length()),
        "convergent_index": n,
        "convergent_count": len(conv),
        "v_bits": v.bit_length(),
        "vprime_bits": vp.bit_length(),
        "floor_den_bits_ge": bits,
        "floor_den_decimal_digits_ge": digits,
        "floor_statement": f"any rational a/b equal to S has b >= 2^{bits} > 10^{digits}",
        "claim_boundary": "Exact finite computation; the kernel-checked theorem is in "
                          "KernelDenominatorFloor.lean. Not a statement about irrationality.",
    }
    if args.lean_out:
        snippet = (
            f"-- generated by formal_math/probes/erdos251_kernel_denominator_certificate.py --X {X}\n"
            f"def certX : ℕ := {X}\n"
            f"def certC : ℕ := {c}\n"
            f"def certU : ℕ := {u}\n"
            f"def certV : ℕ := {v}\n"
            f"def certU' : ℕ := {up}\n"
            f"def certV' : ℕ := {vp}\n"
            f"def certTenPow : ℕ := {digits}\n"
        )
        Path(args.lean_out).write_text(snippet)
        receipt["lean_snippet"] = args.lean_out
    out = Path("state/formal_math/probes/erdos251_kernel_denominator_certificate_receipt.json")
    if out.parent.exists():
        out.write_text(json.dumps(receipt, indent=1, ensure_ascii=False) + "\n")
        receipt["receipt_path"] = str(out)
    if args.json:
        print(json.dumps(receipt, indent=1, ensure_ascii=False))
    else:
        for k, val in receipt.items():
            print(f"{k}: {val}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
