import ExternalVerification251PrimeGapIdentity.Solution

#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_summable
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeGapSeries_summable
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_eq_two_add_primeGapSeries
#print axioms Erdos249257.ExternalVerification251PrimeGapIdentity.primeSeries_irrational_iff_primeGapSeries
